### ISSUE TITLE
Add check to reduce way name query sensitivity / update frequency

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1016]
We are currently querying the map data for the current way name that is being traveled along.  The querying is very precise and this sometimes causes the way name to update too frequently.  

We should add a check (similar to [iOS](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L782-L807)) to look forward and confirm that this change in way name is actually warranted.  

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/41256841-d1479318-6d98-11e8-88c4-185c021207ac.gif)

**Comment by 1ec5** [comment]
This screenshot also shows that the querying code could also filter out irrelevant features, such as those with the `class` property set to `path` while the user is driving.

**Comment by danesfeder** [comment]
Capturing productive voice with @1ec5 and @vincethecoder:

The check we are looking to add here takes the current step coordinates and measures 10 meters ahead of the current location.  Then, for each feature, we measure 10 meters ahead and 10 meters behind the current location.  

Finally, we measure between each of these points (10 meters ahead of user vs. 10 meters ahead _or_ behind feature.  This is pretty tough to convey via text so I also drew this (which may or may not help 😆):

![query_sensitivity](https://user-images.githubusercontent.com/8434572/43080514-def08084-8e5d-11e8-9af2-9d94ed8a74a5.png)

**Comment by 1ec5** [comment]
> 10 meters ahead of user vs. 10 meters ahead or behind feature.

The reason we measure both ways along the feature is that the vector tile would contain the same two-way road, with the coordinates ordered the same way, whether the route happens to travel forward or backward along it. (In the case of a one-way road, the route won’t travel backwards along the route anyways, so we don’t have to check for that case.)

> we determined it would be helpful to add a filter expression when adding the LineLayer to filter out unnecessary data that may be provided by the query

Note that this filtering should only take place for driving directions. For walking and cycling directions, the vector tiles don’t say whether bikes or pedestrians are allowed on a particular roadway, and the Directions API route doesn’t say whether a particular route segment travels along a road or other path. So there can only be a filter for driving directions.

> you can see this in the gif L Street Cycle Track

(sigh) Technically cycle tracks should be tagged on the roadway instead of mapped as separate ways, but the filter should work around that issue in any case.
