### ISSUE TITLE
Cannot set opacity on route colors

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1065]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.15.0

I would like to set an opacity on the alternative route color.
Maybe there's something I'm misunderstanding, but I would think it would be as easy as setting an alpha value in the color resource.

Example in my style whose parent is NavigationMapRoute:

`<item name="alternativeRouteColor">#37875bfa</item>`
looks the exact same as
`<item name="alternativeRouteColor">#875bfa</item>`

Do I need to set it elsewhere or is it just not possible at the moment?

**Comment by Guardiola31337** [comment]
Hey @cmahopper :wave: thanks for reaching out and report your issue.

You're right. This is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/1045 because of an issue upstream in the Maps SDK :eyes: https://github.com/mapbox/mapbox-gl-native/issues/12198 and it'll be fixed when https://github.com/mapbox/mapbox-gl-native/pull/12210 lands and we release a new version of the SDK with the patch. Stay tuned!

Closing as answered.
