### ISSUE TITLE
Route opacity looks weird because each step overlaps the next

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1084]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.16.0-beta.1

### Steps to trigger behavior

 1. Set the color of the alternate route to have an opacity of less than 100%
 2. Show the route on the map

### Expected behavior
Complete opacity along the entire route.

### Actual behavior
Because the lines of the route overlap, the route is not entirely transparent everywhere.
See screenshot:
![screenshot_20180705-133755](https://user-images.githubusercontent.com/40161549/42321370-fbfbd592-8058-11e8-953d-6c33ed05d0a6.png)

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

cc @cafesilencio

**Comment by cafesilencio** [comment]
This isn't an issue in the upcoming 1.0 SDK. There's only an overlap if you are going to be driving down the same street twice, for example with multiple waypoints taking you down the same street in different directions. This makes sense because the line is getting draw in the same place for part of the route. Notice the screen shot below.

![Screenshot_20200603-164025](https://user-images.githubusercontent.com/2249818/83699527-24040f00-a5b9-11ea-9a59-1ff1d07372dc.png)
