### ISSUE TITLE
Turning directions voice is wrong in Danish

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1101]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.16.0-beta.1

First of all, I have no idea what power you have over the voice or what it says, but I figured I'd post it here anyway, and you can close it or redirect me :)

In Danish, when the voice instructs you to turn left (or right), it says "Drej til venstresving" - literally, "Turn left turn" where it should be "Drej til venstre" (Turn left). Same goes with "Drej til højresving" -> "Drej til højre".

**Comment by danesfeder** [comment]
Hey @cmahopper 👋 thanks for the feedback here and spotting this issue.  Our voice instructions are sourced from https://github.com/Project-OSRM/osrm-text-instructions, so if you can open an issue there, that would be great.  

Specifically, please check out https://github.com/Project-OSRM/osrm-text-instructions/blob/master/CONTRIBUTING.md - if you're able to provide the updated translations, this would speed up the process of getting the fix deployed.

**Comment by 1ec5** [comment]
Hi @cmahopper, as @danesfeder noted, guidance instruction strings are maintained in the OSRM Text Instructions project. (We incorporate OSRMTI into the Directions API on the server side, so improvements to it will benefit all platforms.) I looked into the particular strings you mentioned above and opened Project-OSRM/osrm-text-instructions#258 to track the necessary changes.

By the way, you’re more than welcome to sign up for Transifex and request to join our Danish [translation team](https://www.transifex.com/project-osrm/osrm-text-instructions/) there. Whenever you see an incorrect translation, you can suggest a fix directly – less error-prone that way.

I’ll close this issue because the Android navigation SDK has no control over the particular wording of the instructions from the client side.
