### ISSUE TITLE
The position is not precise

### ISSUE THREAD

**Issue by dsilvera** [mapbox/mapbox-navigation-android#1114]
**Android API:** N/A
**Mapbox Navigation SDK version:** 0.15.0

### Steps to trigger behavior
Sometimes, I am teleported about few meters and the service detect an off route.

### Expected behavior
I am not teleported

### Expected behavior
I am teleported and I have offroute

### Actual behavior
I analyse the algo and I think the rule : 
`currentAccuracy <= locationAcceptableAccuracyInMetersThreshold `
is mandatory on all case.
If we have valid velocity and the new position is 5 second after last position, we do not check accuracy.

https://github.com/mapbox/mapbox-navigation-android/blob/4daaed8c79852294b3243229d2aa4f7bae70268c/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/LocationValidator.java#L74

What do you think about that?

Thank you

**Comment by danesfeder** [comment]
Moving with #1157

**Comment by Guardiola31337** [comment]
Hey @dsilvera 👋 in #1157 we rolled back the filtering mentioned above in favor of the less aggressive filter we had prior. This is available since [`0.17.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/0.17.0) (we have released `0.18.0` afterwards).

Is OP still an issue for you? Could you confirm? Thanks!

**Comment by danesfeder** [comment]
This should be resolved with `0.20.0`, thanks for checking out the SDK @dsilvera!
