### ISSUE TITLE
Having Issue with Navigating within a College Campus

### ISSUE THREAD

**Issue by adh81910** [mapbox/mapbox-navigation-android#1154]
I am currently a intern at Creighton University, and I am working on a project for in campus navigation. We planned on using MapBox directions API to help create navigation throughout the campus. 

The issue is that routes never go through the campus's local roads. Is there any way to add additional data to MapBox such that we can have defined walkways the API can use to navigate in the campus? Here is a snapshot of the issue we are currently seeing:

![capture _2018-07-25-08-23-01](https://user-images.githubusercontent.com/41595674/43203682-7d1e984a-8fe4-11e8-9bd4-78db38d5b6fb.png)

For reference, here is the actual campus map:

![image](https://user-images.githubusercontent.com/41595674/43204150-caad2382-8fe5-11e8-8102-ba3acc1f55a8.png)

**Comment by danesfeder** [comment]
Hey @adh81910 👋 thanks for the feedback here.  

From your screenshot, it looks like the directions profile you are using is `PROFILE_DRIVING_TRAFFIC` see also > https://www.mapbox.com/api-documentation/#retrieve-directions.  You'd update the `profile` [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L144) to `PROFILE_WALKING`.  Our [default profile](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L69) is the `PROFILE_DRIVING_TRAFFIC`.  

This should make the directions API consider walking paths rather than roads.  If you're still not seeing correct paths, this may be a data issue (path data is missing from OpenStreetMap).  See https://wiki.openstreetmap.org/wiki/Contribute_map_data.

Going to go ahead and close this, as it isn't an actual issue with the Navigation SDK.  Hope this helps!

cc @coxchapman @1ec5 if I'm missing anything here

**Comment by adh81910** [comment]
I tried to update the profile by adding a Builder class, and the issue still prevails. This means that I need to add data like pedestrian walkways to the map. How do I go about this?
