### ISSUE TITLE
voice instructions not working with Turkish

### ISSUE THREAD

**Issue by headbanggg** [mapbox/mapbox-navigation-android#1183]
**Android API:27**
**Mapbox Navigation SDK version:com.mapbox.mapboxsdk:mapbox-android-navigation:0.16.0**

Hello all,

 I use mapmatching in my app. I would like to get voice instructions as Turkish language.
In MapboxMapMatching.builder there are 2 methods available for setting language.
      *first method: language(Local language)
      *second method: language(String language).

I couldnt find Turkish language in Locale class. So I used second method with string parameter "tr" , which I found at [https://www.mapbox.com/api-documentation/#instructions-languages](url).

When I use .language("tr") I can log Turkish instructions in mapmatching response. I can see them on Navigation mode in instructions banner too. But unfortunately voice instructions are not working in Turkish. 
Is there any way to solve this issue?

My mapmatching builder function:
<img width="796" alt="screen shot 2018-08-03 at 09 27 36" src="https://user-images.githubusercontent.com/26357151/43629011-a3582c3e-9704-11e8-992d-8811b6c73f7a.png">

Locale class(There is no Turkish):
<img width="466" alt="screen shot 2018-08-03 at 09 26 54" src="https://user-images.githubusercontent.com/26357151/43628991-8aa083c6-9704-11e8-9973-085d95eb2abf.png">

**Comment by headbanggg** [comment]
Another question,
Is there any possibility to use local sound files instead of using mapbox voice instructions?

**Comment by danesfeder** [comment]
Hey @headbanggg, do you mean local sound files that reflect the text instructions provided?  I'm not completely following, my apologies. 

I think the issue here is a result of the conversion of the map matching response to `DirectionsRoute` the `voiceLanguage` attribute, which we use as a localization cue for voice instructions do not seem to be include.  I will look into opening a PR in `mapbox-java` to address this. cc @osana

**Comment by danesfeder** [comment]
Confirming this was an issue with `mapbox-java` fixed in https://github.com/mapbox/mapbox-java/pull/847.  

@headbanggg please stayed tuned here as we release `3.4.0` of the Java library and pull the new dependency here in the Navigation SDK.  This should not require any changes on your part other than updating the SDK.

**Comment by danesfeder** [comment]
Re-opening due to https://github.com/mapbox/mapbox-navigation-android/pull/1200 opened as a result of https://github.com/mapbox/mapbox-navigation-android/issues/1199
