### ISSUE TITLE
Incorrect then banner maneuver

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1228]
Found a weird behavior with the "then banner" 👀

![then_banner_icon_flipped_issue](https://user-images.githubusercontent.com/1668582/44397417-91f45900-a540-11e8-8d27-f18f2b37f88a.gif)

![then_banner_icon_left](https://user-images.githubusercontent.com/1668582/44397632-5312d300-a541-11e8-90ba-218e10d96cde.png)

![then_banner_icon_right](https://user-images.githubusercontent.com/1668582/44397635-56a65a00-a541-11e8-8ee6-35e8d5af0e26.png)

The then banner shows the next instruction after the immediate one and the maneuver is wrong.

_Route_

```java
.origin(Point.fromLngLat(-0.358568,39.49221))
.destination(Point.fromLngLat(-0.3606,39.490841))
```

After some 🕵️ the data seems to be 👌 so I guess it's an issue related to how we're populating the model. My hunch is that we're updating the model sooner than shouldn't because the next next instruction is a turn left. As you can 👀 in the video ☝️ this only affects the maneuver (turn left when should be right) - text is 🆗 (`Calle Humanista Frederic Furio`) 

Noting that there's a whole `sub` component that we aren't consuming so in order to fix this issue could better to just replace.

**Comment by boldtrn** [comment]
I have seen this issue as well.

My investigation so far, looks like we current use the modifier of the instruction after the then instruction.

In your example there are 2 right turns, followed by a left turn. So it looks like the then instructions consumes the direction from the left turn but the text is correctly consumed from the next banner instruction. The issue seems to happen if there is a `sub` component and if there is no `sub` component (only if the SDK decides to show the next banner instruction).
