### ISSUE TITLE
Runtime crashing on Map

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-navigation-android#1254]
A/libc: /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed

My added libraries :: 

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.4.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.7.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.18.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.2.1'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0') {
        transitive = true
    }

Can anyone please let me know, what version is stable?

**Comment by Guardiola31337** [comment]
Hey @mf-mindcrewtech 👋 thanks for reaching out and report your question.

I believe your conflict is because you're still using `mapbox-android-services` which is incompatible with the latest versions of the rest of the services. You should include `mapbox-sdk-services` instead. For context 👀 https://github.com/mapbox/mapbox-java/pull/664 and https://github.com/mapbox/mapbox-navigation-android/pull/697

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!

Closing as answered.

**Comment by mf-mindcrewtech** [comment]
@Guardiola31337 are you kidding me? You better help me to answer/solved this issue than close the issue.
