### ISSUE TITLE
Update willDisplay so it doesn't have to use abbreviationText

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1262]
See comment on the following pr:

https://github.com/mapbox/mapbox-navigation-android/pull/1233#discussion_r213715978

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
Looking at the code snippet in the comment referred to and the current implementation in the 1.0 SDK I don't think there is still an issue.

The current code doesn't mutate the banner instructions but instead will check if there is a BannerInstructionsListener and if non-null will return what comes from willDisplay() else it will return the instructions that came into the onBannderDisplay method.

Since this appears outdated I'm closing this ticket but if I misunderstood what the original issue was please reopen.
