### ISSUE TITLE
MapBox Navigation View show active route in different color

### ISSUE THREAD

**Issue by praveenposwal** [mapbox/mapbox-navigation-android#1266]
We are creating a navigation with multiple waypoints by using mapbox navigation view. Now we want to show current active route in different color. Is there any possibility of that?

**Mapbox Navigation SDK version:** com.mapbox.mapboxsdk:mapbox-android-navigation:0.18.0

Here is the code that  I have tried : 

 private void setCurrentLegPolylineOverlay(Integer legIndex, MapboxMap mapboxMap,RouteProgress routeProgress) {
        if (routeProgress != null) {

            String lineSourceID = "line-source-leg-" + legIndex.toString() + "-" + UUID.randomUUID().toString();

            String NAVIGATION_ROUTE_SOURCE = "mapbox-location-source";
            String NAVIGATION_ROUTE_LAYER = "mapbox-plugin-navigation-route-layer";

            LineLayer lineLayer = new LineLayer("currentLegLineLayer", lineSourceID);
         //   String placeLineBelowLayerID = "mapbox-plugin-navigation-route-layer";

            String  placeLineBelowLayerID = "mapbox-location-accuracy-layer";

            if (routeLayerExists(placeLineBelowLayerID,mapboxMap)) {
                float routeScale = 1.0f;
                lineLayer.setProperties(
                        PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                        PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND),
                        PropertyFactory.lineWidth(15f
                        ),
                        PropertyFactory.lineColor("#39dc19"),
                        PropertyFactory.lineOpacity(.5f),
                        PropertyFactory.fillOutlineColor(Color.BLACK)
                );
                mapboxMap.removeLayer(lineLayer);
                mapboxMap.addLayerBelow(lineLayer, placeLineBelowLayerID);

            }
        }
    }

    private Boolean routeLayerExists(String layerID, MapboxMap mapboxMap) {

        Boolean exists = false;

        List<Layer> styleLayers = mapboxMap.getLayers();
        for (int i = styleLayers.size() - 1; i >= 0; i--) {

            if (styleLayers.get(i).getId().equals(layerID)) {
                exists = true;
            }

        }

        return exists;
    }

**Comment by Guardiola31337** [comment]
Hey @praveenposwal 👋 thanks for reaching out and report your question.

Have you 👀 https://github.com/mapbox/mapbox-navigation-android/issues/291? It seems so because the code you attached is pretty similar to this one https://github.com/mapbox/mapbox-navigation-android/issues/291#issuecomment-333403082 If that's the case, I believe that using that code should work too for your use case. Could you give better context into why isn't working? Also, could you provide some screenshots of what you're 👀? This will help us determine what's happening here.

BTW, this issue tracker is only for bug reports with test cases and feature requests so in the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!

**Comment by danesfeder** [comment]
@praveenposwal any updates here?

**Comment by Guardiola31337** [comment]
Going to go ahead and closing here.

@praveenposwal Feel free to cut new tickets if you find any other issues and thanks for checking out the SDK!
