### ISSUE TITLE
Pass MapboxNavigationOptions to NavigationLauncher

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1274]
Hey,

I would like to disable manuallyEndNavigationUponCompletion when using your NavigationLauncher. 
This parameter is part of MapboxNavigationOptions and I wonder why NavigationLauncherOptions doesn't support it too. 

Why don't you let NavigationLauncherOptions support the whole functionality like MapboxNavigationOptions?

**Comment by danesfeder** [comment]
Hey @P-Zenker 👋 

Because we opt to keep the `NavigationLauncherOptions` lightweight as far as what you can package in them.  If you'd like more customization, you should roll with the `NavigationView` implementation like you're doing in some of the `Fragment` code I've seen from you.  This gives you full access to these options when initializing the `NavigationView`.
