### ISSUE TITLE
Incorrect behavior in Navigation View when set allowRerouteFrom to false.

### ISSUE THREAD

**Issue by Siddiqa** [mapbox/mapbox-navigation-android#1287]
Incorrect behavior when set allowRerouteFrom to false.

Mapbox Navigation SDK version: 0.18.0

### Steps to trigger behavior

 1.Setup navigation view and start navigation from source to destination.
 2.Navigate on Wrong route.
 

### Expected behavior
If set allowRerouteFrom to return false  will stop the re-route process and the user will continue without 
new route in the direction they are traveling.

### Actual behavior
The navigation head arrow constantly jumping its position.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12933877/45469845-ddb5af00-b748-11e8-8633-0295e1a854a7.gif)

**Comment by danesfeder** [comment]
Hey @Siddiqa 👋 taking a look at your screenshot, this looks to be working as designed.  If you don't provide `NavigationView` a new `DirectionsRoute` after you have disallowed an off-route event, we will continue to try to snap to the old route (which you are no longer driving along).  

To achieve your expected behavior, you'd also need to disable snapping via `MapboxNavigationOptions`.  The point of the listener is to "intercept" off-route events and provide a route that's different from the one we fetch internally > like with map-matching for example https://www.mapbox.com/android-docs/navigation/overview/map-matching/#map-matching-with-navigationview

Hope this helps!  Thanks for checking out the SDK 🚀
