### ISSUE TITLE
NavigationViewOptions simulation stops at first waypoint 

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1311]
**Android API: 26**
**Mapbox Navigation SDK version:0.19.0**

### Steps to trigger behavior

 1. Get a route with multiple waypoints
 2. Use NavigationViewOptions with shouldSimulateRoute = true

### Expected behavior
Resume simulation after reaching first waypoint like in 0.18.0

![ezgif com-video-to-gif-7](https://user-images.githubusercontent.com/23097192/46007787-34ad7380-c0bb-11e8-9186-030bfbac3608.gif)

### Actual behavior
The simulation stops at the first waypoint.

![ezgif com-video-to-gif-8](https://user-images.githubusercontent.com/23097192/46008053-e5b40e00-c0bb-11e8-91e0-89a1cc3c2ce8.gif)

**Comment by Guardiola31337** [comment]
Hey @P-Zenker 👋 thanks for reporting!

Yeah, you're completely right here. I've also noticed OP (while testing [`WaypointNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java) from the test app) and was going to cut a ticket but you beat me to it 😛

This is because the latest changes introduced in https://github.com/mapbox/mapbox-navigation-android/pull/1039 re `ReplayRouteLocationEngine`.

We will prioritize internally and discuss a solution for this and then report back here on this ticket. Thanks again!

**Comment by fabio2018spj** [comment]
Hi Mapbox,

I have the same problem.

Could you kindly give a status about the fix?

Thanks
