### ISSUE TITLE
navigationView only showing origin and destination point, not route itself

### ISSUE THREAD

**Issue by Gadda27** [mapbox/mapbox-navigation-android#1393]
**Android API:**
**Mapbox Navigation SDK version:**0.19.0

### Steps to trigger behavior

 1. I'm using the DirectionsRoute.fromJson() method create a DirectionsRoute which I'm passing to a NavigationMapRoute to navigate the route. My code for the JSON file is modified from a working Directions API response, which I can also load from a JSON file and which causes no issues with the navigation (route is shown etc.).
I try to create custom routes with responses from the [API Playground](https://www.mapbox.com/api-playground/#/directions/?_k=s63o40) on the basis of that working file (same format etc.). 
For this I change every single value to the new custom value.

### Expected behavior
A route that I can navigate through is added to the map.
![phpjfpdj8am](https://user-images.githubusercontent.com/38690543/46483419-e3f2f480-c7f7-11e8-929a-963502d0b5ef.jpg)

### Actual behavior
It only shows the origin point and the destination point of the route, but not the blue-colored route.
![php8jubamam](https://user-images.githubusercontent.com/38690543/46483424-e8b7a880-c7f7-11e8-9a58-913eef8410b7.jpg)

**Comment by Guardiola31337** [comment]
Hey @Gadda27 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the issue (minimal example) or any other specifics around your test setup? If there is any sample or pseudo code you can provide, that would be really helpful. Also could you share the modified JSON you're using in your tests? This will give us better insight into your implementation and what could be causing your problem.

In any case, I guess this is because of https://github.com/mapbox/mapbox-java/issues/894 - which is fixed now but not released yet. Could you please retest this adding `mapbox-sdk-services:4.1.0-SNAPSHOT` to your dependencies and report back if it solves your issue?

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.1.0-SNAPSHOT'
    // ...
}
```

Thanks again.

**Comment by Gadda27** [comment]
Thanks for your response. The issue was caused by the API Playground using a different polyline precision (5) than the one which was used in the response (6). This resulted in the coordinates being read as 3.0123 instead of 30.123.

**Comment by Guardiola31337** [comment]
Yeah, that makes sense! Thanks for the update @Gadda27 🙏
