### ISSUE TITLE
NavigationView cursor is not centered

### ISSUE THREAD

**Issue by hussi1** [mapbox/mapbox-navigation-android#1421]
I am using NavigationView inside a fragment, Navigation cursor inside NavigationView is aligned to top. Is there any way i can move that cursor to center of window or adjust its position programmatically.

NOTE : I have already tried **NavigationView#retrieveNavigationMapboxMap()#retrieveMap()#setPadding()**

I am recreating this issue because my previous issue was closed without resolution 

![cursor](https://user-images.githubusercontent.com/17702218/47012626-0cff7780-d15e-11e8-9a6e-b8be8c7b91ef.png)

**Android API: 27**
**Mapbox Navigation SDK version:com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0**

### Steps to trigger behavior

 1.Add NavigationView in fragment

### Expected behavior
Cursor should be in center

### Actual behavior
Cursor is aligned to top

**Comment by Guardiola31337** [comment]
As my colleague @danesfeder commented in https://github.com/mapbox/mapbox-navigation-android/issues/1419#issuecomment-429880696 you'd be able to adjust this with `NavigationView#retrieveNavigationMapboxMap()#retrieveMap()#setPadding()`. In your case, this is needed because you're including two maps as in [`DualNavigationMapActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/DualNavigationMapActivity.java) and should be tweak it manually.

I also want to take the opportunity to let you know that we recently released version [`0.21.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.21.0) so I encourage you to upgrade because there are a bunch of improvements and new features plus lots of bug fixes since `0.18.0`.

Hope this helps!

Also want to note that this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!
