### ISSUE TITLE
Use MapboxMap#queryRenderedFeatures for NavigationMapRoute click listener

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1634]
Per a great suggestion from @LukasPaczos in https://github.com/mapbox/mapbox-navigation-android/pull/1387#discussion_r240613582, we should use `MapboxMap#queryRenderedFeatures` to see if a user has clicked on a different alternative route.  

Currently, we use a series of turf measurements to see the distance of the point clicked to the closest route.  With longer routes, this is pretty inefficient way of determining the new primary route that was clicked.

**Comment by Guardiola31337** [comment]
@abhishek1508 is this going to be implemented in the `1.0` UI SDK?

**Comment by langsmith** [comment]
I was working on this before being asked to turn my attention to feedback refactoring. My work is at https://github.com/mapbox/mapbox-navigation-android/pull/new/ls-better-alternate-route-click-detection and route click detection now uses `queryRenderedFeatures` instead of Turf distance calculations. My refactoring work also enables a developer to provide custom padding values that are used to create a `RectF` box. The box is used in the Maps SDK's `queryRenderedFeatures()` method to query whether any portion of a route line runs through it. This querying only happens if a route line wasn't exactly tapped on. Checking whether the route line was exactly tapped on is done with `PointF` and `queryRenderedFeatures()`.

The SDK then makes appropriate adjustments based on whether any `Feature`s are returned in the queries. 

Building this query box is an implementation that @LukasPaczos and I thought made sense, rather than trying to build some sort of buffer corridor around a route line and then seeing whether a click is inside of the route line's buffer area.

Bring buffer support to Mapbox Turf for Java is being tracked at https://github.com/mapbox/mapbox-java/issues/987

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/4394910/95909115-ce075b00-0d52-11eb-9652-1238c661aa53.gif)


![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/4394910/95909395-466e1c00-0d53-11eb-89d6-cda051ddfac0.gif)
