### ISSUE TITLE
Use navigationViewOptions with NavigationLauncher?

### ISSUE THREAD

**Issue by hobochild** [mapbox/mapbox-navigation-android#1652]
Hi, I'm working on integrating the drop-in navigation UI for a react-native application, and I'm trying to add a milestoneListener while using the `NavigationLauncher`.

I'm using the NavigationLauncher like so:
```
NavigationViewOptions options = NavigationViewOptions.builder()
.directionsRoute(response.body().routes().get(0))
.shouldSimulateRoute(true)
.build();

 NavigationLauncher.startNavigation(activity, options);
```

The docs seem to suggest there is some way to use [NavigationViewOptions](https://www.mapbox.com/android-docs/api/navigation-sdk/navigation-ui/0.26.0/index.html with the  `NavgiationLauncher`?

Here is the passage from the docs:

> NavigationViewOptions provides a way to pass variables to a NavigationView. This class can be used with NavigationLauncher or when starting navigation with a custom implementation of NavigationView.

[found here](https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationviewoptions).

So for clarity is there a way to use the `NavigationViewOptions` with the `NavgiationLauncher`?

Thanks!

**Comment by Guardiola31337** [comment]
Hey @hobochild 👋 thanks for reaching out and report your question.

Because we opt to keep the `NavigationLauncherOptions` lightweight as far as what you can package in them. If you'd like more customization, you should roll with the `NavigationView` implementation 👀 https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationviewoptions

Also friendly reminder this is not a support forum, so in the future, for implementation questions, you can send a message to help@mapbox.com and reference this ticket. Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox). The Android team is watching these questions. Thanks for understanding!
