### ISSUE TITLE
Android resource linking failed with 0.26.0 .

### ISSUE THREAD

**Issue by wbearand** [mapbox/mapbox-navigation-android#1677]
Android API: 28
Mapbox Navigation SDK version: 0.26.0

### Steps to trigger behavior
Tried to upgrade my project (after a working on sth else for months) from 0.21.0 to 0.26.0 and took very long due to following error:

```
Android resource linking failed
C:\Users\............\.gradle\caches\transforms-1\files-1.1\jetified-mapbox-android-navigation-ui-0.26.0.aar\a13b4a3e05a7bf0ff75516399ad7d095\res\layout\navigation_view_layout.xml:10: AAPT: error: attribute mapbox_styleUrl (aka com.............................:mapbox_styleUrl) not found.
```

I assumed that this was a build error most likely due to my setup.
More confusing though, it works for me now with 0.27.0-SNAPSHOT . Can easily reproduce by switching back. 

In the snapshot I am experiencing a native crash though.

In the mentioned file there is app:mapbox_styleUrl="?attr/navigationViewMapStyle", should it be mapbox:mapbox_styleUrl ?

**Comment by Guardiola31337** [comment]
Hey @wbearand 👋 thanks for reaching out and report your issue.

It seems you run into a compatibility issue. Were you including `mapbox-android-sdk` `7.x` dependency in your `build.gradle` file in combination with version `0.26.0` of the Navigation SDK by any chance?

By the way, in https://github.com/mapbox/mapbox-navigation-android/pull/1615 we made the Navigation SDK compatible with Maps SDK 7.0 Events 4.0 so in order to fix the issues you're experiencing with `0.27.0-SNAPSHOT` I encourage you to check 👀 the [Maps 6.x to 7.x migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide). Note that [`mapbox_styleUrl` has been removed from the list of useable XML attributes](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide#xml-attributes) and it seems you're still using it which causes the issue you're running into.

Hope this helps a bit.

**Comment by danesfeder** [comment]
@wbearand have you been able to test with `0.27.0`?

**Comment by danesfeder** [comment]
@wbearand going to go ahead and close here.  If you still run into issues with `0.27.0` please feel free to open a new ticket.

**Comment by rthomps7** [comment]
I've been having similar issues adding `0.27.0` to my project. Might be something I'm doing, but since this seems so recent I'm wondering if something is up

**Comment by danesfeder** [comment]
@rthomps7 you're getting the error message from the OP with `0.27.0`?

**Comment by rthomps7** [comment]
I don't do much native Android development, so it very well may be something I am doing wrong.

With `0.27.0` and the snapshot, I am getting AAPT errors for undefined attributes on my app.

I switched to `0.21.0` and it's building now.

**Comment by wbearand** [comment]
@Guardiola31337, @danesfeder : sorry for my late response. thanks for the migration link, yes I suppose that was the issue. I am on 0.28.0 now and looks stable, thanks.

**Comment by Guardiola31337** [comment]
Hey @rthomps7 👋 could you try with `0.28.0`? That solved the issue for @wbearand as commented in https://github.com/mapbox/mapbox-navigation-android/issues/1677#issuecomment-459378128

**Comment by rthomps7** [comment]
@Guardiola31337  - that appears to have fixed it for me as well. :)

**Comment by Guardiola31337** [comment]
That's awesome! Thanks for the update @rthomps7
