### ISSUE TITLE
navigation-ui creates conflict with appcompactview

### ISSUE THREAD

**Issue by Yunus0or1** [mapbox/mapbox-navigation-android#1720]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. using      implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.28.0' in dependencies  with      implementation 'com.android.support:appcompat-v7:28.0.0' . 

### Expected behavior
Error free compilation. 
### Actual behavior
com.android.support:appcompat-v7:28.0.0'  throws error saying all the version must have same version of specification/

**Comment by Guardiola31337** [comment]
Hey @Yunus0or1 👋 thanks for reaching out and report your issue.

That's weird because `'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.28.0'` is already including `'com.android.support:appcompat-v7:28.0.0'` 👀 https://github.com/mapbox/mapbox-navigation-android/blob/eb619217a61038e3d4bb75fc9fafb6a099e4734d/gradle/dependencies.gradle#L20 https://github.com/mapbox/mapbox-navigation-android/blob/eb619217a61038e3d4bb75fc9fafb6a099e4734d/gradle/dependencies.gradle#L65

Could you add some more information for reproducing the error or any other specifics around your setup? Could you share your `build.gradle` files / config? This will give us better insight into what could be causing your problem.

**Comment by Yunus0or1** [comment]
Hi , I was totally occupied yesterday. That is why could not send you back anything. Here is the problem. 

![dependencies problem](https://user-images.githubusercontent.com/11329052/52253906-d0d26b80-2934-11e9-98f6-f183d4378fb2.PNG)

Here is the full app gradle :

https://dpaste.de/dOgx

And here is Project Gradle :

https://dpaste.de/rfTh

Here is manifest.xml:

https://dpaste.de/JqpE

Problem occurs when 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.28.0' is used with 
implementation 'com.android.support:appcompat-v7:28.0.0' .

**Comment by Guardiola31337** [comment]
Hey @Yunus0or1 👋 Looking carefully at your `build.gradle` file I noticed that you're including `implementation 'com.android.support:appcompat-v7:28.0.0'` twice 👀 

```groovy
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
```

That might be it.

Also friendly reminder this is not a support forum, so in the future, for implementation questions, you can send a message to help@mapbox.com and reference this ticket. Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox). The Android team is watching these questions. Thanks for understanding!
