### ISSUE TITLE
Enable developers to set/adjust the volume of spoken instructions

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#1749]
It should be possible for developers to easily set the volume of spoken instructions during turn-by-turn navigation. Unfortunately this is more complicated than it seems as the SDK adaptively switches between a media player and the built-in TTS system depending on network and other conditions.

In order to shield developers from this complexity, we should add a `setVolume()` method (and perhaps a getter as well?) to the `SpeechPlayer` interface, and handle the complexity of interacting with the different concrete player types under the hood.

cc @malwoodsantoro

**Comment by billyking991** [comment]
I don't know if this is even possible, but this is literally the biggest request my users have (on iOS too, let me know if you need me to open an issue).  It would be awesome if it was possible to even raise the volume of the voice relative to the media player volume.  I don't really have an issue with it, but I get lots of App and Play store reviews requesting that the voice is louder.

**Comment by billyking991** [comment]
I think I may know what is going on.  I've been testing with 4 of the different English voices and comparing what I'm hearing with the Mapbox.  I think it may not be that the voice isn't loud enough...it may be that the voice is equalized so that it's too mellow.  Is there a way to adjust the the way the voice is equalized so that it's much more treble and stands out against all of the other noises in a car?  

The reason I've come to this conclusion is because when there is a terrible connection, the Polly voice its replaced with the Text-To-Speech voice I've set on the device.  That voice has much more treble in it and is much easier to hear in the car.  I feel that the Polly voices are two mellow and focused toward the midrange of the sound spectrum.  Does this make sense?  

Regardless, I keep getting asked by users to make the voice louder, if possible.  Any changes that could be made would be really nice.

**Comment by billyking991** [comment]
That would be fantastic.  Please let me know if you need anything from me.

**Comment by clj0020** [comment]
@danesfeder has anything been done to address this yet? We are getting similar complaints about not being able to hear while Google Maps is fine.

**Comment by Guardiola31337** [comment]
@asinghal22 is this something we want to support in `1.0`?

cc @abhishek1508 @JunDai

**Comment by JunDai** [comment]
> It should be possible for developers to easily set the volume of spoken instructions during turn-by-turn navigation.

@akitchen / @billyking991 - while I understand it's a problem if the user can't hear the voice instruction, but there is potential complain if Mapbox offers the `setVolume` interface. Different users have different definition/expectation about voice instruction volume.

Consider this use case:
1. your app users usually set their device to a lower volume because they like quiet
2. your app sets a relative higher voice instruction volume
3. your app users will experience a volume jump when start navigation in your app
I think you will get some complain in this case too.

But I think Mapbox should consider to add that API `setVolume`, how to integrate it into your apps is the developer's choice.
