### ISSUE TITLE
NavigationRoute Language: Country ignored

### ISSUE THREAD

**Issue by arildojr** [mapbox/mapbox-navigation-android#1758]
Hello,

I'm trying to change language instructions for the `NavigationRoute` to Portuguese Brazil (pt-BR) but Mapbox always gets Portuguese Portugal (pt-PT). It seems the country code is being ignored.
Please check my code below to change the language:
`NavigationRoute.builder(this)
.accessToken(Mapbox.getAccessToken()!!).origin(origin).destination(destination)
.language(Locale("pt", "BR")).build()`

According to this docs pt-BR should be supported: [https://docs.mapbox.com/api/navigation/#instructions-languages](url)

**Android API:** 26 8.00
**Mapbox Navigation SDK version:** 0.30.0

### Expected behavior
Should listen to Portuguese Brazil in Voice Instructions

### Actual behavior
Listening to Portuguese Portugal in Voice Instructions

**Comment by danesfeder** [comment]
Hey @arildojr 👋 I believe your issue here is the construction of `Locale`.  By updating to `new Locale("pt-BR")` you should see the correct `pt-br` in the request URL:

![screen shot 2019-02-19 at 8 39 12 am](https://user-images.githubusercontent.com/8434572/53019382-97b0f580-3422-11e9-91de-5928bb3cedc8.png)

As you can see, `new Locale("pt", "BR")` results in `pt_BR`.  Let us know if this works okay for you, going to go ahead and close this as resolved.

**Comment by arildojr** [comment]
@danesfeder correct, thanks!

**Comment by Guardiola31337** [comment]
Hey @arildojr 👋 The API supports both `pt_BR` and `pt-br` so I'm wondering why you thought that we're giving Portuguese Portugal voice instructions instead of Portuguese Brazil 🤔 Could you share a response including some instructions that you noticed that were incorrectly translated? My guess is that this is a "translation" issue.

Our voice instructions are sourced from https://github.com/Project-OSRM/osrm-text-instructions, so if you can open an issue there, that would be great (this is non-actionable on our side).

Specifically, please check out https://github.com/Project-OSRM/osrm-text-instructions/blob/master/CONTRIBUTING.md - if you're able to provide the updated translations, this would speed up the process of getting the fix deployed.

Thanks!
