### ISSUE TITLE
How do i use silent Waypoints with mapmatching

### ISSUE THREAD

**Issue by vincent-caron** [mapbox/mapbox-navigation-android#1851]
Hello,

I am using coordinates given by a service to create a directionroute with mapmatching points.

I've read that it's now possible to have silent waypoint, but i can't find any documentation or example on the way to do this.

Can someone explain me how to do this or give me an example ?

Thanks in advance

Regards

**Comment by Guardiola31337** [comment]
Hey @vincent-caron 👋 thanks for reaching out and report your question.

Support for via / silent waypoints was added in https://github.com/mapbox/mapbox-java/pull/959 and https://github.com/mapbox/mapbox-navigation-android/pull/1733 and it's available since [`v0.29.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.29.0). For further details, you can see the Javadoc 👀 https://docs.mapbox.com/android/api/navigation-sdk/navigation/0.34.0/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.Builder.html#addWaypointIndices-java.lang.Integer...-

For implementation questions, you can send a message to help@mapbox.com and reference this ticket.  Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox).  The Android team is watching these questions. Thanks for understanding!
