### ISSUE TITLE
LocationEngine::requestLocationUpdates not work after navigation started.

### ISSUE THREAD

**Issue by zeallat** [mapbox/mapbox-navigation-android#1871]
**Android API : 28**
**Mapbox Navigation SDK version : 0.34.0**

### Steps to trigger behavior

 1. Initialize ```LocationEngine```. (In my case, ```ReplayRouteLocationEngine```. But I don't think it makes difference.)

 2. Initialize ```LocationEngineCallback<LocationEngineResult>```.

 3. Call method ```LocationEngine::requestLocationUpdates(request,  callback,  looper)``` from ```LocationEngine``` of (1) with ```LocationEngineCallback``` of (2).

 4. Set ```LocationEngine``` of (1) to ```MapboxNavigation```

 5. Call method ```MapboxNavigation::startNavigation(directionsRoute)```

Or run below order cause same result.
1 -> 2 -> 4 -> 5 -> 3

### Expected behavior
```LocationEngineCallback::onSuccess(result)``` is called when ```LocationEngine``` has new location update.

### Actual behavior
When navigation session is active, my custom ```LocationEngineCallback``` never called. 

---
I think this beacause of this [PR](https://github.com/mapbox/mapbox-navigation-android/pull/1803). So I must get location update from ```RawLocationListener``` from ```MapboxNavigation``` when navigation session is in active. 
Above expected behavior was worked at Mapbox Navigation SDK version 0.22.0. But I can't find any direction of this change in ```Migration Guide```. So I want to know if this is a bug or one of breaking changes or just I make a mistake.

**Comment by Guardiola31337** [comment]
Hey @zeallat 👋 thanks for reaching out and report your question!

As you pointed out in order to listen for the raw locations coming from the location engine you should implement a `RawLocationListener` and add it via `MapboxNavigation#addRawLocationListener` 👀 https://docs.mapbox.com/android/api/navigation-sdk/navigation/0.34.0/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.html#addRawLocationListener-com.mapbox.services.android.navigation.v5.location.RawLocationListener- After that, you'll be notified every time a new `Location` is pushed by the `LocationEngine`. This is not a breaking change, just a new API that we exposed to developers in https://github.com/mapbox/mapbox-navigation-android/pull/1803 Hope this clarifies how to use it.

Also friendly reminder that this is not a support forum, so in the future, for implementation questions, you can send a message to help@mapbox.com and reference this ticket.  Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox).  The Android team is watching these questions. Thanks for understanding!

**Comment by zeallat** [comment]
@Guardiola31337 Many thanks for reply my issue. You means, ```callback``` from ```LocationEngine#requestLocationUpdates(request, callback, looper)``` is not called after do ```MapboxNavigation#startNavigation()``` is normal case?

**Comment by Guardiola31337** [comment]
Hey @zeallat with the new location APIs 👀 https://github.com/mapbox/mapbox-navigation-android/pull/1615 the `callback` is consumed internally, so if you're still interested in the raw location updates coming from the location engine you should implement `RawLocationListener` (as mentioned above). Does that make sense?

**Comment by zeallat** [comment]
@Guardiola31337 Thanks again for nicely answer... I was understood why this happens, just wonder about why this is not a breaking change..(because of it was available at version 0.22.0).
I just confused that if it is not a bug, then it might be need to mention in migration guide or not?(for other people?)
But 0.22.0 is far long ago version... so might it be not so important.
Sorry for bother... I love your api! Thanks!

**Comment by Guardiola31337** [comment]
@zeallat 
As part of https://github.com/mapbox/mapbox-navigation-android/pull/1615 there were some breaking changes and those were described in both the documentation https://docs.mapbox.com/android/core/overview/#getting-location-updates and in [`0.27.0` Migration Guide](https://github.com/mapbox/mapbox-navigation-android/wiki/0.27.0-Migration-Guide). Hope this helps.

Thanks again for checking out the SDK!
