### ISSUE TITLE
ERROR: Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:6.2.0

### ISSUE THREAD

**Issue by EnhaoSun** [mapbox/mapbox-navigation-android#1950]
I added the maven { url 'https://mapbox.bintray.com/mapbox' } to root project gradle.
 and implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.38.0' to module gradle. The error still occurs. Can anyone help me?

![Screen Shot 2019-05-29 at 2 43 19 PM](https://user-images.githubusercontent.com/49918013/58561893-1b4b6100-8220-11e9-8afd-358c5751fd70.png)
![Screen Shot 2019-05-29 at 2 43 10 PM](https://user-images.githubusercontent.com/49918013/58561928-2c946d80-8220-11e9-8b83-f21d639fe94a.png)

**Comment by Guardiola31337** [comment]
Hey @EnhaoSun 👋 thanks for reaching out and report your issue.

It seems you have included it under the `buildscript` block. In order to get it working you should include it under the `allprojects` one. For reference you can check root's `build.gradle` file of `mapbox-navigation-android` https://github.com/mapbox/mapbox-navigation-android/blob/2f58fdb2a1983e5048a85a76bc3c9b280b099742/build.gradle#L35

Also friendly reminder that this is not a support forum, so in the future, for implementation questions, you can send a message to help@mapbox.com and reference this ticket.  Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox).  The Android team is watching these questions. Thanks for understanding!
