### ISSUE TITLE
Offline Navigation Not Responsive

### ISSUE THREAD

**Issue by Sanunez** [mapbox/mapbox-navigation-android#1962]
**Android API:** 16 -28
**Mapbox Navigation SDK version:** mapbox-android-navigation-ui:0.38.0

### Steps to trigger behavior
 1. Create offline Tiles
 2. Create offline route
 3. load up NavigationLauncher while offline

### Expected behavior
Offline turn by turn navigations just as if it was online

### Actual behavior
Navigation Launcher shows up blank and cannot be interacted with. It only becomes responsive when online is switched back on.

![OfflineNavBug](https://user-images.githubusercontent.com/11667825/58970404-ff474280-877e-11e9-8a52-002521371531.gif)

### Code Being Run
``` Java
private void showNavigationRoute(Symbol originSymbol){
		if(navigationMapRoute != null){
			navigationMapRoute.updateRouteArrowVisibilityTo(false);
			navigationMapRoute.updateRouteVisibilityTo(false);
		}else{
			navigationMapRoute = new NavigationMapRoute(null, mapView, mapboxMap);
		}
		navigationMapRoute.addRoute(currentRoute);
		CameraPosition position = new CameraPosition.Builder()
						.target(originSymbol.getLatLng())
						.zoom(15)
						.tilt(20)
						.build();
		mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(position), 1000);
		IconicsButton navStartBtn = findViewById(R.id.startNavigationButton);
		navStartBtn.setVisibility(View.VISIBLE);
		navStartBtn.setOnClickListener(v -> {
			navStartBtn.setEnabled(false);
			NavigationLauncherOptions navoptions = NavigationLauncherOptions.builder()
							.offlineRoutingTilesPath(MainActivity.this.getCacheDir().getPath())
							.offlineRoutingTilesVersion(offlineRouteVersion)
							.directionsRoute(currentRoute)
							.shouldSimulateRoute(simulateRoute)
							.build();
			NavigationLauncher.startNavigation(MainActivity.this, navoptions);
		});
	}
```

Could be a similar issue to: https://github.com/mapbox/mapbox-plugins-android/issues/970

**Comment by Sanunez** [comment]
One additional piece of info i can't find anywhere is: Where do you attach the onReroute listener when using NavigationLauncher to start Navigation?

**Comment by Guardiola31337** [comment]
Hey @Sanunez 👋 thanks for reaching out and report your issue.

Based on the video you shared you're testing on the _Faroe Islands_ as indicated in the docs https://docs.mapbox.com/android/navigation/overview/offline-routing/#test-offline-routing

Could you add some more information around your test setup? Especially, could you share some code around how you're downloading the offline routing tiles and how you're retrieving the list of available routing tile versions? We'd like to 👀 how you're utilizing the offline APIs.

Have you seen 👇? https://github.com/mapbox/mapbox-navigation-android/blob/5b9a8e803955cc7055e9070248f91179824a91bc/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java#L349-L356

Are you able to reproduce the issue using the [test app](https://github.com/mapbox/mapbox-navigation-android/tree/master/app) / [`NavigationLauncherActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java)? That'd be really helpful to troubleshoot the issue.

In any case, what are you trying to implement? Could you describe your use case in detail? In order to give a fully offline navigation experience you should know that there are two "offline" pieces involved: routing and map tiles. It seems that the map isn't loaded at all, reason why you cannot do anything (in fact, until the map is loaded, most of the components are not initialized). Could you check if there's any log printed out? Could you try `Online` > `Start Navigation` > `Offline` and 👀 if the navigation session keeps going?

If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem. As mentioned, a complete example reproducing the issue would be 💯

**Comment by Sanunez** [comment]
For some reason I did not get this notification, I will implement on the test app and get back to you! Thanks!

**Comment by Guardiola31337** [comment]
Awesome @Sanunez Thanks for the update!

**Comment by Guardiola31337** [comment]
Closing as stale.

@Sanunez thanks for checking out the SDK. Feel free to cut a new ticket if you can still reproduce OP with the latest version.
