### ISSUE TITLE
Android resource linking failed with mapbox-android-sdk:8.1.0

### ISSUE THREAD

**Issue by swadallail** [mapbox/mapbox-navigation-android#2001]
Tried to upgrade my project (after a working on sth else for months) from mapbox-android-sdk 6.6.2 to 8.1.0 and took very long due to following error:|
`Android resource linking failed
Output:  warn: removing resource com.example.android.mapbox:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
C:\Users\AmedBasheiR\AndroidStudioProjects\MapBox\app\src\main\res\layout\activity_location_picker.xml:10: error: attribute mapbox_styleUrl (aka com.example.android.mapbox:mapbox_styleUrl) not found.`
**Android API:*28*
**Mapbox Navigation SDK version:*0.7.1*

**Comment by Guardiola31337** [comment]
Hey 👋 @swadallail Thanks for reaching out and report your question.

As you can imagine there have been a bunch of improvements and new features plus lots of bug fixes since `0.7.1` (current version is [`0.41.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.41.0) 😬) so please consult the [migration guides](https://github.com/mapbox/mapbox-navigation-android/wiki#recent-migration-guides) for the necessary updates required and reach out to us if you have any questions or if you run into any issues.

Heads up: If you're using the Navigation UI SDK, you don't have to declare the Mapbox Maps SDK, it's included implicitly 👀 https://github.com/mapbox/mapbox-navigation-android/blob/156e6a7aafe3bb603ac7c0ba28a322e0925b7a8d/libandroid-navigation-ui/build.gradle#L49 This is on purpose to avoid any kind of dependencies conflicts and it's described in the [documentation](https://docs.mapbox.com/android/navigation/overview/#add-the-dependency-1).

Also friendly reminder that this is not a support forum, so in the future, for implementation questions, you can send a message to help@mapbox.com and reference this ticket.  Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox).  The Android team is watching these questions. Thanks for understanding!
