### ISSUE TITLE
WaypointNavigationActivity doesn't work - testapp

### ISSUE THREAD

**Issue by Florent-Sebag** [mapbox/mapbox-navigation-android#2022]
Hi,

I'm trying to implement the WaypointNavigationActivity of the testapp in my app.
I did a copy/paste; everything works until that the first waypoint is reached. After that, when the DropoffDialog is showed and the user "accept to continue to navigate", the toast message show directly that we have arrived at the next point, without moving, and then an other DropoffDialog shows up for the next point. So all the dialog are showed before reaching each one. I think this is because the map is not refreshed when we pass to the second waypoint; I tried with clearMarker(); but it doesn't work either.

**Comment by Guardiola31337** [comment]
Hey @Florent-Sebag 👋 thanks for reaching out and report your question.

Could you add some more information for reproducing the behavior you're describing or any other specifics around your setup? That would be really helpful because without having additional information, I'm unable to reproduce - I've just tested [`WaypointNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java) and it's working 👌 Are you tweaking anything? If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

Also friendly reminder that this is not a support forum, so in the future, you can send a message to help@mapbox.com and reference this ticket. Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox). The Android team is watching these questions. Thanks for understanding!
