### ISSUE TITLE
NullPointerException on NavigationMapboxMap.addProgressChangeListener

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#2029]
Hey Team,

We are getting random crash on mapbox sdk. I've attached the logs file. 

Android Api: 28
MApbox sdk: 0.33.0
[com.kater.krs.driver_issue_crash_5D5B14DA015500012650FECBBEDBC9CB_DNE_0_v2.txt](https://github.com/mapbox/mapbox-navigation-android/files/3517929/com.kater.krs.driver_issue_crash_5D5B14DA015500012650FECBBEDBC9CB_DNE_0_v2.txt)

Thanks,
Navdeep

**Comment by Guardiola31337** [comment]
Hey @navdeepg 👋 thanks for reaching out and report your issue.

Current release version is [`0.41.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.41.0). To confirm that the issue is still present in the latest version, would you mind upgrading to `0.41.0` version and retest? As you can imagine there have been a bunch of improvements and new features plus lots of bug fixes since `0.33.0`. Including some changes around the attached logs 👀 `v0.33.0` https://github.com/mapbox/mapbox-navigation-android/blob/17022b656bbdc9b14478fcd455785ed91d2b9fce/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L691-L692 `v0.41.0` https://github.com/mapbox/mapbox-navigation-android/blob/86605e637a73c124f20958f97342eaa81f4dfa47/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L677-L678

Please consult the [migration guides](https://github.com/mapbox/mapbox-navigation-android/wiki#recent-migration-guides) for the necessary updates required and reach out to us if you have any questions or if you run into any issues. Thanks in advance!

**Comment by andrlee** [comment]
@navdeepg any updates? were you able to repro this issue?

**Comment by Guardiola31337** [comment]
@navdeepg I'm going to go ahead and close this as stale - please feel free to cut a new ticket if you're able to reproduce.
