### ISSUE TITLE
MapBox Localization Issue - Australia

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-navigation-android#2053]
I have implemented turn by turn navigation and set voice instructions to Australian English. Had a chance to drive through a roundabout and the voice instructions pronounced it as a traffic circle. In Australia traffic circles and roundabouts are same thing, users will not know what a traffic circle is, can you please update voice instructions and replace traffic circle with roundabouts. Let me know if I can do anything on my end.

**Comment by Guardiola31337** [comment]
cc @1ec5 @danpat

**Comment by danpat** [comment]
@Guardiola31337 I think this issue is stale.  We did some language analysis back in Sept 2019 and concluded that `roundabout` was the more common term, in English-speaking places where roundabouts exist.  There are a *few* places in the US that call them `traffic circles`, but those places don't actually have many, so the total number of erroneous announcements is lower when we use `roundabout` by default.

We still don't have an `en_AU` specific l10n though, which is a bloody shame.
