### ISSUE TITLE
MapBox Localization Issue - YORUBA

### ISSUE THREAD

**Issue by toblinkz** [mapbox/mapbox-navigation-android#2071]
I have tried implementing the yoruba as  a navigation  instruction but it's not still working. I was assured it was added in the new release.

**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by Guardiola31337** [comment]
Hey @toblinkz 👋 thanks for reaching out.

Translations were added in https://github.com/mapbox/mapbox-navigation-android/pull/2003 and available since `v0.42.0` - current SDK version is [`v0.42.6`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.42.6).

Instructions on how to create your custom speech engine and how to plug it to the SDK were detailed here https://github.com/mapbox/mapbox-navigation-android/issues/2000#issuecomment-515603897

Closing as answered.
