### ISSUE TITLE
[Feature Request] WayPoint Priority

### ISSUE THREAD

**Issue by BinaryPigStudio** [mapbox/mapbox-navigation-android#2233]
Hi,

I would like to ask if it would be possible to add a way of manually prioritising a waypoint over others while generating an optimised route.
Our APP is for a delivery company and some deliveries are more urgent than others, the user is unable to follow the suggested optimised route because it does not take into consideration that urgency.

For example: 
- Route with 10 waypoints.
- Waypoint 5 and 6 have higher priorities.
- Route would be generated with source '_First - 5 - 6_' (5-6 are interchangeable if the priority is the same) , remaining waypoints would be random if destination is set to ANY.

The '_Priority_' parameter is set with '_0-10_' with '_0_' being the lowest priority and '_10_' the highest priority.

Best Regards,
Tiago from Binary Pig

**Comment by Guardiola31337** [comment]
Is this something currently supported by the Directions API @mapbox/navigation-api @danpaz?

**Comment by danpaz** [comment]
This feature is not supported in the API as far as I know. cc @danpat in case you know more.

**Comment by danpat** [comment]
This is a combinatoric optimization problem, not a strictly shortest-path problem.

If you've only got routes of 10 waypoints, then you can probably brute force a result:

  1. Request a Matrix result so you have the travel times between all pairs of waypoints.
  2. Generate all possible sequences (there will be about 10! = 3,628,800 combinations)
  3. Sort them based on your objective - e.g. sort routes with 5,6 earlier first, then sort by total trip length.
  4. Pick the item from the top of the sorted list.
  5. Pass that sequence to the Directions API to get turn-by-turn instructions following that order.

Be aware that the growth of this problem is factorial - you'll run out of reasonable compute power at probably 12 or 13 stops if you use a brute force solution like the one above.

Mapbox's Optimization API can solve *some* problems like this, but it does not support your particular requirement for "high priority" waypoints.

**Comment by mandeepsandhu** [comment]
Can the computation be broken down into multiple steps (instead of computing it all together in one request)? Taking the example above, compute a matrix with only the highest priority waypoints (5 & 6), do another matrix search for the remaining waypoints (assuming they all have the same priority))& then find shortest path from 6 to the second matrix's first location? I'm spitballing here, so feel free to CMIIW (maybe this approach takes longer to compute than doing it all once?).

**Comment by danpat** [comment]
@mandeepsandhu I mean, yeah, there are lots of heuristics you can use, depending on your objective - replace steps (2) and (3) in my list above with whatever gets you to your preferred solution.

There are likely delivery scenarios where it actually makes economic sense to *not* deliver the high priority packages - e.g. if a single priority package is on the far side of a city, and all the other deliveries are on the side closest to the depot, it might make sense to just not deliver the priority package and deliver lots of non-priority packages instead.  Modelling these kinds of problems properly needs to consider lots of aspects of how the business operates.

**Comment by mandeepsandhu** [comment]
> @mandeepsandhu I mean, yeah, there are lots of heuristics you can use, depending on your objective - replace steps (2) and (3) in my list above with whatever gets you to your preferred solution.
> 
> There are likely delivery scenarios where it actually makes economic sense to _not_ deliver the high priority packages - e.g. if a single priority package is on the far side of a city, and all the other deliveries are on the side closest to the depot, it might make sense to just not deliver the priority package and deliver lots of non-priority packages instead. Modelling these kinds of problems properly needs to consider lots of aspects of how the business operates.

I agree. My assumptions were quite simplified (I assumed the higher prio destinations _have_ to be serviced no matter what). Ideally you'd want to give alternates here (just like how we provide alternate routes if requested) and let the user decide if the trade-off of priority vs non-priority is worth it or not (but that would seem to be a more expensive solution for the customer and more time-consuming).
