### ISSUE TITLE
Notify about a canceled request and expose route setter

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2406]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/2400/files#diff-2c6725b936f8c3d41f2d40c2ba2c2487R49. We should be able to expose a `Router.Callback#canceled` method which will empower us to manage a state in a way that would make exposing a `DirectionsSession#setRoute` possible.

Outdated WIP branch here https://github.com/mapbox/mapbox-navigation-android/tree/lp-cancel-route-request.

/cc @mapbox/navigation-android

**Comment by abhishek1508** [comment]
I see that in the `examples` app we are adding `libnavigation-ui` dependency to the build.gradle. This is because all the activities in this `examples` app is using `NavigationMapRoute` from the `ui` module. I have a couple of questions:
* Does that mean that a customer who will be using the `v1.0` will have to add `libnavigation-ui` as a dependency as well? 
* Also, `libnavigation-ui` internally depends on `libnavigation-core`. So then a customer will end up adding `v1.0`, `legacy-ui` and `legacy-core` in their app. When are we planning to resolve this?
* `NavigationMapRoute.java` uses `MapboxNavigation.java` from the legacy core. We need to modify this class to make sure it doesn't do so. Thoughts/Comments?

In general, I am trying to understand if a customer can use `v1.0` to request routes from a Router and then draw them on the map without using `ui` module. I guess that's what we are doing at the moment.
cc @LukasPaczos @Guardiola31337 @olegzil

**Comment by LukasPaczos** [comment]
@abhishek1508 users always can request the routes and draw them using Maps SDK APIs only.

We opted to currently use the legacy `NavigationMapRoute` for the sake of convenience. Of course, the legacy UI lib isn't fully compatible with core `1.0` yet, but this is what @RingerJK is working on in https://github.com/mapbox/mapbox-navigation-android/pull/2437 and follow up PRs.
