### ISSUE TITLE
Navigation notification shows free-drive mode when there is an ongoing navigation

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#2604]
### Steps to trigger behavior

 1. Run the example app in the repo
 2. Launch `SimpleMapboxNavigationKt` and start a navigation
 3. Check navigation notification

### Expected behavior
Notification shows correct navigation mode
### Actual behavior
Notification shows free-drive mode
![Screenshot_20200317-103134](https://user-images.githubusercontent.com/3918950/76881524-7fcebf80-6836-11ea-85f6-a42423337c44.png)

**Comment by Guardiola31337** [comment]
Adding more context here. This is a regression from https://github.com/mapbox/mapbox-navigation-android/pull/2450 I noticed that when running the [`SimpleMapboxNavigationKt`](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt) from the `examples` test app. This was in _Active Guidance_ and displayed that arrow icon and `Free Drive Session` text, that should never happen.

cc @Lebedinsky

**Comment by Guardiola31337** [comment]
Re-opening here. This is still reproducible sometimes 👀 

![Screenshot_20210310-095210](https://user-images.githubusercontent.com/1668582/120320106-cbd91900-c2af-11eb-9a45-1e4d7d77ad1a.png)

Apparently, very first instruction is not always populated.

cc @abhishek1508 @cafesilencio

**Comment by Guardiola31337** [comment]
Noting that I was able to reproduce again 👀 

| Wrong icon + no distance  | Wrong icon  | Correct icon after passing step  |
|---|---|---|
| ![Screenshot_20210812-150121](https://user-images.githubusercontent.com/1668582/129271470-77b1edd8-85c7-4c42-bdce-1299afc75875.png)  | ![Screenshot_20210812-150151](https://user-images.githubusercontent.com/1668582/129271592-da0842a7-a1a6-4d8d-996e-67e7b7092f8f.png)  | ![Screenshot_20210812-150521](https://user-images.githubusercontent.com/1668582/129271616-7faef927-9b74-432f-a6e6-92d87e77b90f.png)  |

cc @Zayankovsky @abhishek1508

**Comment by Guardiola31337** [comment]
I kinda confirmed that the issue is a race condition from the notification not displaying the information the very first time somehow (we should keep investigating how can this happen from an Android point of view) and how we're checking for the state - preventing from doing so until the next step (apparently at that point the notification is fully available already). @abhishek1508 @Zayankovsky any ideas?

Also, I want to note that when updating always (rebased https://github.com/mapbox/mapbox-navigation-android/pull/4732 into `main`) I'm seeing the app laggy and unresponsive 😥 

So I'd say that we should make that state logic more robust somehow but we cannot update always as it is taxing UI performance.

**Comment by Guardiola31337** [comment]
Unfortunately I was able to reproduce after https://github.com/mapbox/mapbox-navigation-android/pull/4792 😥 

![Screenshot_20210910-135058](https://user-images.githubusercontent.com/1668582/132900590-9319fd05-fc50-40ab-b699-011d08fa2e3f.png)

Re-opening here.

cc @Zayankovsky
