### ISSUE TITLE
Improve turn completion announcements

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#264]
Right now we always issues a completion voice announcement after a turn (e.g. “Continue on K St NW for 1.2 miles”) regardless of the next step's duration/length.

For 0.6.2 we should check the duration of the step and announce the approach ("In 800 feet, turn right onto California St") or turn announcements ("Turn right onto California St") instead.

Pseudocode:
```
If upcomingStepDuration < 15s: return nextStepTurnAnnouncement
If upcomingStepDuration < 70s: return nextStepApproachAnnouncement
Else: return completionAnnouncement
```

cc @cammace @danesfeder

**Comment by hdaymon** [comment]
This is already done on the server. Instead of writing throwaway code here, let's spend the effort to get the server side instructions into production? We should have it up on staging by the end of today and hopefully directions production tomorrow (9/28). If we can do builds against staging for both iOS and Android we can do some test driving on Friday. @danesfeder and @cammace can you join us Friday at 10am in DC? @bsudekum and @1ec5, do you want to do some test driving over the weekend? 


cc: @willwhite @bsudekum @cammace @danesfeder @1ec5

**Comment by cammace** [comment]
punting this to 0.7 milestone, not understanding the pseudocode and which milestones need to contain the fix.

**Comment by ericrwolfe** [comment]
@cammace this would be here, in the NewStep milestone: 
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DefaultMilestones.java#L110-L115

**Comment by cammace** [comment]
With 0.7.0 I've removed the default milestones in favor of the Voice Instructions in the DirectionsRoute. Closing this.
