### ISSUE TITLE
onNavigationSessionStateChanged() toggles ACTIVE_GUIDANCE/FREE_DRIVE in response to onRoutesChanged returning true/false

### ISSUE THREAD

**Issue by olegzil** [mapbox/mapbox-navigation-android#2651]
The NavigationSessionStateObserver interface notifies callers via onNavigationSessionStateChanged() which delivers one of three enums: ACTIVE_GUIDANCE, FREE_DRIVE or IDLE. The RoutesObserver interface notifies the caller via onRoutesChanged(). These seem to be linked. When onRoutesChanged returns an empty route list due to an off-route event onNavigationSessionStateChanged() switches from its previous state to FREE_DRIVE. Once onRoutesChanged() returns a valid, non-empty route list onNavigationSessionStateChanged() switches from its previous state to ACIVE_GUIDANCE. These events should not be linked. The ACTIVE_GUIDANCE and FREE_DRIVE states must well defined and not be affected by off-route events

**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior
 1. Implement onNavigationSessionStateChanged() and onRoutesChanged(). Add logging to both methods
 1. Start the Example App, select a route and start navigation
 2. Start a mock navigation app and start navigation. This is a guided navigation session
 3. Log the device output and notice that the loggs toggle between ACTIVE_GUIDANCE and FREE_DRIVE when you go off-route. 

### Expected behavior
The FREE_DRIVE state should remain unchanged until you either arrive, cancel the session or programmatically clear the route.

### Actual behavior
as described in "Steps to trigger behavior"

**Comment by Guardiola31337** [comment]
Thanks for reporting @olegzil 🙇 

I also noticed that when testing https://github.com/mapbox/mapbox-navigation-android/pull/2650

We shouldn't send `NavigationSession.State` changes when on re-routing. It's because of 👇 

We're clearing the list before doing a request https://github.com/mapbox/mapbox-navigation-android/blob/25a4642ac8743c219d387b7da56e42c6a6789fa8/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt#L45 which fires off https://github.com/mapbox/mapbox-navigation-android/blob/25a4642ac8743c219d387b7da56e42c6a6789fa8/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt#L28 which fires off https://github.com/mapbox/mapbox-navigation-android/blob/25a4642ac8743c219d387b7da56e42c6a6789fa8/libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt#L74 which ends up updating `hasRoutes` and calling `updateState` https://github.com/mapbox/mapbox-navigation-android/blob/25a4642ac8743c219d387b7da56e42c6a6789fa8/libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt#L40 which finally changes the `NavigationSession.State` from _Active Guidance_ to _Free Drive_ momentarily during requesting a new route as part of a re-route event https://github.com/mapbox/mapbox-navigation-android/blob/25a4642ac8743c219d387b7da56e42c6a6789fa8/libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt#L52-L58 because the first condition is `false` but the second is `true` because the session is `STARTED` i.e. we're reporting `FREE_DRIVE` when in reality it's still `ACTIVE_GUIDANCE` but handling an off-route.

We should think about how to fix this.

cc @LukasPaczos @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
This was fixed in https://github.com/mapbox/mapbox-navigation-android/pull/2668

Closing.
