### ISSUE TITLE
NavigationViewActivity doesn't end the trip session when clicking on the back button

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2732]
When testing the `examples` test app noticed that `NavigationViewActivity` doesn't end the trip session after clicking on the back button 👇 Is that on purpose / by design? We should 👀 the rest of the examples and be consistent.

![navigation_view_activity_end_trip_session](https://user-images.githubusercontent.com/1668582/78829561-8fb06e00-79b4-11ea-884d-1c5ce6afd842.gif)

**Comment by JunDai** [comment]
@Guardiola31337 - I would assume it's by design so the navigation will continue run at background when user press back button. In this case, user will need to specifically click the "**X**" icon to stop the navigation.

@abhishek1508 - correct me if that's not the case.

**Comment by Guardiola31337** [comment]
@JunDai 
> I would assume it's by design so the navigation will continue run at background when user press back button. In this case, user will need to specifically click the "**X**" icon to stop the navigation.

That's fair but problem is that if you do that and then click on the notification, app doesn't bring back to the foreground 😓 i.e. you cannot do anything other than closing the session.

**Comment by JunDai** [comment]
> That's fair but problem is that if you do that and then click on the notification, app doesn't bring back to the foreground 😓 i.e. you cannot do anything other than closing the session.

🤔 hmmm, good point. I didn't pay attention to it.

**Comment by abhishek1508** [comment]
@JunDai I guess first we need to find out what happens in the following scenario:

User opens the app > Start the NavigationViewActivity instead of MainActivity > Make sure the trip session started > Now press the back button to go to home screen > Now click on the notification

Expected:
The user should see the puck navigating based on the route progress with proper banner data and other data that should be seen.

If this works then we are fine because in the current scenario there is an activity stack where the NavigationViewActivity is 3rd in the stack. Pressing the back button removes it from the stack thereby resulting in the system to create the activity again. Then in this case we would just call finish onBackPress so that TripSession.stop() is invoked.

But if we see the same behavior as mentioned in the issue with the above test then we need to fix it.

**Comment by JunDai** [comment]
> User opens the app > Start the NavigationViewActivity instead of MainActivity > Make sure the trip session started > Now press the back button to go to home screen > Now click on the notification

The activity just restart and the state wasn't kept.

Just checked the legacy code, I think we don't cleanup `NavigationService` when the NavigationViewModel destroys itself. see -> https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L204

Working on a fix.

**Comment by Guardiola31337** [comment]
@JunDai 
> Just checked the legacy code, I think we don't cleanup `NavigationService` when the NavigationViewModel destroys itself. see -> https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L204

What do you mean here? 👀 https://github.com/mapbox/mapbox-navigation-android/blob/d24bf065aa00cf7b5267c7b125930091874e9af0/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java#L136

**Comment by JunDai** [comment]
@Guardiola31337 - yeah, we are talking about the same thing. So you could see in the legacy `NavigationView` code, its onDestroy will call NavigationViewModel's onDestroy to **endNavigation** which is as you mentioned above. And within that endNavigation the legacy code will stop the NavigationService. See my link above.

But this code isn't there in the new Core SDK. That's why we see the notification is still there even the NavigationView is already been destroyed.

**Comment by Guardiola31337** [comment]
@JunDai 
> But this **stopNavigationService** logic isn't there in the new Core SDK. That's why we see the notification is still there even the NavigationView is already been destroyed.

Ohh I see, yeah you're right, now the session should be explicitly ended from `NavigationView` (and any other UI components if needed) 👍

**Comment by JunDai** [comment]
so are we intentionally to remove the **stopNavigationService** logic out of the Core SDK or it might just be forgotten? I mean the fix will depends on it. Should we want to add this back to the Core or the Core's consumer should take care of it?

possible solutions:
* put the **stopNavigationService** back into Core when MapboxNavigation onDestroy
* call **stopNavigation** when NavigationView onDestroy

**Comment by Guardiola31337** [comment]
Yeah, that's correct and those are the right questions we need to answer 👍
