### ISSUE TITLE
Map is not loading sometimes in the examples Activities

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2840]

**Comment by JunDai** [comment]
@Guardiola31337 - I can 100% reproduce this issue by a fresh install of the `example` app. 
While as I mentioned in the PR #2877 the reason is in the fresh install case, the map style is not loaded successfully before we get the location update success callback. And the navigationMapboxMap is not initialized so we couldn't set location to it.

I verified this fix on most of the example activities. We should be good here.
If you still see it, let me know which activity is ok.
