### ISSUE TITLE
Vanishing route line issues

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2868]
When testing the test app noticed various issues related to the vanishing route line feature https://github.com/mapbox/mapbox-navigation-android/pull/2804 👀 

![route_vanishing_issues](https://user-images.githubusercontent.com/1668582/80655270-3a63fb80-8a4c-11ea-9468-48e901d7fa8d.gif)

This is pretty easily to reproduce using the `ReplayActivity` example. The video reproduces https://github.com/mapbox/mapbox-navigation-android/issues/2859 https://github.com/mapbox/mapbox-navigation-android/issues/2859#issuecomment-621489073 https://github.com/mapbox/mapbox-navigation-android/issues/2859#issuecomment-621490508 and some other issues.

Feel free to close this ticket if the new ones were known issues and if we are already tracking them separately.

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2849 https://github.com/mapbox/mapbox-navigation-android/issues/2847

cc @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
There's a limit on what can be done when zooming in on the map like that. The vanishing point of the line is based on percentage of the distance traveled not an exact location which as far as I know isn't provided in route progress update. In addition the replay engine moves a lot faster than a car would in the real world exaggerating the issue. https://github.com/mapbox/mapbox-navigation-android/pull/2870. updates the behavior and in my testing the issue is less noticeable.  I'm attaching a video of the behavior using a mock location app and the code in the update related to PR #2870.

![20200430_091246](https://user-images.githubusercontent.com/2249818/80733728-ecd6a580-8ac2-11ea-81e5-bba04c1e81d2.gif)

**Comment by cafesilencio** [comment]
PR #2859 made significant improvements. At the moment I'm not sure what more can be done. The issue is only seen if the map is zoomed in as far as possible.
