### ISSUE TITLE
Route artifacts when vanishing line is enabled and rerouting

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2964]
![ezgif com-optimize (35)](https://user-images.githubusercontent.com/16925074/81805291-e01e6c80-951a-11ea-86c6-efb79c3543ea.gif)

/cc @cafesilencio @abhishek1508 @Guardiola31337

**Comment by LukasPaczos** [comment]
This has been reproduced when running https://github.com/mapbox/mapbox-navigation-android/pull/2960 but should generally be unrelated.

**Comment by LukasPaczos** [comment]
@cafesilencio can this still an issue given the recent iterations?

**Comment by cafesilencio** [comment]
@Łukasz Paczos <lukasz.paczos@mapbox.com> I don't think it's an issue but I
have to do some testing to confirm.

**Comment by cafesilencio** [comment]
What I'm seeing in the video above make sense to me. The maneuver arrows are updated on route progress updates so when the re-route happens a new route gets drawn which leaves a marker for the new origin waypoint and on the next progress update event that's received the arrows get updated. There is some additional dialog between myself and pablo here: https://github.com/mapbox/mapbox-navigation-android/pull/3141

**Comment by LukasPaczos** [comment]
I see a couple of ways for us to improve this behavior:
1. Hide the maneuver arrow when the route is redrawn and show it with the next progress update.
2. Investigate why the route line is shown fully -> jumps to the next steps -> goes back to starting from the puck. There has to be an issue with the way we calculate the vanishing point when the route is redrawn.

**Comment by cafesilencio** [comment]
Regarding point 2 please see this comment, I think it offers an explanation.   https://github.com/mapbox/1tap-android/issues/359#issuecomment-643345283

1. Something like this will need some careful consideration. The route progress listener can't take for granted the arrows are visible since they can be made invisible in the MapRouteLine class. A client commented in the past about the sometimes inconsistent or unpredictable behavior of the route arrow visibility. I don't want to introduce any regressions. I'll examine the issue further.
