### ISSUE TITLE
Dokka. Enable Kotlin docs 

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2986]
Based on https://github.com/mapbox/mapbox-navigation-android/pull/2423#issuecomment-578235046 enable KDocs via Dokka. See [Dokka `output formats`, `html`](https://github.com/Kotlin/dokka#output-formats)

**Comment by langsmith** [comment]
I'm not sure how to do multiple formats, but the way to create kdocs is to not declare any `outputFormat` at all because kdocs is the default Dokka format.

<img width="540" alt="Screen Shot 2020-05-18 at 8 52 18 AM" src="https://user-images.githubusercontent.com/4394910/82233447-e333a700-98e4-11ea-899f-61e15f480e50.png">

https://github.com/mapbox/mapbox-navigation-android/search?q=outputFormat&unscoped_q=outputFormat

**Comment by langsmith** [comment]
cc @colleenmcginnis

**Comment by RingerJK** [comment]
Based on internal discussion: keep `kdoc` only
