### ISSUE TITLE
LocationEngine wiring not working

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3057]
**Android API:**
**Mapbox Navigation SDK version:**

Debugging issues where we're seeing the LocationComponent being updated with raw locations, not the enhanced locations. Finding that the LocationEngine is not being wired between the various components correctly. Hacking reference: https://github.com/mapbox/mapbox-navigation-android/pull/3054

Code flow is
 1. public [NavigationMapboxMap is constructed](https://github.com/mapbox/mapbox-navigation-android/blob/71e8195ce0418bb7d67e77432790198b374dea52/examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt#L99) example
 2. private [NavigationMapboxMap.initializeLocationComponent](https://github.com/mapbox/mapbox-navigation-android/blob/71e8195ce0418bb7d67e77432790198b374dea52/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L175)
 3. private [LocationComponent unsubscribes LocationEngine](https://github.com/mapbox/mapbox-gl-native-android/blob/5f7c224e76be7dc75744869dc892fcb92be28e24/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L502)
 4. public [NavigationMapboxMap.addProgressChangeListener](https://github.com/mapbox/mapbox-navigation-android/blob/71e8195ce0418bb7d67e77432790198b374dea52/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L384) 

I'm not seeing the way to construct the LocationComponent with the LocationEngine from NavigationMapboxMap. addProgressChangeListener is the only way for NavigationMapboxMap to set MapboxNavigation - and the only place to get NavigationOptions?

cc: @LukasPaczos @cafesilencio @JunDai @abhishek1508 @Guardiola31337

**Comment by LukasPaczos** [comment]
The `LocationComponent` used in the Nav UI environment should not consume data from any location engine. That's why the flag to keep it uninitialized is passed. The only updates that should be pushed to the `LocationComponent` in the `NavigationMapboxMap` are the ones that are coming from the Nav Native, and this is happening via the [`locationObserver`](https://github.com/mapbox/mapbox-navigation-android/blob/71e8195ce0418bb7d67e77432790198b374dea52/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L923) here: https://github.com/mapbox/mapbox-navigation-android/blob/71e8195ce0418bb7d67e77432790198b374dea52/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L304-L312

If we would initiate the component with any `LocationEngine`, it would go rogue and request raw location updates by itself, which would compete with the updates that we're pushing from Nav Native via the `LocationComponent#forceLocationUpdate`.

**Comment by kmadsen** [comment]
> If we would initiate the component with any LocationEngine, it would go rogue and request raw location updates by itself, which would compete with the updates that we're pushing from Nav Native via the LocationComponent#forceLocationUpdate.

Yeah fair enough, but it seems LocationComponent is still supporting LocationEngine. Created this ticket when trying to figure out how you can do that.

Fixed the driver app's issue by removing LocationComponent.LocationEngine initialization. Closing this ticket as not actionable.
