### ISSUE TITLE
Provide default navigation options as a default argument

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3187]
Refs https://github.com/mapbox/mapbox-navigation-android/issues/3182#issuecomment-644956033.

This ticket tracks exploring whether we could inject `MapboxNavigation#defaultNavigationOptions` automatically as a default argument (or any other way), to make the `NavigaitonOptions` optional and fill the gaps where needed.

/cc @Guardiola31337 @kmadsen

**Comment by kmadsen** [comment]
Spent some time thinking of configuration, so will post the thoughts on it. 

**application context** is required for the default implementation of onboard router, and default distance formatter, probably more features. think it's fair to make this a required field, rather than passing it to each feature.

**access token** is required to make most features work. but it can become invalid. It shouldn't be nullable, but we should have an experience for when it's invalid.

Actionables
 - Make DistanceFormatter an optional feature and remove it from NavigationOptions, but that [has a bit of work](https://github.com/mapbox/mapbox-navigation-android/issues/3016) 
 - LocationEngine can be provided alone, without the LocationEngineRequest. still, it'd be better to move them to NavigationOptions instead of the constructor
 - MapboxNavigation object can be recreated, but internal state is static. This causes issues like the [ThreadController](https://github.com/mapbox/mapbox-navigation-android/issues/3156) and [configuration changes](https://github.com/mapbox/navigation-sdks/issues/402). Need a way to control the state of the main MapboxNavigation interface

If we truly wanted to make `NavigationOptions` optional, and have an empty constructor, with everything working for `MapboxNavigation`. There's a way to get there, but that'd be a lot. I think we can consider Context and access_token required, similar to maps. Plan to get there would be short.

It would be nice to provide the context and access token in one place, even share them with Maps because these are the only required fields there. Better maps and nav integration would be out of scope of this, considering we have plenty of nav only options to sort out.

**Comment by kmadsen** [comment]
> LocationEngine can be provided alone, without the LocationEngineRequest. still, it'd be better to move them to NavigationOptions instead of the MapboxNavigation constructor

Here's what the migration would look like for this one https://github.com/mapbox/mapbox-navigation-android/pull/3191

It would simplify usage a bit, because right now all our examples require us to interact with the LocationEngine directly. But it would be much better to hand that off to TripSession, because it is also making requests to the LocationEngine

**Comment by kmadsen** [comment]
Posting a status here to make sure there is agreement, here are two action items to conclude the refactor. 

There are two remaining defaults created in the [defaultNavigationOptionsBuilder()](https://github.com/mapbox/mapbox-navigation-android/blob/589c5a45a7cccddd6363b436699ccc525389ea2e/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L686-L700)

1. MapboxDistanceFormatter is still required, considerations and approaches were [tracked here](https://github.com/mapbox/mapbox-navigation-android/issues/3016) 
1. OnboardRouterOptions.Builder() still requires a default file path `internalFilePath`: think we agree this should be moved internally. Now that NavigationOptions has a application context, we can do this

After these, we could remove the need to have a seperate default builder function

What do you think about those tasks? cc: @LukasPaczos  @Guardiola31337

**Comment by LukasPaczos** [comment]
`2.` sounds good to me!

For `1.`, it'd be great o see a draft PR. That'd give us an idea of the volume of changes needed.

**Comment by kmadsen** [comment]
> 2. sounds good to me!

https://github.com/mapbox/mapbox-navigation-android/pull/3308 🥳  , awesome feel free to review! 

> For 1., it'd be great o see a draft PR. That'd give us an idea of the volume of changes needed.

Yeah this is a bigger project. Here was [the incomplete draft](https://github.com/mapbox/mapbox-navigation-android/compare/km-distance-formatter-as-a-feature). Conclusions recorded here https://github.com/mapbox/mapbox-navigation-android/issues/3016

the tl;dr is MapboxDistanceFormatter is only used for user interfaces - won't make sense if you're using core without ui

**Comment by Guardiola31337** [comment]
Where are we here @kmadsen? Could you provide an update when you have a chance? 🙏

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/3016

The MapboxDistanceFormatter is still the thing that needs to be moved. As shown in the default function, it is still required in order to create a default object
https://github.com/mapbox/mapbox-navigation-android/blob/afdd8587b684cf7b82f44288cc2063444d96cfe5/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L862-L865
