### ISSUE TITLE
Router getRoute() method failing

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3218]
### Android API is 21 or newer

application dependencies {
        //////////////////  MAPBOX BETA STUFF  ////////////////////////////
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.4'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.4'
        //this has symbol manager
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
        // this looks like incomplete implementation
        //implementation 'com.mapbox.base:annotations:0.1.1'
        //////////////////  MAPBOX BETA STUFF  ////////////////////////////
}

Router.getRoute(myRouterOptions, myRouterCallback) fails when adding these annotations to the options
 								 
DirectionsCriteria.ANNOTATION_DISTANCE
DirectionsCriteria.ANNOTATION_DURATION
DirectionsCriteria.ANNOTATION_SPEED

### Steps to trigger behavior

 1. Create a Router object
 2. Assign the above annotations to the options
 3. call Router.getRoute() with the options and callback parameters

### Expected behavior
a successful route returned

### Actual behavior
The server API call resulted in an HTTP 400 error and return message of:
{"message":"enable_refresh only works with maxspeed or congestion annotations"}

### Remediation
I added the ANNOTATIONS_MAXSPEED to the options and this resolved the getRoute() call successfully.

**Comment by Guardiola31337** [comment]
Hey 👋 @tkvalentine56 thanks for checking out the SDK

> The server API call resulted in an HTTP 400 error and return message of:
{"message":"enable_refresh only works with maxspeed or congestion annotations"}

That sounds like working as designed to me. https://docs.mapbox.com/api/navigation/#directions response is returning an error with a message pointing to the root cause which BTW is out of control from the SDK side. Are you expecting that the SDK includes that annotation by default? Not sure what's the problem here 🤔 

cc @danpaz

**Comment by Guardiola31337** [comment]
Speaking offline with @danpaz it seems the issue is in https://github.com/mapbox/mapbox-navigation-android/blob/6845983f0ebf852b4987ab3ee7b3f83324384e30/libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt#L56 which should be something like 

```
.enableRefresh(routeOptions.profile() == DirectionsCriteria.PROFILE_DRIVING_TRAFFIC && (congestion_annotations=true || maxspeed_annotations=true))
```

Could you confirm @danpaz?

cc @kmadsen

**Comment by danpaz** [comment]
That's right @Guardiola31337. For the `enable_refresh` option to work the Directions API requires that you set `overview=full` and request congestion or maxspeed annotations, and use the mapbox/driving-traffic profile. The idea with refresh is that the SDK can re-request annotations along your path as you're navigating. So for this feature to work your path needs to be full geometry (overview=full) and have annotations that need to be refreshed (like traffic-influenced congestion annotations).

**Comment by kmadsen** [comment]
@tkvalentine56 are you still running into this error when using `.overview(DirectionsCriteria.OVERVIEW_FULL)`?

Many features in the navigation SDK require route geometry, which is why it's one of the default options
https://github.com/mapbox/mapbox-navigation-android/blob/fcb72496ecfd94acbd352682f37c1c86c4c4f14e/libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt#L23

| [overview](https://docs.mapbox.com/api/navigation/#directions) |
| -- |
| Displays the requested type of overview geometry. Can be full (the most detailed geometry available), simplified (default, a simplified version of the full geometry), or false (no overview geometry).|

**Comment by tkvalentine56** [comment]
Kyle,

I have resolved it and moved forward. The real issue here is the
RouteOptions permutations of all the settings available. If you do not have
the accepted options when calling 'getRoute()' on the Router object, then
it fails and you get an ambiguous error return of 'Failed'.

It took me three weeks of part-time investigation to drill into the API to
find out that the real error was based on the 'refresh' feature and that I
did not have the maxspeed_annotations options set.
So not questioning your logic for requesting a route here but a detailed
set of documentation of what options/option sets are required when certain
key options are set would have saved me 2.5 calendar weeks of poking around
and getting truthful but incomplete detailed responses of 'it works for me'
from others on your team.

Thank you,
Tim Valentine

**Comment by zugaldia** [comment]
Thank you @tkvalentine56 for trying the Preview release and for the documentation feedback. Sorry to hear about the confusion using the options object - we've got an internal ticket open tracking documentation updates to the route generation section. I understand we're good to close this ticket, please reopen it otherwise.
