### ISSUE TITLE
Update documentation and examples to use MapboxNavigationProvider

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3224]
https://github.com/mapbox/mapbox-navigation-android/issues/3156 and https://github.com/mapbox/mapbox-navigation-android/pull/3212 follow up.

As mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/3212#pullrequestreview-436608904, to fully resolve the issue we still need to:
- [ ] expose a way to destroy the provider
- [ ] make the MapboxNavigation's constructor internal
- [ ] update examples
- [ ] update the documentation to reflect the recommendation to use the `MapboxNavigaitonProvider`

/cc @mapbox/navigation-android

**Comment by korshaknn** [comment]
we also need a way to destroy `Provider`

**Comment by korshaknn** [comment]
so, do we want to save `ThreadController` as a singleton?
If we make `MapboxNavigation` constructor internal -> `MapboxNavigationProvider` will be the only way to get it. And Provider will handle `onDestroy` call on each `navigation` instance. And we won't have coroutine issues in `ThreadController`
@LukasPaczos @Guardiola31337 @kmadsen

**Comment by Guardiola31337** [comment]
One other thing that we found out integrating `MapboxNavigaitonProvider` in https://github.com/mapbox/mapbox-navigation-android/pull/3191 is that 👇 (you beat me to it @korshaknn 😅)

> we also need a way to destroy Provider

but another one is that it's not lifecycle aware. Noting that in the legacy we relied on the service to handled that 👀 https://github.com/mapbox/mapbox-navigation-android/blob/6845983f0ebf852b4987ab3ee7b3f83324384e30/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L1137 but not anymore. We should look into that as well.

Also if `MapboxNavigationProvider` handles `MapboxNavigation` destruction we might be able to remove `MapboxNavigation#onDestroy` (one less method to expose and maintain publicly) or replace it with an `unregisterListeners` or something.

cc @kmadsen

**Comment by Guardiola31337** [comment]
Another discussion point is how would you as a client change the options dynamically using `MapboxNavigationProvider`? Let's say that you want to disable predictions when in _Free Drive_ and enable them when in _Active Guidance_. It seems that `MapboxNavigation` needs to be recreated. Is that how you envisioned supporting this scenario?

cc @korshaknn @LukasPaczos @kmadsen

**Comment by LukasPaczos** [comment]
In my opinion, options that impact the behavior of the SDK this much should rather be immutable, especially if there's no strong use-case. If we want to support different prediction patters for free-drive and active guidance, that should be 2 separate fields in settings. I other cases, the `MapboxNavigation` should be recreated.

**Comment by kmadsen** [comment]
> expose a way to destroy the provider

Customers also want MapboxNavigation to continue to work without being destroyed (added a link to this discussion). Like Pablo said, we're also exploring removing the MapboxNavigation.onDestroy with more explicit calls - because onDestroy can do and not-do a lot of things.

> make the MapboxNavigation's constructor internal

We should continue to look into issues when using MapboxNavigationProvider before we force usage with a internal MapboxNavigation constructor. Let's make sure all the examples are migrated and working before forcing usage

> Another discussion point is how would you as a client change the options dynamically using MapboxNavigationProvider?

I think dynamic options should be inside MapboxNavigation, not in constructor options. But right now the way to change options with MapboxNavigationProvider is to create a new one
https://github.com/mapbox/mapbox-navigation-android/blob/fcb72496ecfd94acbd352682f37c1c86c4c4f14e/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigationProvider.kt#L36-L37

When integrating, another question was wondering if there should be an MapboxNavigaitonProvider function to check if an instance of MapboxNavigation has been created. The solution I found for this was to check savedInstanceState, but you won't always be in an Activity.onCreate
``` kotlin
fun onCreate(savedInstanceState: Bundle?) {
  if (savedInstanceState == null) {
    val mapboxNavigationOptions = MapboxNavigation
        .defaultNavigationOptions(this, Utils.getMapboxAccessToken(this))
        .locationEngine(getLocationEngine())
        .build()
    MapboxNavigationProvider.create(mapboxNavigationOptions).apply {
```

**Comment by korshaknn** [comment]
so, let's summarize:
- `MapboxNavigation` constructor should NOT be `internal`. Some customers need to work with `MapboxNavigation` directly, also we need to test  `MapboxNavigationProvider` before forcing to use it.
- `onDestroy` can't be removed from `MapboxNavigation`. It depends on the first point ^^.
- if you want to change `options`, you need to create a new instance of `MapboxNavigation`
- `MapboxNavigationProvider` should have a method to check if  `MapboxNavigation` is created
- `MapboxNavigationProvider` should have `destroy` method

@Guardiola31337 , @kmadsen , @LukasPaczos
