### ISSUE TITLE
Use directions token for guidance images

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3225]
Currently, the guidance images are requested using the Maps token
https://github.com/mapbox/mapbox-navigation-android/blob/fcb72496ecfd94acbd352682f37c1c86c4c4f14e/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java#L725-L727

however, it should rather accept and use a provided directions token so that it always matches the token that's used by the developer to interact with the Directions API.

/cc @abhishek1508 @Guardiola31337

**Comment by Guardiola31337** [comment]
Great catch @LukasPaczos

**Comment by abhishek1508** [comment]
This is what do as developer inside `NavigationAppplication`

```
private fun setupMapbox() {
        val mapboxAccessToken = Utils.getMapboxAccessToken(applicationContext)
        if (TextUtils.isEmpty(mapboxAccessToken) || mapboxAccessToken == DEFAULT_MAPBOX_ACCESS_TOKEN) {
            MapboxLogger.w(Message("Mapbox access token isn't set!"))
        }

        Mapbox.getInstance(applicationContext, mapboxAccessToken)
        MapboxNativeNavigatorImpl.create(HandheldProfile(), MapboxLogger)
    }
```

Since, this is setting my account related `accessToken` to `Mapbox.getInstance()`, when I request it from `Mapbox.getAccessToken()` I get the same token as above.

Is there some other way to retrieve the token the developer might be setting when making Directions API request?
cc @LukasPaczos

**Comment by LukasPaczos** [comment]
@abhishek1508 the Directions API request doesn't have to be executed with the same token that is used for the Maps SDK. Especially in non-drop-in scenarios and since all of the request params are prepared by the developer, not by the SDK.

We might want to consider passing a token as a constructor argument for the `InstructionView` or passing it as an argument to `InstructionView#determineGuidanceView` so that the developer can control it and ensure it matches the token that was used to request the route. It'd be great to document it in the same place as well.

**Comment by Guardiola31337** [comment]
Another option is to expose a getter in `MapboxNavigation` and rely on that one from the UI SDK. Noting that we exposed it already in the legacy 👀 https://github.com/mapbox/mapbox-navigation-android/blob/fcb72496ecfd94acbd352682f37c1c86c4c4f14e/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L955-L957

Only problem that I see with ☝️ approach is using the `InstructionView` as a stand-alone component i.e. without creating and interacting with `MapboxNavigation` at all - although not sure if that's an option at the moment and even if this is something we'd like to support because UI SDK heavily relies on Core SDK 🤔 If we want to support it though we'd need to implement something around the lines @LukasPaczos suggested.
