### ISSUE TITLE
ui.v5.NavigationView could not be resolved, can't find replacement

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3331]
**Mapbox Navigation SDK version:** 1.0.0-rc2     `implementation 'com.mapbox.navigation:core:1.0.0-rc.2'`

### Steps to trigger behavior

 1. Try to migrate from 0.x to 1.0.0-rc2
 2. `com.mapbox.services.android.navigation.ui.v5.NavigationView` can no longer be found

### Expected behavior
I expected this to either work or to be replaced. In the case this was replaced, it should be mentioned in the migration guide.

### Actual behavior
Could not find another view class via the autocompletion. Not sure how to proceed. Installation guide and other docs that I read also did not mention a replacement.

**Comment by Guardiola31337** [comment]
Hey @carstenhag thanks for reaching out 👋 

This shouldn't be the case anymore. You were trying to access `NavigationView` which is in the `com.mapbox.navigation:ui` artifact which is intentional (they're separate artifacts) and UI artifact wasn't available by the time you created this ticket. You should be able to access it now as UI is publicly available (latest release as of today is `1.0.0-rc.6` for both Core and UI).

Noting here that we changed the package name from `com.mapbox.services.android.navigation.ui.v5` to `com.mapbox.navigation.ui` and we're explicitly mentioning that in the `About the 1.0 Navigation UI SDK` section of the _1.0 Navigation SDK Migration Guide_ 👀  https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide#namespace-changes

Closing here as answered.

**Comment by carstenhag** [comment]
Sorry, thought these old issues from me were already closed. As you may have seen in my other issues, we are now using 1.0.0-rc.6 etc. Thanks though, maybe someone else will find this useful :)
