### ISSUE TITLE
Tampering with a builder returns inconsistent results

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3343]
Follow up to https://github.com/mapbox/mapbox-navigation-android/issues/2709#issuecomment-631117281.

The proposed pattern accepts the builder instance as an argument and returns the same reference back instead of rebuilding it. This means, that if the original builder has been tempered with, fetching the builder reference from the object and rebuilding it right away won't equal the initial one.

This is reproducible with a simple test:
```
@Test
fun reuseChangedBuilder() {
    val builder = NavigationOptions.Builder(context)
    val options = builder.build()
    builder.accessToken("pk.123")

    assertEquals(options, options.builder.build())
}
```

The `assertEquals(options, options.builder.build())` invocation should always pass, regardless of the circumstances.

The `toBuilder` methods of data classes should not return the same builder instance that they were built with, they should recreate the builder from scratch.

When refactoring this, we should add a generic builder test that each implementation could extend taht iterates through all of the fields and makes sure that they match the spec we're after.

/cc @kmadsen @Guardiola31337

**Comment by kmadsen** [comment]
Yeah I noticed this too. Thanks for opening Lukas. I've been trying pretty hard to not override equals and hash, but I'm not sure how else to do it. It may be the best option, because then we can also make a private constructor.

What would you think of modifying the pattern to be

``` kotlin
class FooOptions private constructor(
  val property: String,
  val value: Int,
  val builder: Builder
) {
    fun toBuilder() = builder

    override fun equals(other: Any?): Boolean { }
    override fun hashCode(): Int { .. }
}
```

We'll need a way to make sure equals and hashCode are regenerated after changes. would be great if we could make this automatic, but right now it seems like we'll need to _remember_.

Also when generating the equals and hash, don't add the builder.
![Screen Shot 2020-07-15 at 8 01 18 AM](https://user-images.githubusercontent.com/3021882/87561333-60736200-c671-11ea-996e-002d4e6d4836.png)

Also, private constructor will have the benefits of removing SEMVER when we add values to these objects.

**Comment by LukasPaczos** [comment]
@kmadsen the `toBuilder` method would need to look more like this:
```kotlin
fun toBuilder() = Builder(required).apply { non-required }
```

Since https://github.com/mapbox/mapbox-navigation-android/issues/2709 is revived, I'm gonna close this ticket, let's continue the discussion there.
