### ISSUE TITLE
Re-route doesn't work in example app

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3347]
**Android API:** OS 10
**Mapbox Navigation SDK version:** Navigation 1.0 SDK

### Steps to trigger behavior

 1. Use `Mock Locations` app to build a route A
 2. Launch the `example` test app and select `Basic Navigation` example
 3. Build a different route B, it's different with route A in step 1
 4. Click `Start Navigation` button

### Expected behavior

Since route A and B are different, there should be re-route event and the new route should be drawn on the map.

### Actual behavior

The puck moves following route A and the map doesn't have any routeLine on it.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/3918950/87613485-4ca41c00-c6c2-11ea-8753-2b54508e5375.gif)

**Comment by JunDai** [comment]
@Guardiola31337 also saw this issue, refer: https://github.com/mapbox/mapbox-navigation-android/pull/3297#pullrequestreview-448300302

**Comment by cafesilencio** [comment]
Per Lukas's suggestion this may be related to https://github.com/mapbox/navigation-sdks/issues/489. I've checked out several commits during July to try and identify where it was introduced but I get inconsistent results.  When I test on the current master branch I will get inconsistent results. During a given trip session I will sometimes see the first reroute succeed but the second won't because the progress listener doesn't get a new route and the route state in the route received is invalid.  Other times the very first reroute will fail.

**Comment by cafesilencio** [comment]
I can see in MapboxTripSession that often ( but not always ) there is a route progress emitted in updateRouteProgres(...) which will have a state of OFF_ROUTE followed by repeated ROUTE_INVALID emissions.  The route emitted by the updateRouteProgress method doesn't change when this happens.  When the reroute is successful the state goes from OFF_ROUTE to LOCATION_TRACKING and a different route is emitted.

cc @LukasPaczos

**Comment by LukasPaczos** [comment]
This is related to https://github.com/mapbox/navigation-sdks/issues/489. Currently, we receive only on off-route event which is followed by invalid until we provide a new route.

**Comment by Guardiola31337** [comment]
Where are we here? Good to close?

**Comment by cafesilencio** [comment]
I think this issue has been resolved with the changes in the 2.x code stream.
