### ISSUE TITLE
UI classes such as MapboxNavigationMap or MapView not available on 1.0.0-rc2 release

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3350]
I am trying to migrate to the new mapbox navigation sdk. 

**Mapbox Navigation SDK version:** 1.0.0-rc2

### Steps to trigger behavior

 1. See MapboxNavigationMap and MapView classes at example code: https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
 2. Try to also use it
 3. Classes not found. I seem to use the wrong lib/dependency, but it is unclear where to get the correct one from.

### Expected behavior
Readme/installation instruction/migration guide shows which dependency should be used for nav only, and which for nav + UI.

### Actual behavior
Readme/installation instruction/migration guide don't mention UI components at all.  
I can't further perform the migration, because the needed classes aren't available.

**Comment by carstenhag** [comment]
@LukasPaczos Hello there, first off, sorry to ping you directly.
I can't continue the migration if these things are missing. Could you or someone else please help me on this? I must be missing something, because in the releases and the other pages I was not able to find an UI dependency :(.

**Comment by LukasPaczos** [comment]
Hey @carstenhag!

The documentation found on https://docs.mapbox.com/android/beta/navigation/overview/ and the `1.0.0-rc` series only covers the Navigation Core SDK features, this means localization and routing. We are currently migrating the UI components to be compatible with the new Navigation Core SDK and they will be publicly released together with the stable release of the Navigation Core 1.0 in the next couple of weeks. If you do have an opportunity to test only the Navigation Core SDK, we would really appreciate the feedback on the API design, otherwise, the UI components will be available soon.

I'm gonna go ahead and close here, but let us know if you have any other questions!

**Comment by carstenhag** [comment]
Thanks for the answer, now everything makes sense 👍 .
