### ISSUE TITLE
Android: No Voice Instructions

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#344]
Upon starting the Navigation UI, I get the first instruction "Turn left in 100 feet" i then imediatly get the second instruction "Turn left in 100 feet".

Once I recieve this voice instructions I no longer get anymore voice instructions.

**Comment by cammace** [comment]
Can you provide additional information to help us reproduce this issue? Are you using Polly voice engine or the default Android one? Do you have a specific route which we can use to reliably reproduce this, if so, can you pass the Directions API request URL? Are you getting milestone event callbacks still and that is why you are saying there is no voice instructions or is the navigationMilestoneEvent callback not even getting called? All of these along with additional information will help us troubleshoot the issue. Otherwise we have no way to reproduce.

**Comment by Danny-James** [comment]
@cammace This is quite difficult as im driving when testing, I'm not using polly as im not sure how to set this up as their are no detailed instructions (Maybe something you should provide) - I'm setting the `awsPoolId` as `NULL` to use the `AndroidVoice`.

In regards to the Route, it's happening with every route I try, I Start from my Current Location and I then plot waypoints and a destination (i'm using this for a crane routing application, so the crane as to stick to a signed off route by the authorities).

As i have more than 3 waypoints I am unable to use the traffice routing so i use the Simple driving DirectionsRoute - if this makes sense and provides any more info.

I simply call - `NavigationLauncher.startNavigation(this, route, null, false)`

So i don't have any access over any milestones/callbacks (this is another of my questions how to pass options to this as i can't see a way to do this)

If you would like anymore info i will try to provide as best i can.

**Comment by Danny-James** [comment]
I'm now using  0.6.2  and the voice is working, however i don't have any  direction instructions  when selecting directions in the bottom view on the  Navigation UI .

**Comment by Danny-James** [comment]
![screenshot_20171018-122758](https://user-images.githubusercontent.com/32104383/31716562-5de1d8cc-b400-11e7-8088-5d24eacb91d0.png)

**Comment by Danny-James** [comment]
This Seems To Have Been Resolved @cammace will report the directions as a new issue if it happens again.
