### ISSUE TITLE
 1.0.0-rc.6 is stable version 

### ISSUE THREAD

**Issue by AbdullahSoubeih** [mapbox/mapbox-navigation-android#3512]
1.0.0-rc.6 is stable version ?? , so I can using it with my project without any issues

**Comment by LukasPaczos** [comment]
Hey @AbdullahSoubeih! Release candidates are not considered production-ready releases but they are a good point in time to expect API stability and start migrating your codebase. A stable 1.0.0 will follow in the next couple of weeks. We appreciate any feedback you might have so that we can address it before going stable, thanks!
