### ISSUE TITLE
Thoughts about the usage of NavigationMapRoute#addRoutes() (naming, annotations)

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3571]
**Android API:**. not relevant
**Mapbox Navigation SDK version:**
```
    implementation 'com.mapbox.navigation:ui:1.0.0-rc.7'
    implementation 'com.mapbox.navigation:core:1.0.0-rc.7'
```

### Actual & Expected behavior
The `NavigationMapRoute#addRoutes()` method suggests that routes are only added, but looking into its code it seems like the routes are actually set.  
Same applies to `addRoute `. There is also `MapboxNavigation#setRoutes()` which accepts the same parameter but has a set in its name ;).

Further, the min size annotation does not seem to make sense, as there's a specific `isEmpty()` handling in the method. Especially weird as there is no `clearRoutes()` method.
```java
addRoutes(@NonNull @Size(min = 1) List<? extends DirectionsRoute> directionsRoutes)
```

**Comment by Guardiola31337** [comment]
cc @abhishek1508 @cafesilencio

**Comment by carstenhag** [comment]
Not stale

**Comment by cafesilencio** [comment]
Thanks for the feedback @carstenhag. I agree with you. The naming can be improved and the method made more clear. Changing the name in the 1.x version would break SemVer but the name has already been changed for 2.x. The size annotation looks erroneous since passing an empty list is supposed to be a way to clear the routes. This can be updated in an upcoming release of 1.x.

**Comment by carstenhag** [comment]
Thanks for fixing this!
