### ISSUE TITLE
Destination Address supposed to be shown in the toolbar when we reached the actual destination

### ISSUE THREAD

**Issue by arunpandian22** [mapbox/mapbox-navigation-android#3601]
![image](https://user-images.githubusercontent.com/24975205/94566390-e6be3e00-0287-11eb-88e7-6b82889d0256.png)

### Expected behaviour
* When the User reached the destination address, the address need to be displayed in the tool bar along with arrived message

### Actual behaviour
* Currently the toolbar simply shows the arrived message only

**Comment by Guardiola31337** [comment]
Thanks for reaching out @arunpandian22 👋 

That's expected behavior. Have you checked [`RouteOptions#waypointNames`](https://github.com/mapbox/mapbox-java/blob/bc21013afe4c27dda816a2bc9f1646f90545b53a/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L950-L964) and [`RouteOptions#waypointNamesList`](https://github.com/mapbox/mapbox-java/blob/bc21013afe4c27dda816a2bc9f1646f90545b53a/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L966-L985). I think that's exactly what you're looking for. See also `waypoint_names` parameter docs https://docs.mapbox.com/api/navigation/#retrieve-directions

Also friendly reminder that this issue tracker is only for bug reports with test cases and feature requests. For implementation questions you can send a message to help@mapbox.com and reference this ticket. Also, please check out our [help docs](https://www.mapbox.com/help/) or post your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/mapbox).  We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues.
