### ISSUE TITLE
Navigator#remainingWaypoints should only be called in Active Guidance

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3884]
Regression from https://github.com/mapbox/mapbox-navigation-android/pull/3581

Capturing from @averkhaturau

> It's not expected to provide remaining waypoints having no route.

We should refactor `MapboxTripSession` / `TripStatus` / `MapboxNativeNavigatorImpl` logic so that `Navigator#remainingWaypoints()` is called only when in _Active Guidance_ (maybe it's as simple as checking if `MapboxNativeNavigatorImpl.route` is `null` and not calling it / returning `0` remaining waypoints)

https://github.com/mapbox/mapbox-navigation-android/blob/c77d441172a905b93311ca265e532ebd88e61495/libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt#L123 

This is spamming the logs with messages like the following when in _Free Drive_

```
2020-12-23 09:30:58.750 7555-7709/com.mapbox.onetap.app E/nav-native: No routes when calling remainingWaypoints
```

cc @Lebedinsky @RingerJK @zugaldia @truburt

**Comment by Guardiola31337** [comment]
As discussed internally, noting that don't think this should be logged as an "error".

cc @averkhaturau

**Comment by averkhaturau** [comment]
Log level of this message will be changed to warning in next release of nav-native.
BTW, if possible by architecture it would be better to use [NavigationStatus.nextWaypointIndex](https://github.com/mapbox/mapbox-navigation-native/blob/be3d6fcd75975f378e781a985fa19430e632a922/bindings/navigator.mbg#L451) instead of `navigator!!.remainingWaypoints().size` from terms of performance if you know all waypoints. E.g.
`waypoints.size-status.nextWaypointIndex`.

**Comment by etl** [comment]
Would be great to put into 1.5

**Comment by Guardiola31337** [comment]
Isn't this fixed already @RingerJK?

cc @LukasPaczos

**Comment by LukasPaczos** [comment]
This is fixed in https://github.com/mapbox/mapbox-navigation-android/pull/3930 and https://github.com/mapbox/mapbox-navigation-android/pull/3972 and available in v2. We weren't planning to backport this to v1.

@etl is this a blocker that we should reconsider backporting?
