### ISSUE TITLE
Add annotations to RouteProgress object

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#41]
Now that RouteProgress has moved to an Android project, we can take advantage of the annotations to further ensure parameters, methods, classes, etc. are correct.

**Comment by Bharathjh614** [comment]
can we add annotations to mapbox navigation while navigation?

**Comment by danesfeder** [comment]
Hey @Bharathjh614, the annotations are added when you make the `DirectionsRoute` request, so to do this while navigating, you can request a new route with the annotations desired and then call `MapboxNavigation#startNavigation` with the new route.

**Comment by Bharathjh614** [comment]
I need to add annotations while navigating for example:
If the same application is installed by two users and they are navigating
for certain place using the same application if they both come accross the
same path if the distance between them is less than 150m then red marker is
shown and more than 150m green marker should be shown i have successfully
implemented this using skobbler maps but don't know to do with mapbox since
launch navigation calls the attached navigation project i couldn't do that.
Can anyone help with this
