### ISSUE TITLE
Mapbox Directions profile for roads of type access = private

### ISSUE THREAD

**Issue by murr999888** [mapbox/mapbox-navigation-android#4105]
I need to build routes on the territory of plants, factories and other places (there are long distances and a huge road network!), the roads to which are marked in the OSM with the tag access = private. To do this, I currently use my own OSRM server for other applications. 

I would like to use Mapbox Navigations's capabilities for this. Is there a Mapbox Directions profile that will allow me to build a route to such places? 

If it is possible to convert the OSRM server response to the Mapbox Direction route?

**Comment by Guardiola31337** [comment]
cc @mapbox/navigation-api

**Comment by kshehadeh** [comment]
@murr999888 Do you have some sample destinations we can look at?

**Comment by murr999888** [comment]
Map - Mariupol city, Ukraine
Start on a public road, end on a private road (Azovstal metallurgical plant), 
from/to for example

47.10142500672612, 37.57351040840149
47.100460982576806, 37.5818145275116

For normal navigation purposes, of course you've got it right. But for freight transport, a wider road network is needed. Including private roads. 
In OSRM I made a special profile for this and I can build such a route. I want to do something like this with Mapbox.

**Comment by stari4ek** [comment]
I've checked provided route. It works for `driving` profile and it works for `driving-traffic` if it's Valhalla-based (as opposite to OSRM-based).
![image](https://user-images.githubusercontent.com/327778/113299824-f46f8180-9305-11eb-97a7-24cdb12a23c8.png)
![image](https://user-images.githubusercontent.com/327778/113300587-bd4da000-9306-11eb-9b81-0d85e982b59b.png)

So, you can use `driving`. Otherwise, please contact customer support team to switch you to valhalla for `driving-traffic`.
/cc @kshehadeh

**Comment by murr999888** [comment]
Cool! Thanks!
