### ISSUE TITLE
Directions API requests should be canceled when NavigationActivity is destroyed

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#412]
It's good practice to cancel any calls that Retrofits making if the activity gets destroyed. We can make use of the Lifecycle component

![screen shot 2017-10-23 at 4 16 31 pm](https://user-images.githubusercontent.com/5652865/31911102-933b79a4-b80d-11e7-9ad8-a08155084ee0.png)
 to automatically cancel the event.

@zugaldia @danesfeder

**Comment by zugaldia** [comment]
Architecture components and Retrofit is explicitly mentioned on the official docs: https://developer.android.com/topic/libraries/architecture/guide.html#fetching_data

**Comment by cammace** [comment]
@danesfeder, I remember a few weeks ago you asked about canceling the request? Did this issue get worked out?

**Comment by danesfeder** [comment]
@cammace I didn't have a chance to add this to `NavigationRoute` but should be a quick PR to expose that API

**Comment by devotaaabel** [comment]
@cammace @danesfeder Assuming you are talking about having `NavigationRoute` implement `LifecycleObserver`, how were you invisioning setting it up with a `LifecycleOwner`? Passing the `LifecycleOwner` to the `NavigationRoute`, or manually setting it everywhere `NavigationRoute` is used? It's a little complicated in the case of `RouteEngine` because `NavigationRoute` is a couple steps removed from any `LifecycleOwners`.

**Comment by akitchen** [comment]
@danesfeder & @akitchen were discussing -- it would also be good to provide developers with a way to cancel outstanding requests from `NavigationRoute`
