### ISSUE TITLE
Confusing onFasterRoute API

### ISSUE THREAD

**Issue by yunikkk** [mapbox/mapbox-navigation-android#4233]
Currently faster route logic will fetch faster route every 5 minutes (customizable, but not less then 2 minutes), and determine that route is faster, if it's at least 10% (not customizable) faster than the current one. 
Then, after 5 minutes when faster route is requested, there are two possible situations:
- there is route faster than the current. 
FasterRouteObserver will call [onFasterRoute](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteObserver.kt#L23) with current route and an alternatives list, `isAlternativeFaster == true`; alternatives will still contain current route in the list of alternatives.
- there is no faster route, our route is still fastest. 
FasterRouteObserver will call [onFasterRoute](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteObserver.kt#L23) with current route, alternatives list with `alternatives[0]` the same current route and `isAlternativesFaster == false`. That was fixed at #3144 / #3301.

Couple of questions / notes regarding this: 

1. If user would like to still make use of it, even if we don't say new route is faster, they'll need to filter current route in some way (also, maybe compare it with the current RouteProgress), facing with the same complexities that we've dealt in #3301.
What I would expect is that `alternatives` list should _not_ contain the current route at all. Suppose we could filter it out from the alternatives.

2. By the way why the minimum 2 minutes limit was introduced? It's a bit weird that setting this value less that 2 minutes will just crash the application in runtime without any prior warnings. 

3. Could we customize 10% limit when calculating logic of faster route? We've ended up implementing similar logic on our side since had a requirement to show _any_ faster route, even 1 second faster than current.

cc  @mapbox/navigation-android; @kmadsen since you've implemented #3301

**Comment by kmadsen** [comment]
Hey thanks for the feedback! Some of the confusions are due to; porting an interface from v1 navigation, adding ideas, learning about the issues you listed. After we realized this is mostly about alternatives, there was some discussion about repurposing it as such (check linked issues)

IMO :)
![Screen Shot 2021-04-09 at 9 00 15 PM](https://user-images.githubusercontent.com/3021882/114257706-97fc0a00-9976-11eb-8b36-a38c62e0b100.png)

That's the background. Below will answer the numbered questions

> 1. If user would like to still make use of it, even if we don't say new route is faster, they'll need to filter current route in some way (also, maybe compare it with the current RouteProgress), facing with the same complexities that we've dealt in #3301.
What I would expect is that alternatives list should not contain the current route at all. Suppose we could filter it out from the alternatives.

Altering the RouteProgress into an object of relevant info is a good idea too. I just tried that for Arrival, [but ended up using RouteProgress](https://github.com/mapbox/mapbox-navigation-android/pull/4238). Happy to chat more about this

> 2. By the way why the minimum 2 minutes limit was introduced? It's a bit weird that setting this value less that 2 minutes will just crash the application in runtime without any prior warnings.

This was a product ask, see "Feature Change: Faster Route API" linked issue.

> 3. Could we customize 10% limit when calculating logic of faster route? We've ended up implementing similar logic on our side since had a requirement to show any faster route, even 1 second faster than current.

Also love this idea. The 10% limit came from legacy. Would like to loop in iOS to make something consistent.

**Comment by kmadsen** [comment]
We spoke about estimating the work in this ticket, and agreed it was still too ambiguous to start work. I've translated it into a actionable proposal here https://github.com/mapbox/navigation-sdks/issues/956

The goal of the proposal is to close address and close this ticket as well

**Comment by kmadsen** [comment]
@yunikkk Please take a look https://github.com/mapbox/mapbox-navigation-android/pull/4375

That new interface is trying to close this issue.
