### ISSUE TITLE
[Mapbox Navigation v2]: Crash on progress update

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4285]
**Android API:** 30
**Mapbox Navigation SDK version:** 2.0.0-beta.6

### Steps to trigger behavior

 1. Register a route progress observer
 2. Enable vanishing route line
 3. Post progress the directionsRoute so the routeLine is only shown to the first waypoint

### Expected behavior

Route line is shown to the first waypoint

### Actual behavior

SDK crashes

```
2021-04-19 17:13:14.179 8904-8904/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXXX.YYYYY, PID: 8904
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi.updateUpcomingRoutePointIndex$libnavui_maps_release(MapboxRouteLineApi.kt:566)
        at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi.updateWithRouteProgress(MapboxRouteLineApi.kt:385)
        at com.XXXX.YYYYY.fragments.navigation.NavigationFragment$routeProgressObserver$1.onRouteProgressChanged(NavigationFragment.kt:680)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:554)
```

**Comment by LukasPaczos** [comment]
cc @cafesilencio

**Comment by Guardiola31337** [comment]
Hey @sandyscoffable thanks for reaching out and report your issue.

Could you share your requests setup / `RouteOptions` you're adding and the `DirectionsRoute`s that you get / use when you have a chance?

**Comment by sandyscoffable** [comment]
Just giving a bit of background on this bug, as I think the code I have is potentially triggering it:
- App asks for a route with e.g 3 waypoints
- The route line view / api is then supplied with a route **_only_** to the first waypoint. The other parts are given the complete route

The reason for this is that it's quite confusing as a user when navigating to have the full route line (as you can't see where you're supposed to be driving when the full route line is shown and the route doubles back etc etc).

So I've got scrappy code like this to post-process the route into a single stop and then fire it into the route line API:
```kotlin
fun getFirstLegOfRoute() : DirectionsRoute {
  // Only show the first leg of the route
  val firstLeg = route.legs()?.get(0)

  if (firstLeg != null) {

      val pointsInFirstLeg: List<Point> =
          firstLeg
              .steps()
              ?.mapNotNull { step -> step.geometry() }
              ?.flatMap { stepGeometry ->
                  LineString.fromPolyline(stepGeometry, 6).coordinates()
              }
              ?: listOf()

      val firstLegPolyline =
          LineString.fromLngLats(pointsInFirstLeg).toPolyline(6)

      return route.toBuilder().apply {
          // Only use data from first leg
          legs(listOf(firstLeg))
          geometry(firstLegPolyline)
          firstLeg.distance()?.let { distance(it) }
          firstLeg.duration()?.let { duration(it) }
      }.build()
  }
}

...

fun onRouteUpdate(newRoute : DirectionsRoute){

    MapboxNavigationProvider.retrieve().setRoutes(listOf(newRoute))

    val route = getRouteForRouteLine(newRoute)

    routeLineAPI.setRoutes(listOf(RouteLine(route, null)))?.apply {
        com.mapbox.navigation.ui.utils.internal.ifNonNull(routeLineView,
            mapboxMap.getStyle()) { view, style ->
            view.renderRouteDrawData(style, this)
        }
    }
    
    viewportDataSource.onRouteChanged(newRoute)

 }
```

A lot has been omitted, but hopefully you get the idea.

**Comment by sandyscoffable** [comment]
I appreciate there might be other ways to solve the route line problem (e.g styling etc) but I couldn't find any good examples to do that.

**Comment by sandyscoffable** [comment]
With the above code in place, it would reliably crash. I changed the route line api to use the directionsRoute unchanged and it doesn't crash. So my code (as per above) has caused the crash.

**Comment by sandyscoffable** [comment]
I'll leave it as the full route for now in my application, but it'll need to find a way to make the route clearer (perhaps using a gradientline or whatever) as it was difficult to see where to go when driving. This is exasperated by the wrong turn icons occasionally being shown (there's a different issue raised for that one)

**Comment by cafesilencio** [comment]
@sandyscoffable I want to get a clear idea of what you're tying to accomplish before going forward.  It sounds like if you have a route with multiple way points you want to only show (for example) the part of the route line from the origin to the first waypoint.  If that's correct is this intended for just the initial route overview or during active navigation as well such that after reaching the first waypoint the view of the line then changes so that it would show only the part of the line from the first waypoint to the second waypoint and so on until the end of the route?

**Comment by sandyscoffable** [comment]
Hi, to give you a bit of context I'm building an app for delivery drivers, where they may have up to 10 stops on their route.

- The route overview will show the route line going via all the waypoints
- When navigating, the route line will only be shown to the next waypoint (so it's clearer for the driver to see where they are going - we've had confusion in testing when there are e.g overlapping lines etc etc, with only showing one leg that's less likely to happen)

You might think "Why not just request a new route for each delivery?" ... well, the whole route is sent to a backend to give consumers that aren't next a real time overview of where the driver is and how long they can expect their delivery to be (hence the whole route is required)

**Comment by sandyscoffable** [comment]
Like I say earlier, there might be a way to deal with this via styling e.g leg to the next waypoint = solid blue, subsequent legs = grey with a bit of alpha

**Comment by sandyscoffable** [comment]
I managed to get a screenshot of this earlier today. The example in the screenshot isn't _too_ bad in this case, given the presence of the route arrow etc, however we have some fairly huge roundabouts around here and it's really not clear where to go if they are solid blue.
<img src="https://user-images.githubusercontent.com/20515901/115396906-69cfc300-a1dd-11eb-8b1d-a93936b78198.png" width="320" />

**Comment by cafesilencio** [comment]
A quick comment regarding your post above. The API supports displaying multiple arrows. Have a look at our [example](https://github.com/mapbox/mapbox-navigation-android/blob/main/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxMultipleArrowActivity.kt) to see how this works.

I can't say if displaying multiple arrows satisfies your use case entirely but it may be useful to you.  I'll add an additional post with a more direct response to your original post.

**Comment by cafesilencio** [comment]
It's expected that the route line API class has the same route reference that the rest of the navigation SDK is using. So your previous attempt to use one route for the core navigation and another route for displaying on the map isn't supported. Although you could always create your own class for displaying the route line this would be a significant amount of work so I"m going express an idea I have for accomplishing what you've described using the Mapbox route line API.  

One idea I have to facilitate your use case is to apply a [gradient line](https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/) to the map layers hosting the route line. This is the feature used in the Navigation SDK for what we call the "vanishing" route line which changes the color of the line behind the puck during active navigation (and for displaying traffic congestion).  You could calculate your own gradient line expression which alters the appearance of the route line based on the way points such that the active leg would be visible and the other legs of the route could appear either transparent or a different color. As the driver reaches one waypoint and begins the next leg you recalculate the gradient line expression and apply it to the route line layers, updating the appearance.  The Navigation SDK doesn't have this feature out of the box. I"ll provide some information regarding how to do this.

The gradient line will apply different coloring based on percentages of the line rather than distances. So you can create an expression that colors the first 25% of the line red and the rest blue for example.  The traffic indications on the route line and the vanishing route line display using this. So if it's determined that from point B to point C the traffic congestion level is moderate there is a calculation to figure out what percent of the line is represented at point B and point C and there is an entry in the expression to indicate a specific color should be used at that part of the line. Similarly the vanishing route line determines what percent of the route has been traveled at any given moment during navigation and creates an expression that colors the line from the origin to that point and leaves the other traffic related parts of the expression alone.

The route lines exist on layers on the map. There's nothing stopping you from calculating your own expressions and applying them to the appropriate layers overriding what the Mapbox API is setting.  You'd still get most of the benefits of using the route line API. You'd want to disable the vanishing route line feature in this scenario because it would overrite your expression constantly during navigation. Also, using your own line gradient expression would over write the traffic congestion indications which may or may not be an issue for your use case. I"ll explain how you might go about implementing this. I don't think it will be as complicated as it might sound.

At a high level:
For each waypoint in a route you'd be calculating the percentage of the route line each waypoint represents. As an example you might have a route that has one waypoint at 25% of the total route distance and another waypoint at 78% of the total route distance.

Depending on which leg of the route you wanted visible you'd create a gradient line expression that colored that leg with some color and the other leg(s) another color (or transparent). You'd then apply that expression to the appropriate map layers.

During navigation you'd have to update the layers with a new expression as the driver moved from one leg to another. A route progress observer will bee necessary to accomplish this.

The route line consists of 3 lines on 3 layers. The bottom line is called the casing line and it gives the appearance of a black (by default) border. The next line is the main route line and sits on top of the casing line. It's blue by default. The top most line is the traffic line which displays the traffic congestion using a gradient line.

For what you are trying to accomplish you would create one gradient line expression and apply it to all three layers.

The details:
A route has an overall distance and each leg has a distance. Using these values you can calculate the percentage of the route line each leg represents.  So if you have a route that is 100 meters with the first leg distance being 25 meters and the second leg being 75 meters you would create an expression that starts with the first 25% being one color and the rest being another color (or transparent). When you detect the driver has reached the first waypoint you'd create a new line gradient expression that made the first 25% of the line transparent (for example) and the rest of the line some other color. 

Look at at [this method](https://github.com/mapbox/mapbox-navigation-android/blob/772fef695aaaf63e5358f7c2acba4c4926b58523/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt#L114) to see how we create these expressions internally in the SDK. 

Upon creating the appropriate expression the next step is to apply it to the appropriate map layers hosting the route lines.
See [this example](https://github.com/mapbox/mapbox-navigation-android/blob/772fef695aaaf63e5358f7c2acba4c4926b58523/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt#L346) for how the gradient is applied to the map layers.

You'll need to apply the expression to three layers to effect the three route lines described above. Those layerIds are: RouteLayerConstants.PRIMARY_ROUTE_TRAFFIC_LAYER_ID, RouteLayerConstants.PRIMARY_ROUTE_LAYER_ID and RouteLayerConstants.PRIMARY_ROUTE_CASING_LAYER_ID.

Reminder the vanishing route line feature should be disabled.

I believe your use case calls for showing the entire route overview before navigation begins so you'll need to register a route progress observer in your activity or fragment and during navigation determine which leg the driver is on and create an expression that visually represents the leg the driver is on. As the current route leg changes, you'll want to create a new expression and apply it. 

I hope I didn't throw too much information at you. One additional thing to note is that there's a slight difference between calculating the leg distance percentages and the way distances are projected on the map.  What I"ve described should be accurate enough and the discrepancy probably won't be noticed but if you need a more accurate way of calculating the distance percentages, comment in this ticket and I'll point you to some code that is more complex but more accurate.  I doubt it will be needed for your use case.

**Comment by sandyscoffable** [comment]
Thank you very much for your comprehensive answer. I'll add this to my TODO list. 

I had identified a Gradient line as one of the potential options but I wasn't entirely sure about it as:
1. it seemed to take values e.g X% of the way along the line (and I at the time wondered if this would need to be recalculated for every move of the puck perhaps reducing performance?). But I expect the route line is generated once and it doesn't need to be recalculated until the route changes.
2. I couldn't find any Android examples that I could rip off 😂 

Thanks again for your help ... like I say I've added it to my list, and I'll give it a try.

**Comment by sandyscoffable** [comment]
I'll close this issue to get it off your list, since the problem is mine.

**Comment by sandyscoffable** [comment]
> You'd want to disable the vanishing route line feature in this scenario because it would overrite your expression constantly during navigation

Dammit, I'm using that, so I'd have to pull whatever that's doing over into the expression (although I expect there is more to it than that).

I guess what I was kinda hoping for was the Mapbox navigation SDK allowing something like:
```
 .routeLineColourActiveLeg(R.color.activeLegColor)
 .routeLineColourSubsequentLegs(R.color.subsequentLegs)
```

I guess internally, the Mapbox SDK could then decide to use a solid line or a gradient line based on whether those two colours are the same?

**Comment by sandyscoffable** [comment]
We had a chat about it this morning. I think we're going to ditch the vanishing route line feature (which is just a nice-to-have) and implement the gradient line, as being able to see and understand where you're going is a key feature of the navigation component of the app.

**Comment by LukasPaczos** [comment]
@sandyscoffable it feels to me like a valid problem that an SDK could help solve in the future. Would you be able to cut a feature request ticket for being able to style route legs differently on the map (with a possibility to make them transparent as well)?

cc @jyrigo @AhmerKhan1

**Comment by sandyscoffable** [comment]
@LukasPaczos - sure. How should I raise the feature request? Raise a new issue?

**Comment by LukasPaczos** [comment]
Yes, just create a new issue, thank you!

**Comment by sandyscoffable** [comment]
To anyone who wants to do the same thing, I achieved it via the following code (it's taken me a few hours to do this due to lack of examples, unfamiliar syntax, I was setting the gradient on the wrong line, and it needs to be set after the routeLineView  has been set).

```kotlin

routeLineView.renderRouteDrawData(style, ...)

...

val totalDistance = newRoute.distance()
val firstLegDistance = newRoute.legs()?.get(0)?.distance() ?: newRoute.distance()

val firstLegPc = firstLegDistance / totalDistance

val lineBlue: Int = resources.getColor(R.color.line_blue, null)
val lineBlueCasing: Int = resources.getColor(R.color.line_blue_casing, null)

val lineGrey = resources.getColor(R.color.line_grey, null)
val lineGreyCasing = resources.getColor(R.color.line_grey_casing, null)

mapboxMap.getStyle()?.let {
  it.getLayerAs<LineLayer>(PRIMARY_ROUTE_LAYER_ID).apply {
      lineGradient(lineGradientExpression(lineBlue, lineGrey))
  }

  it.getLayerAs<LineLayer>(PRIMARY_ROUTE_TRAFFIC_LAYER_ID).apply {
      lineGradient(lineGradientExpression(lineBlue, lineGrey))
  }

  it.getLayerAs<LineLayer>(PRIMARY_ROUTE_CASING_LAYER_ID).apply {
      lineGradient(lineGradientExpression(lineBlueCasing, lineGreyCasing))
  }
}

fun lineGradientExpression(firstLegColor: Int, remainderColor: Int) =
  interpolate {
      linear()
      lineProgress()
      stop {
          literal(0.0)
          color(firstLegColor)
      }
      stop {
          literal(firstLegPc)
          color(firstLegColor)
      }
      stop {
          literal(firstLegPc + 0.00001)
          color(remainderColor)
      }
      stop {
          literal(1.0)
          color(remainderColor)
      }
  }

```

<img width="480" src="https://user-images.githubusercontent.com/20515901/115740669-f8cc0f00-a386-11eb-9d4d-d42525de8833.png" />

To anyone who reads this, the line styles need to be set _**after**_ the `renderRouteDrawData` call, as that nukes any styles set on the line.

**Comment by cafesilencio** [comment]
> NOTE AGAIN: The line styles need to be set after the renderRouteDrawData call, as that nukes any existing styles set on the line.

This can be done by calling MapboxRouteLineVuew::initializeLayers before calling render if that better fits the flow of your app.

**Comment by sandyscoffable** [comment]
Note that there is a bug in the function I provided above in the case there is only one leg. This fixes it:
```kotlin
fun lineGradientExpression(firstLegColor: Int, remainderColor: Int) =
    interpolate {
        linear()
        lineProgress()
        stop {
            literal(0.0)
            color(firstLegColor)
        }
        stop {
            literal(firstLegPc)
            color(firstLegColor)
        }
        if(firstLegPc < 1.0) {
            stop {
                literal(firstLegPc + 0.00001)
                color(remainderColor)
            }
            stop {
                literal(1.0)
                color(remainderColor)
            }
        }
    }
```
