### ISSUE TITLE
[Support][Android] Custom turn by turn navigation

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-navigation-android#432]
Guys,

I'd like to implement my custom navigation view. Right now I'm using 0.7.0 snapshot. I guess I should based on `NavigationView` class and I have few question/issues.

As far as I see I have to implement my own `NavigationPresenter` what seems to be clear, but do you have any plans to allow using your view models like:
* `LocationViewModel`
* `RouteViewModel`
* `NavigationViewModel`

Some of methods from those classes aren't public so it's impossible to use it without cloning  - If I do it in that way I have to care about all updates, etc.

Right now my idea is to copy all required classes - is it the right way? Maybe there is another, better way to achieve that? Any suggestions or information about future plans?

Probably there is also a service responsible for navigation in background - would it be possible to use it?

I'll appreciate any suggestion related to this issue.

**Comment by cammace** [comment]
Our plans are to gradually make the UI part of the SDK more modular as you mention, making the different views available to users rather than an entire activity or view like it's current state. We don't have any specific timeline for this though and for now, as you suggest, copying the classes or using them as reference are your best options. 

We are tracking the splitting up of the views internally and you'll see tickets open here and there when we are about to start the process. Closing this ticket since we have nothing actionable here.
