### ISSUE TITLE
Could not resolve com.mapbox.navigator:mapbox-navigation-native:16.0.0

### ISSUE THREAD

**Issue by SumedhShriram** [mapbox/mapbox-navigation-android#4345]
**Mapbox Navigation SDK version:** 0.43.0

### Steps to trigger behavior

 1. Add the following code snippet to your project-level build.gradle file:
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.43.0-SNAPSHOT'
}
 2. Sync Gradle

### Expected behavior
Gradle Sync Successful

### Actual behavior
1. Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:16.0.0.
2. Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:16.0.0.
3. Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:16.0.0.

**Comment by LukasPaczos** [comment]
Hey @SumedhShriram, unfortunately, the `v0.x` versions of the Navigation SDKs are not supported anymore. Please check out https://docs.mapbox.com/android/navigation/guides/ and our migration guides in the wiki - https://github.com/mapbox/mapbox-navigation-android/wiki.

The error that you're running into is probably caused by the sunsetting of Bintray, where we used to host our artifacts - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.
