### ISSUE TITLE
Add routeline traffic update

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#4410]
Setting routes in the route line API is an expensive operation. Having a method that just updates the traffic would be useful for cases like route refresh. 

This ticket is to add a feature in the route line API that would update just the traffic data for a route.

**Android API:**
**Mapbox Navigation SDK version:**

**Comment by cafesilencio** [comment]
There's a differing opinion that setRoutes() should do the work of determining if the primary route has changed an if it hasn't the route line class should just update the traffic data as needed and not reset the vanishing point and other state that need not change. 

There were also other parties that wanted to discuss a strategy before settling on an implementation.

cc @LukasPaczos @zugaldia

**Comment by zugaldia** [comment]
> There's a differing opinion that setRoutes() should do the work of determining if the primary route has changed an if it hasn't the route line class should just update the traffic data as needed and not reset the vanishing point and other state that need not change.

This is the feedback I got from a customer to improve the performance of the method by only updating the part that is needed (and to avoid any route flashes). A suggestion was a method parameter boolean (`updateTrafficOnly`) or a similar mechanism.

@1ec5 @MaximAlien How does this work today on iOS?

**Comment by LukasPaczos** [comment]
Thanks for cutting the ticket @cafesilencio!

In my opinion, the Route Line APIs should not reset the internal state if the same route is provided twice via `setRoutes`. If the route is the same and the only difference are the annotations (like congestion or restrictions), only the visual representation of the annotations should be updated. The internals of the Route Line APIs should be as efficient as possible and avoid duplicate work when it's unnecessary instead of pushing the responsibility of recognizing and handling that to the developer (via a separate method or boolean flag), this would just increase the chance of misusing the APIs.

Developers do know that passing a `RouteProgress` via `updateWithRouteProgress` and passing the puck position update via `updateTraveledRouteLine` are impacting the state of the line. If the same route is provided twice and those progress variables are already in place, the Route Line APIs should take them into account. This would be the most straightforward way to integrate for developers, that's why I think it should be our default behavior.

Based on that I'd suggest the below changes:
- Do not reset the state if the provided route is the same (based on ID and/or maneuvers) as the one already used. See the internal `isSameRoute` extension that could be used here.
- Reset state only if the route is different than the one already used. It feels natural that if the route is different, the progress is invalidated.
- Expose a `clearProgress` (or similar) API for the use cases where developers would actually like to reset the state of the currently used route. This is a much rarer use case and shouldn't be the default.

I'd also love to learn how this is handled on iOS!

**Comment by LukasPaczos** [comment]
cc @dudeuter

**Comment by cafesilencio** [comment]
> Expose a clearProgress (or similar)

There is already a clearRouteLine() that will reset the state of the class.
