### ISSUE TITLE
V10 import a 3D object onto Android SDK?

### ISSUE THREAD

**Issue by NickLambert95** [mapbox/mapbox-navigation-android#4502]
I was told in another thread by a Mapbox team member that V10.0 added support for 3D models (like GLTF's) for both native Android and iOS SDK's. I am having trouble finding the documentation for both platforms that showcases an example of how this is actually supposed to be done. 

This is the closest I could find for iOS: https://github.com/mapbox/mapbox-maps-ios/pull/154

I cannot find anything like this for Android. Does anyone know where I can find it?

**Comment by NickLambert95** [comment]
@tobrun @chloekraw

**Comment by astojilj** [comment]
@NickLambert95 

I believe you're looking for LocationPuck3D:
Example code: https://docs.mapbox.com/android/beta/maps/guides/migrate-to-v10/#3d-model-capabilities

There [is an example in mapbox-maps-android](https://github.com/mapbox/mapbox-maps-android/blob/8c50a1ca76a7f49e9f1ca2b4fcc3722ec6133a0d/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt#L119) repository. If you face issues with it, or you're interested in other type of models, please submit them to https://github.com/mapbox/mapbox-maps-android.

Note that LocationPuck3D is developed to be used for 3D model of a vehicle. When placed on terrain, based on current position and bearing (modelRotation[2]), it would be additionally rotated ([pitch and roll](https://en.wikipedia.org/wiki/Six_degrees_of_freedom)) so that it follows terrain slope.

**Comment by NickLambert95** [comment]
@astojilj 
Thanks for getting back to me! The example you listed would only allow me to place a single 3D object (and I can't give it a certain location since it uses my current). Is there another method around this for Android? I'm looking to place several 3D models in different locations

**Comment by astojilj** [comment]
@NickLambert95 
Thanks. I've closed this issue just because of the assumption it is related to LocationPuck3D.
Let's try to clarify requirements for your use case here and eventually open another issue in https://github.com/mapbox/mapbox-maps-android.
We can continue discussion here, no matter that the issue is closed.

For LocationPuck3D, it is possible to specify location https://github.com/mapbox/mapbox-maps-android/blob/5e1a6d358ce7af2783ea226301baa35bf07433fe/plugin-locationcomponent/README.md.


> I'm looking to place several 3D models in different locations

a. How complex are the models (number of vertices)? Could you write OpenGL renderer for it? 
b. Are the objects to be rendered on 2D map view only, or also on terrain? If on terrain, do all of them follow terrain slope e.g. vehicle or behave like buildings?
c. Are objects moving?
d. Are they placed on ground or above the ground?
e. Currently, custom 3D objects could be rendered using LocationPuck3D or [custom layer API](https://github.com/mapbox/mapbox-maps-android/blob/04560145d3558c70c674a3d5fa15636cbb1dbf1c/app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/TriangleCustomLayer.kt). While there are custom layer examples provided with SceneKit on iOS and Three.js on mapbox-gl-js, we have not provided similar example that uses existing framework on Android. Let's visit again what could be done about it.  Could you write OpenGL code for the models or use e.g. [tinygltf example to load and render](https://github.com/syoyo/tinygltf/issues/159)? Or prefer some other 3D framework / engine supported on Android, to use in custom layer?

**Comment by karatuno** [comment]
@astojilj Can custom layer API be used for 3D markers?
