### ISSUE TITLE
Expose native Navigator

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#4584]
Native `Navigator` should be exposed to make it possible to test any new/experimental NN feature.
It allows testing native logic without any changes in SDK API.
It should not be available for all customers.

as a solution we can add a getter marked with `@ExperimentalMapboxNavigationAPI` annotation to `MapboxNavigation` and expose `Navigator`. To use it, customers need to add a separate NN dependency. This changes should not affect regular customers.

Let's discuss how we can implement it.

cc @zugaldia @truburt @mapbox/navigation-android @mapbox/navnative

**Comment by LukasPaczos** [comment]
> as a solution we can add a getter marked with @ExperimentalMapboxNavigationAPI annotation to MapboxNavigation and expose Navigator. To use it, customers need to add a separate NN dependency. This changes should not affect regular customers.

This approach is the easiest to maintain for everyone involved and wouldn't even require Nav SDK bumps, clients could update only Nav Native as long as other elements of the binary (that SDK actually uses) are not breaking. There's a risk here though - there is a little bit of logic in how Nav SDK communicates with Nav Native, for example, we use a dedicated thread for most of the operations, or we sometimes recreate the navigator instance when we go offline/online. Developers would not be able to hook into this thread and there could be small race conditions when they interact with experimental features. The way that they access the features wouldn't be consistent either with the rest of the SDK in general which might cause some friction.

An alternative I can think of is exposing the Nav Native APIs via the SDK as we normally do but without wrapping the data objects. This would still be low maintenance on the SDK, it would offer more familiar access to the features and Nav SDK could schedule the communication between the SDK and Nav Native correctly side. On the other side, it would require Nav SDK bumps to expose new Nav Native features.

Both of the above approaches would require developers to manually declare a dependency on the Nav Native artifact (and keep it in sync with the version that Nav SDK uses) as it's intentionally not exposed by default since we're wrapping all the objects. To avoid this, we would have to wrap every new feature fully as we normally do. We can still tag them as experimental and keep them undocumented and untested which does already significantly decrease maintenance costs.

#### Summary
If the goal is to allow developers to take advantage of new experimental features without them having to be released in the Nav SDK, option 1 is the only option. It does bear the highest risk of possible issues though.

If the above is not a requirement, I'd actually consider option 3, exposing wrapped but untested and undocumented experimental APIs. The usage would be familiar for developers and without having to manage Nav Native dependency manually, while also stable for us internally.

**Comment by kmadsen** [comment]
Adding a couple issues to consider because I think they are potential blockers. 

**How do we handle version SEMVER versioning?** I think the answer is the comments above, create all the api's as experimental and then they are free in minor releases ✅ . But if so, we should state that explicitly to remove confusion.

**What about documentation?** With a public repository, the public source code acts as public documentation. Also, In order to see why something is changing read the release notes. Generating some public release notes would be good.

>  Developers would not be able to hook into this thread and there could be small race conditions when they interact with experimental features.

+1 to the point here. The SDK simplifies navigator interactions. Giving a bi-pass will also complicate the assumptions we get to make. Would we know if someone is reporting an issue with an experimental configuration?

**Comment by LukasPaczos** [comment]
The change actually already landed in https://github.com/mapbox/mapbox-navigation-android/pull/4669. @kmadsen wanna give it a pass and see if you think we should follow up on the setup?
