### ISSUE TITLE
How can I set location Engine to start simulation?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#4593]
The first time, I don't want to start simulation, so I don't set location engine in my NavigationOptions.
```
      NavigationOptions navigationOptions = new NavigationOptions.Builder(getContext())
                .accessToken(token)
                //.locationEngine(new ReplayLocationEngine(mapboxReplayer))
                .build();
     mapboxNavigation = new MapboxNavigation(navigationOptions);
```

The Second route, I want to start simulation, how can I set location Engine?

**Mapbox Navigation SDK version:**
com.mapbox.navigation:android:2.0.0-beta.17

**Comment by cafesilencio** [comment]
It's not clear to me exactly what your use case is.  I suggest setting the location engine rather than commenting it out like you have in the code snippet you provided.

The routes should be controlled by calling `MapboxNavigation::setRoutes` for the core navigation system. The simulator has methods to start and stop the simulation as well as methods to change the route.  See this example [here](https://github.com/mapbox/mapbox-navigation-android/blob/ea5c220eb7205a883c0b1b3b091c738d2df108d2/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt#L438) for some hints in controlling the simulator.  

If this isn't helpful please elaborate on your use case so we can better understand what you're tying to accomplish.

**Comment by KayHung** [comment]
@cafesilencio 
This example [here](https://github.com/mapbox/mapbox-navigation-android/blob/main/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt), it's not simulate the route.
How can I simulate the route when I already initialization mapboxNavigation

**Comment by LukasPaczos** [comment]
This is not supported as of today (please correct me if I'm wrong @kmadsen) - you need to recreate the `MapboxNavigation` objects between running a simulated and real route. Is recreating the `MapboxNavigation` not possible in your use case @KayHung? Tagging this as a feature request for now.

**Comment by Guardiola31337** [comment]
Hey @KayHung any updates here?

**Comment by KayHung** [comment]
@Guardiola31337 
I see this issue https://github.com/mapbox/mapbox-navigation-android/issues/4766
I think that is I want.

**Comment by Guardiola31337** [comment]
Thanks for the follow-up @KayHung 

If that's the case, I'm going to close here, we can keep discussing in https://github.com/mapbox/mapbox-navigation-android/issues/4766

Thanks again!
