### ISSUE TITLE
How can I setFormatter in MapboxManeuverApi?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#4595]
I want to change the formatter dynamically, 
I found MapboxTripProgressApi has setFormatter function,
`mapboxTripProgressApi.setFormatter(tripProgressFormatter());`

But I can't found the same function in MapboxManeuverApi, so how can I setFormatter in MapboxManeuverApi dynamically?

**Mapbox Navigation SDK version:**
com.mapbox.navigation:android:2.0.0-beta.17

**Comment by cafesilencio** [comment]
@abhishek1508 Is there any reason a `setFormatter` method couldn't be added to the `MapboxManeuverApi`

**Comment by abhishek1508** [comment]
@KayHung I would like to understand the use case for the SDK exposing `setFormatter`. Currently we already expose this API that allows you to set the formatter in `MapboxManeuverApi`

```
private val formatterOptions: DistanceFormatterOptions by lazy {
    DistanceFormatterOptions.Builder(applicationContext).build()
}

private val maneuverApi: MapboxManeuverApi by lazy {
    MapboxManeuverApi(MapboxDistanceFormatter(formatterOptions))
    // or
    MapboxManeuverApi(YourDistanceFormatter)
}
```

Once you do the above, there shouldn't be any need for `setFormatter` unless you would want to change the formatter again at runtime which I would like to understand the use for.

**Comment by KayHung** [comment]
@abhishek1508 
I want to change the formatter after maneuverApi initial

**Comment by LukasPaczos** [comment]
@KayHung is recreating the `MapboxManeuverApi` not possible in your use case?

**Comment by KayHung** [comment]
@LukasPaczos 
Now, I just recreated the MapboxManeuverApi.
If I do it constantly,  is there any problem with my app?

**Comment by LukasPaczos** [comment]
You shouldn't see any problems but the performance and bandwidth usage might suffer since you won't be able to benefit from the cached state every time you recreate the object. I'd rather recommend implementing a custom `DistanceFormatter` with some mutable state that formats inputs differently depending on an external factor, and pass it once to the Maneuver API. Then, you can change the formatter's behavior and redraw the data whenever needed.

I'm going to go ahead and close here as we're not planning to make the formatter mutable directly in the Maneuver API at the moment.

**Comment by KayHung** [comment]
@LukasPaczos 

>  I'd rather recommend implementing a custom DistanceFormatter with some mutable state that formats inputs differently depending on an external factor, and pass it once to the Maneuver API. Then, you can change the formatter's behavior and redraw the data whenever needed.

I will try this way. Thanks you.
