### ISSUE TITLE
Refactor Building API

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#4696]
The aim of this ticket is to open a discussion to refactor `MapboxBuildingArrivalApi` and `MapboxBuildingHighlightApi`. `MapboxBuildingArrivalApi` is nothing but a wrapper around `MapboxBuildingHighlightApi` that hooks onto the `ArrivalObserver`. Even though it is easy for the end user to not register/unregister to the observer, this opens doors to more bugs which our UI components have suffered from in pre v2.0. As a side effect of hooking onto the observer the `mapboxNavigation` state has to be propagated to this wrapper which can potentially cause leaks in different use cases. With the existing building api, it's also unclear when to use `MapboxBuildingHighlightApi` and `MapboxBuildingArrivalApi` and what use case does each API fulfill.

I propose to expose only one class `MapboxBuildingApi` that would have the following signatures:
```
// Given a point, this API would highlight a building
fun highlightBuilding(point: Point, mapboxMap: MapboxMap)

// The API extrudes all buildings by adding extrusion layer to [MapboxMap]
fun enableBuildingExtrusions(mapboxMap: MapboxMap)

// The API removes the extrusion layer and source from [MapboxMap]
fun disableBuildingExtrusions(mapboxMap: MapboxMap)

// The API removes the building layer and source from [MapboxMap]
fun removeBuildingLayer(mapboxMap: MapboxMap)

<!-- 
I would like to discuss more on this particular API below if we should expose it. 
Exposing something like this takes away extra lines developer would have to write in 
their activity to pass in a point to the API above. 
-->

// Given routeProgress the API would highlight a building onWaypointArrival and onFinalDestinationArrival
fun highlightBuildingDestination(routeProgress: RouteProgress, mapboxMap: MapboxMap, isFinalDestination: Boolean)

For ex: if not for this API and you want to highlight a building on waypoint you would have to do the following:
override fun onWaypointArrival(routeProgress: RouteProgress) {
    val routeOptions = routeProgress.route.routeOptions()
    val coordinateIndex = routeProgress.currentLegProgress?.legIndex!! + 1
    routeOptions?.coordinatesList()?.get(coordinateIndex)?.let { point ->
        mapboxBuildingApi.highlightBuilding(point, mapboxMap)
    }
}

override fun onFinalDestinationArrival(routeProgress: RouteProgress) {
    val point = routeProgress.route.routeOptions()?.coordinatesList()?.lastOrNull()
    mapboxBuildingApi.highlightBuilding(point, mapboxMap)
}

<!-- With above API we can do all of it for the developer and all they would have to do is -->
override fun onWaypointArrival(routeProgress: RouteProgress) {
    mapboxBuildingApi.highlightBuildingDestination(routeProgress, mapboxMap, false)
}

override fun onFinalDestinationArrival(routeProgress: RouteProgress) {
    mapboxBuildingApi.highlightBuildingDestination(routeProgress, mapboxMap, true)
}
``` 
The only state this class would maintain is a list of buildings that are highlighted. It is needed if a user don't want to apply extrusion to an already highlighted building

The above mentioned API's are enough to be able to 
- Highlight a building when a user clicks on it
- Highlight destination building when user reaches the waypoint
- Highlight destination building when user reaches the final destination
- Un-highlight already highlighted building when user starts the next leg in a multi leg route
- Extrude all buildings 
- Extrude all building except the building that is highlighted
- Un-extrude all buildings

The `MapboxBuildingApi` proposed doesn't need any callback `BuildingHighlightObserver` as is currently required by `MapboxBuildingHighlightApi`. I still don't understand the use case behind this callback and how can it be useful. It could definitely be exposed if we can identify some use cases for it.

/cc @LukasPaczos @Guardiola31337 @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
As long as we can still do the same things that we could before these API improvements look good to me 👍 

@kmadsen as you originally worked on this, do you have any objections? Maybe you can clarify 👇 

> The `MapboxBuildingApi` proposed doesn't need any callback `BuildingHighlightObserver` as is currently required by `MapboxBuildingHighlightApi`. I still don't understand the use case behind this callback and how can it be useful. It could definitely be exposed if we can identify some use cases for it.

**Comment by kmadsen** [comment]
Thanks for cutting this ticket! Excited to see the interest in the API. I am in favor of "Simplifying the api with a single class". But consider a couple other discussion points - because I don't think the proposed interface is exactly what we want. 

### Who handles all-building extrusions?
```
// The API extrudes all buildings by adding extrusion layer to [MapboxMap]
fun enableBuildingExtrusions(mapboxMap: MapboxMap)

// The API removes the extrusion layer and source from [MapboxMap]
fun disableBuildingExtrusions(mapboxMap: MapboxMap)

// The API removes the building layer and source from [MapboxMap]
fun removeBuildingLayer(mapboxMap: MapboxMap)
```
Putting all building extrusions under one interface was the original design decision. When we discussed this, we declared "building extrusions" a map problem not a navigation problem. So we pulled it out and exposed the "arrival building" information. See discussion here https://github.com/mapbox/mapbox-navigation-android/pull/4420#discussion_r639627274

### Finding the arrival building

Something else we discussed offline is an issue with highlighting the actual buildings upon arrival. For example, our api takes route progress and uses a point on the map to query for building features. The priority, should be a routable location, but we also want to have a building location. If we create routable points that are building centers, we will have ambiguous routable locations (think about NYC where a building is in-between two roads) 

``` kotlin
override fun onFinalDestinationArrival(routeProgress: RouteProgress) {
    val point = routeProgress.route.routeOptions()?.coordinatesList()?.lastOrNull()
    mapboxBuildingApi.highlightBuilding(point, mapboxMap)
}
```

### Simplifying the api with a single class

Right now there are two apis
- MapboxBuildingArrivalApi
- MapboxBuildingHighlightApi

Taking this functionality and wrapping it under one api `MapboxBuildingApi`. Could be a good refactor where we cut and expose the functions of a "flattened" file. I'm not opposed to this direction, I originally considered them separate concerns. But the current suggestion has new conclusions on the "Who handles all-building extrusions?" discussion.

**Comment by abhishek1508** [comment]
Thanks @kmadsen and @Guardiola31337  for taking a look at it. 
It's unfortunate that we don't have a product req specified that would talk about use cases. So the API proposal was put forth looking at the existing capabilities as it exists today.

> Putting all building extrusions under one interface was the original design decision. When we discussed this, we declared "building extrusions" a map problem not a navigation problem. So we pulled it out and exposed the "arrival building" information. See discussion here #4420 (comment)

I totally agree on this. Extruding a building shouldn't be a concern of the Navigation SDK and we can point the developers to appropriate Maps documentation on how to do it.

> Something else we discussed offline is an issue with highlighting the actual buildings upon arrival. For example, our api takes route progress and uses a point on the map to query for building features. The priority, should be a routable location, but we also want to have a building location. If we create routable points that are building centers, we will have ambiguous routable locations (think about NYC where a building is in-between two roads)

I don't think this is a problem for the API. All the API needs access to is a `Point`, no matter if it comes directly from the user or the SDK derives it from `RouteProgress`. We should have clear documentation stating that the building will only highlight upon arrival if the `Point` associated is a building location and not a routable location. If the user selects a building location while making a route request the API would work. We can fairly say that this is one of the limitations at the moment. Iteratively, we can try to find some solution that can highlight a building closest to the routable location and that way we won't have that limitation. This change would be internal so there are no concerns of breaking SEMVER as well.

> Taking this functionality and wrapping it under one api MapboxBuildingApi. Could be a good refactor where we cut and expose the functions of a "flattened" file. I'm not opposed to this direction, I originally considered them separate concerns. But the current suggestion has new conclusions on the "Who handles all-building extrusions?" discussion.

I still hold by my proposal to have just 1 class `MapboxBuildingApi` that has the following signatures:

```
// Given a point, this API would highlight a building
fun highlightBuilding(point: Point, mapboxMap: MapboxMap)

// Given routeProgress the API would highlight a building onWaypointArrival and onFinalDestinationArrival
fun highlightBuilding(routeProgress: RouteProgress, mapboxMap: MapboxMap, isFinalDestination: Boolean)
```

**Comment by kmadsen** [comment]
Ok in agreement for all-building-extrusions 👍 . Also I'm okay with making the "finding the arrival building" a separate issue. But I think that is an issue worth escalating; it involves directions api, ios, maybe nav-native..

> I still hold by my proposal to have just 1 class MapboxBuildingApi that has the following signatures:
```
// Given a point, this API would highlight a building
fun highlightBuilding(point: Point, mapboxMap: MapboxMap)

// Given routeProgress the API would highlight a building onWaypointArrival and onFinalDestinationArrival
fun highlightBuilding(routeProgress: RouteProgress, mapboxMap: MapboxMap, isFinalDestination: Boolean)
```

proposal understood 👍 . Also think the functions are worth discussing.

The current function provides a callback, because otherwise there is no way of knowing if a building was actually highlighted. Is that handled somewhere else? Below is the current api
``` kotlin
fun highlightBuilding(
        point: Point?,
        callback: BuildingHighlightObserver
    ) {
```

Also, I don't like having to pass the `MapboxMap` into every building highlight function. Are we going to do that everywhere? Maybe we want to make extensions for this rather than passing it as an argument? I would rather be able to pass new options for how the building look and feel. For example:

``` kotlin
    fun highlightBuilding(
        point: Point?,
        options: MapboxBuildingHighlightOptions,
        callback: BuildingHighlightObserver
    ) {
```

Another question, how do you clear the current building that is highlighted? We could create a separate function. But as it is now, it is to pass null

https://github.com/mapbox/mapbox-navigation-android/blob/f1340d2dcb612faa329221d4855d48e5f8c480db/libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingArrivalApiTest.kt#L91

**Comment by abhishek1508** [comment]
@kmadsen All the points mentioned makes complete sense. My idea was just to float the API signatures so we could have a discussion, but main intention was to agree if we need to have 2 classes, depend on `mapboxNavigation` and hook onto arrival observers vs removing it and using only 1 API class. Will work on it and we can further discuss in the PR.

**Comment by zugaldia** [comment]
Adding to the RC milestone in anticipation of potential breaking API changes.
