### ISSUE TITLE
No lane icon available for left right

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4737]
**Mapbox Navigation SDK version:** v2.0.0-beta.23

```
 Unrecognized lane LaneIndicator(isActive=true, directions=[left, right]) activeDirection: left
```

[There is no mapping for directions [left,right]](https://github.com/mapbox/mapbox-navigation-android/blob/4f69845366407d6b4ae616c5cca28b0379ca5cfc/libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/LaneIconProcessor.kt#L78-L143) But this is coming from directions api.

**Comment by kmadsen** [comment]
cc: @abhishek1508 do we have a list of icons that need to be created?

**Comment by LukasPaczos** [comment]
This is going to be resolved with the integration of https://github.com/mapbox/navigation-ui-resources/issues/23.

**Comment by 1ec5** [comment]
To clarify, mapbox/navigation-ui-resources#21 added an asset for left+right. mapbox/navigation-ui-resources#23 will fill some gaps in the naming scheme so that the SDK doesn’t need to account for as many theoretical edge cases, but the opposite-turn assets will remain essentially untouched because there are fewer possible situations that would call for them.
