### ISSUE TITLE
Missing information about a route in `RoutesObserver`

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#4776]
`RoutesObserver` does not consist of info about where routes come from(like rerouting or refresh route)

This is a proposal to change `RoutesObserver` interface, this helps us(as an instance in NavTelemerty we make an assumption that after off-route next route that NavTelemetry catches is come from re-route, but we cannot be sure) and customers understand more about why new routes are spread via `RoutesObserver`

```kotlin
const val ROUTES_CHANGE_REASON_NEW_ROUTES = "ROUTES_CHANGE_REASON_NEW_ROUTES"
const val ROUTES_CHANGE_REASON_REFRESH = "ROUTES_CHANGE_REASON_REFRESH"
const val ROUTES_CHANGE_REASON_REROUTE = "ROUTES_CHANGE_REASON_REROUTE"

@StringDef(
    ROUTES_CHANGE_REASON_NEW,
    ROUTES_CHANGE_REASON_REFRESH,
    ROUTES_CHANGE_REASON_REROUTE
)
annotation class RouteChangerReason

fun interface RoutesObserver {
    fun onRoutesChanged(routes: List<DirectionsRoute>, @RouteChangerReason reason: String)
}
```

it also requires changing `MapboxNavigation` API:
```kotlin
@JvmOverloads
fun setRoutes(routes: List<DirectionsRoute>, @RouteChangerReason reason: String = ROUTES_CHANGE_REASON_NEW_ROUTES) 
```
bonus extensions
```kotlin
fun MapboxNavigation.reroute(routes: List<DirectionsRoute>) {
  setRoutes(routes, ROUTES_CHANGE_REASON_REROUTE)
}

fun MapboxNavigation.refreshRoutes(routes: List<DirectionsRoute>) {
  setRoutes(routes, ROUTES_CHANGE_REASON_REFRESH)
}
```

cc @mapbox/navigation-android @zugaldia @truburt

**Comment by Guardiola31337** [comment]
This reminds me to 😅

https://github.com/mapbox/mapbox-navigation-android/blob/e232efd36700e4f5f3345bd76ad99cb28076bb1e/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L352-L364

Take a look at https://github.com/mapbox/mapbox-navigation-android/pull/1819

I'm onboard with the changes suggested (we can work on naming later). I have a question though, how does this will impact the upcoming work on integrating NN's Hybrid Router and Alternatives? cc @korshaknn

**Comment by LukasPaczos** [comment]
I'm in favor of the idea as well. To expose the most value out of this API, we might want to focus on the type of change, and then the reason for the change instead of bundling this information together.

For example:
```kotlin
fun interface RoutesObserver {
    fun onRoutesChanged(routes: List<DirectionsRoute>, changeOrigin: RoutesChangeOrigin)
}

data class RoutesChangeOrigin(@RoutesChangeType type: String,  @RoutesChangeReason: String) {

  const val TYPE_NEW = "ROUTES_CHANGE_TYPE_NEW"
  const val TYPE_REFRESH = "ROUTES_CHANGE_TYPE_REFRESH"
  @StringDef(
    TYPE_NEW,
    TYPE_REFRESH
  )
  annotation class RoutesChangeType

  const val REASON_REROUTE = "ROUTES_CHANGE_REASON_REROUTE"
  @StringDef(
    REASON_REROUTE
  )
  annotation class RoutesChangeReason
}
```

This gives a clear indication to developers with how they can use this information.
- If the `type` is `NEW`, this means I need to redraw all the waypoint callouts, query for new POIs along the route, etc because I know that the route has significantly changed.
- If the `type` is `REFRESH`, this means I know my geometry and steps have not changed, I can optimize my app and avoid running unnecessary tasks.

Then comes a `reason` which is just additional information on top of what has actually changed in the route.

What do you think?

**Comment by RingerJK** [comment]
I have a few questions:
- if the reason is `REROUTE` then it's always a new route, and `type` is not really helpful. If the type is `REFRESH` then what should be the reason?  if it's null then next point ->
- I'm worrying that it would be hard to handle all possible options if we'll add a few more states to `RoutesChangeType`(X) and `RoutesChangeReason`(Y) that we(and customers) have to handle  X*Y possible combinations. As far as I see some combinations are not possible(like type `REFRESH` and reason `REROUTE`), so it might be lead to non-necessary states check-in and brings additional issues if we'll send(by mistake 😃) a non-compatible type-reason combination

I like the idea that we need more fine-gradient states so I'd suggest a single state with clear naming and well documented when and why each reason might happen. The names might be like 
- NEW_ROUTES
- NEW_ROUTES_REROUTE
- NEW_ROUTES_ALTERNATIVE
- REFRESH_ROUTE

wdyt?

**Comment by LukasPaczos** [comment]
What I was trying to get to is that there are only 2 distinct states that developers care about:
1. There's a new route and they need to rebuild all of their route-based features.
2. There's a refresh and they don't need to do any action unless they use some of the annotations.

This would be described by the `type` and most of the time developers can entirely ignore the `reason`. This would result in 2 logical branches in the integrating code instead of all of the possible combinations.

That said, your proposal looks good to me as well, I think we could move forward with that :+1:

The other point I'd like to debate is the possibility to create reasons. The original proposal mentions introducing:
```kotlin
@JvmOverloads
fun setRoutes(routes: List<DirectionsRoute>, @RouteChangerReason reason: String = ROUTES_CHANGE_REASON_NEW_ROUTES) 
```

We're introducing the reasons because the Nav SDK can mutate the list of routes internally without developers' knowledge, so it makes sense to provide additional information about why the change happened in the `RoutesObserver`. However, that same is not true for `MapboxNavigation#setRoutes`. When developers invoke this method, they already know why, so in my opinion, this should be controlled by the SDK, without developers being able to select a different reason themselves. This gives us more control over the API and because of that we could also rely on the reasons in our internal APIs (like telemetry). If the reason was provided from the outside, we could run into misuse issues.

**Comment by RingerJK** [comment]
yeah, that's a good point! I would also restring providing reason outside, but we already give to external developers option to override `RererouteController`, we also have API to make route-refresh of the route(in `mapbox-java`), a developer might make re-reroute/refresh/alternative route in his own way, so seems it should be an option to provide `reason` outside. 
Another way is to relate invoking `MapboxnNavigation#setRoutes`, it's always NEW_ROUTES, but it's not always true
