### ISSUE TITLE
Merge LocationObserver with MapMatcherResultObserver

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4814]
We currently offer 2 interfaces that provide redundant information. `LocationObserver` was the original implementation and provides only the information about `rawLocation`, `enhancedLocation`, and `keypoints`. During the course of `v1`, we introduced an additional `MapMatcherResultObserver` which next to providing the same information as `LocationObserver` also exposes matching probabilities, speed limits, and other matching information available in the free drive. We added a new interface for backward compatibility.

In my opinion, there's no need for these interfaces to live side-by-side. It only complicates the documentation and examples because while we can start with using `LocationObserver`, at some point for more advanced use-cases we need to migrate to the `MapMatcherResultObserver` anyway. There's no overhead in using `MapMatcherResultObserver` instead of `LocationObserver` so there's no reason for the SDK to maintain both.

I'd like to suggest alternative solutions:
- remove the `LocationObserver` and merge it with the `MapMatcherResultObserver` (potentially come up with a new name?)
- deprecate `LocationObserver` (do not remove it, do not change any names)

Since we're in the RC phase, we still have the opportunity to just go ahead and remove the `LocationObserver` but a deprecation can be a good path as well. I'd love to hear your thoughts @mapbox/navigation-android.

**Comment by abhishek1508** [comment]
That's a good suggestion and less code to understand. I would however, opt for removing LocationObserver because no matter we deprecate or remove, we should update both our examples and documentation to use the recommended approach(MapMatchingOnserver) rather than deprecated approach. Otherwise, we are just promoting users to use the deprecated LocationObserver. Plus as you mentioned since we are in RC it's not that bad that we remove LocationObserver.

**Comment by RingerJK** [comment]
looks like MapMatcherObserver has data about `offRoute`, and along with the above should remove `OffRouteObserver`? It's also not compatible that one might has`offRoute=true`, and another `offRoute=false` 🤔 on what user has to relate on?

**Comment by LukasPaczos** [comment]
@RingerJK the `MapMatcherResult` has information about `isOffRoad`, which is different than `offRoute`.

**Comment by RingerJK** [comment]
yes, my bad, I missed that they're have different meanings 👍

**Comment by Zayankovsky** [comment]
Looks like `MapMatcherResultObserver` currently does not provide information about `rawLocation`, unlike `LocationObserver`. Should we add `onRawLocationChanged` function to `MapMatcherResultObserver`?

**Comment by LukasPaczos** [comment]
Yes :+1: 

Any alternative name ideas, or are we all fine with just using the `MapMatcherResult`?

**Comment by abhishek1508** [comment]
> Yes :+1: 
> 
> Any alternative name ideas, or are we all fine with just using the `MapMatcherResult`?

If we look at the properties that MapMatcher gives access to, all of them are trying to match your location to the road except the speed limit. Keeping that in mind what about `LocationMatcher` instead because MapMatcher feels as if you are trying to match to the Map but rather you are trying to make sure that the user stays on the road. Similarly the observer can be `LocationMatcherObserver`

**Comment by abhishek1508** [comment]
I am reopening this because all the examples in our examples repo needs to be updated after this change is released. This ticket will help in tracking the work.

/cc @LukasPaczos @Zayankovsky

**Comment by LukasPaczos** [comment]
Same goes for the docs pages, @Zayankovsky could you run with that as well?

**Comment by Zayankovsky** [comment]
Sure, I will update both examples and docs pages.
