### ISSUE TITLE
Refresh all routes instead of only the primary one

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4832]
The route refresh controller only refreshes the current primary route.

We should also refresh all alternative routes to be able to continuously surface what's the best alternative.

cc @mapbox/navigation-android

**Comment by VysotskiVadim** [comment]
Directions API can refresh only 1 route per request. It means that if we want to refresh all routes(primary + alternatives) we need to make a few requests. [Link to question about refreshing a few routes per request](https://github.com/mapbox/navigation-sdks/issues/1584#issuecomment-1145719636).

The idea of all routes refresh is that the SDK makes a few parallel request, combine data, and update routes. I'm not sure what to do if one of two route refreshes fails. There are a few possible approaches:

### Refresh what you can refresh
The SDK refreshes the routes it can. I.e. in case of 1 of 2 request failed, only one route will be refreshed.
Pros:
* User gets the freshest data at least for some route.
* 
Cons:
* Data could be inconsistent

### Refresh all or nothing
The SDK doesn't refresh anything until it successfully get fresh data for all routes.
Pros:
* Data is always consistent

Cons:
* User may not get fresh data just because one alternative route failed to refresh. 


## Feedback
@mapbox/navigation-android , what do you think about it? Do you see any other solutions? Do you see any other pros and cons in mentioned above? How would you implemented refresh?

**Comment by VysotskiVadim** [comment]
@AhmerKhan1 , @mapbox/driver-app , what do you think about the question above? ☝️

**Comment by VysotskiVadim** [comment]
TODO:

- [ ] log route index/id when calculating route diff

**Comment by VysotskiVadim** [comment]
PR https://github.com/mapbox/mapbox-navigation-android/pull/5923

**Comment by VysotskiVadim** [comment]
> PR #5923

Landed 🚀
