### ISSUE TITLE
Handle re-routing with continuous route alternatives

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5039]
**Mapbox Navigation SDK version:** 2.1.0

When the driver re-routes onto an alternative route, the experience should be seamless. Also, telemetry should not trigger new departure events. These events should either be `ROUTES_UPDATE_REASON_ALTERNATIVE` or `ROUTES_UPDATE_REASON_REROUTE`

Doing this from the SDK, seems to require changes from nav-native https://github.com/mapbox/mapbox-navigation-native/issues/4410. This issue is to track the changes needed from the SDK

https://user-images.githubusercontent.com/3021882/137554160-5fe4e480-a1fc-4891-ae55-05fe4220cff8.mp4

**Comment by LukasPaczos** [comment]
Capturing from https://github.com/mapbox/mapbox-navigation-native/issues/4410#issuecomment-1010754683, this should now be possible when we switch to native reroute controller.

cc @RingerJK

**Comment by LukasPaczos** [comment]
Nav Native recently started to provide [an alternative route ID in navigator status](https://github.com/mapbox/mapbox-navigation-native/blob/ee256be3b168433c9238488a2450156022f32280/bindings/navigator.mbg#L286-L289) during an off-route event in case the user is turning into an alternative that Nav Native tracks.

This ID is currently the Alternative ID which the [Nav Native team is migrating to a Navigation Route ID](https://github.com/mapbox/mapbox-navigation-native/pull/5535) for easier use on the SDK side. We'll be able to use that ID to immediately switch the route to the alternative instead of making a reroute request.

**Comment by zugaldia** [comment]
> This ID is currently the Alternative ID which the https://github.com/mapbox/mapbox-navigation-native/pull/5535 for easier use on the SDK side.

This work just landed :tada:

**Comment by LukasPaczos** [comment]
Upgrade to the version of Nav Native that contains the necessary changes is in https://github.com/mapbox/mapbox-navigation-android/pull/5587. When this PR lands, we should be able to wire it up to the reroute controller.
