### ISSUE TITLE
Can't start activity with mapbox

### ISSUE THREAD

**Issue by trinhvanminh2009** [mapbox/mapbox-navigation-android#512]
How to resolve this problem?
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;

  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path:

**Comment by trinhvanminh2009** [comment]
Error in this line :`  Mapbox.getInstance(DirectionShipper.this,getString(R.string.mapbox_token));`

**Comment by danesfeder** [comment]
Per our release notes, you will need to compile a `3.X.X` version of the lost location library to resolve this https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.2.0

**Comment by Guardiola31337** [comment]
Hey @trinhvanminh2009 👋 
Are you using Lost? As @danesfeder mentioned per https://github.com/mapbox/mapbox-gl-native/pull/9488 the location provider is optional (we're not including Lost within the SDK anymore) and in https://github.com/mapbox/mapbox-gl-native/pull/10355 we bumped the Lost version to `3.0.4` https://github.com/mapbox/mapbox-gl-native/blob/ffea8e145f5b67bbeb7aec46c77d73b95ef6ea31/platform/android/dependencies.gradle#L23 which is the one that MAS `2.2.9` uses. Bumping to `3.0.4` should do the trick.

BTW, what version of the SDK are you using? I ask because `0.7.0` doesn't include above changes and it should work normally? Could you share your `build.gradle` configuration?

**Comment by trinhvanminh2009** [comment]
@Guardiola31337 Thanks for the support, I'm using 0.7.0. 
`    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'`

**Comment by danesfeder** [comment]
This should be fixed in `0.7.1-SNAPSHOT`, please let us know otherwise.  Thanks!

**Comment by trinhvanminh2009** [comment]
@danesfeder Thanks. Here is everything.
https://github.com/trinhvanminh2009/FindTheShipper/blob/master/app/src/main/java/com/minh/findtheshipper/Shipper/DirectionShipper.java 
I have to comment it, because I can't build it.

**Comment by danesfeder** [comment]
@trinhvanminh2009 https://github.com/trinhvanminh2009/FindTheShipper/blob/master/app/build.gradle#L76-L77 you need to remove line 76, then set line 77 like so:
```
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
        transitive = true
    }
```

**Comment by trinhvanminh2009** [comment]
@danesfeder Thanks, I'll do that.

**Comment by trinhvanminh2009** [comment]
DirectionsResponse of (MapBox) It doesn't have any more! After I compile again. Do you have any Solution?
