### ISSUE TITLE
Add NavigationMapRoute above road layers

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#520]
The Android Maps SDK didn't used to expose the [`sourceLayerIdentifier`](https://github.com/mapbox/mapbox-gl-native/issues/8663), which meant that layer IDs were hardcoded in [the traffic plugin (fixed)](https://github.com/mapbox/mapbox-plugins-android/issues/14) and [for the route line](https://github.com/mapbox/mapbox-navigation-android/blob/3a8be52a98032743b5b9672f56c1026386ce3ece/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L356).

This can cause the route line to appear in the wrong place if the current style doesn't have a `ROUTE_BELOW_LAYER` where we expect it.

We should update the NavigationMapRoute and place the route line either [above the topmost map layer that isn't a symbol layer as is done on iOS](https://github.com/mapbox/mapbox-navigation-ios/blob/d4a46730bce08136f3fb60115988c4db3984bfe9/MapboxNavigation/NavigationMapView.swift#L489-L494), or above the topmost layer with source = roads.

cc @danesfeder @bsudekum

**Comment by danesfeder** [comment]
> update the NavigationMapRoute and place the route line either above the topmost map layer that isn't a symbol layer as is done on iOS, or above the topmost layer with source = roads

@tobrun is there a reliable way to do this?  

I'm looking at https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L198 wondering if that's a viable solution (you mention it might not always be accurate).

**Comment by tobrun** [comment]
> @tobrun is there a reliable way to do this?
> I'm looking at https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L198 wondering if that's a viable solution (you mention it might not always be accurate).

Afaik this is the only way for now, I would be nice if we could add this kind of functionality to core instead of writing it on the binding side.

**Comment by danesfeder** [comment]
@ericrwolfe 

@cammace baked the same logic from the traffic plugin:
https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L198

into the `NavigationMapRoute`:
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L517

I'm wondering if we saw this issue with that one style because I kept our normal "route below" layer set:
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L369

So the logic to look through the layers was never hit.

**Comment by ericrwolfe** [comment]
Yeah, I think this might be due to the ROUTE_BELOW_LAYER code. We should remove that and instead make sure that the NaivgationMapRoute code is hit.

**Comment by danesfeder** [comment]
Closed with #590
