### ISSUE TITLE
Recording and replaying rerouting 

### ISSUE THREAD

**Issue by VysotskiVadim** [mapbox/mapbox-navigation-android#5273]
Start recording using `MapboxNavigation.historyRecorder.startRecording()`. Set a route. Go off route to trigger rerouting. Save the history file.

In the saved history file you will find recorded coordinates and the routes that was set during `setRoutes` and rerouting.

Replay history file in `ReplayHistoryActivity`. Notice that `setRoutes` was called 2 times during rerouting instead of 1. The first time `setRoutes` was called from the `ReplayHistoryActivity` because of the `ReplaySetRoute` coming from the `mapboxReplayer`. The second time `setRoutes` was called from the SDK because the SDK detected `OFF_ROUTE` and requested a new route from the Directions API. The calls of `setRoutes` could be in any order.

### Steps to trigger behavior

 1. Record rerouting in history file
 2. Replay rerouting in `ReplayHistoryActivity`

### Expected behavior

`setRoutes` should be called 1 time. I'm not sure how exactly. Maybe we should return recorded route when SDK requests new route during rerouting? Or ignore results of Directions API during replay?

@kmadsen , what your opinion about expected behavior? 

### Actual behavior

The `setRoutes` is called 2 times. One because of event from replayer and another because of RerouteController.

**Comment by kmadsen** [comment]
What are the values of the set_route events in the history file? I think there may be an initial empty route, and then the actual route in a follow up event.

As for the [ReplayHistoryActivity](https://github.com/mapbox/mapbox-navigation-android/blob/16863953a3baae07c4fd10b059eb77a809beb40d/examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt#L331-L333). It is only replaying a file, so the two setRoute events are probably caused by the solution that created the history file.

**Comment by VysotskiVadim** [comment]
>  two setRoute events are probably caused by the solution that created the history file.

There is only one setRoute event. It was recorded when SDK did rerouting in the past. But when we replay location updates, the SDK detects an off-route and does rerouting again in the present. As a result `directionsSession.setRoutes` is called 2 times. One from the `ReplayHistoryActivity` which calls `MapboxNavigation.setRoutes` and the other from the `MapboxNavigation.reroute`.

**Comment by kmadsen** [comment]
> Expected behavior
setRoutes should be called 1 time. I'm not sure how exactly. Maybe we should return recorded route when SDK requests new route during rerouting? Or ignore results of Directions API during replay?

Do you mean, we want to be able to distinguish whether the set route event comes from a re-route or from a user-input? I do agree here, because replay is supposed to replay the external input.

Maybe we need to find a way to add `RoutesUpdateReason` to the `SetRoute` event. That way when it is replayed we could throw out the "re-route" set route events.

**Comment by kmadsen** [comment]
We could see if nav-native would want to add this reason. We could also experiment with an idea in the short term. Try creating a example where you add the `RoutesUpdateReason` in a custom event with `HistoryEventPushHistoryRecord`. And then when you're reading the history file with those custom events, you can pull out the reason to distinguish the setRoute events.

**Comment by Guardiola31337** [comment]
@kmadsen @VysotskiVadim where are we here? It's been a while.

**Comment by VysotskiVadim** [comment]
I still think it's a problem. But it doesn't seem like an important one. I don't think I will try fixing this in the nearest future. I'm closing the ticket to make backlog a little bit less loaded

**Comment by kmadsen** [comment]
@VysotskiVadim if you have some reasons for this, it could still be good to ask NavNative for a way to distinguish the SetRoute event.

https://github.com/mapbox/mapbox-navigation-native/blob/11617f9bc714024ddc4ff28d50f7c7e2f231cd7a/proto/history.proto#L278-L290

Or maybe they have a different recommendation for identifying if the set-route was produced by a re-route event.

https://github.com/mapbox/mapbox-navigation-native/issues/new
