### ISSUE TITLE
Revamp the turn icons used in Mapbox Android Nav SDK

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5382]
Mapbox Android Navigation SDK uses a default set of turn icons in the form of vector drawables. These vector drawables are used when showing maneuver turn instructions. However, some of these vector drawables are confusing and need to be revamped. There are customer [issues](https://github.com/mapbox/1tap-android/issues/1547) being reported as well in regards to incorrect icons. Issues with icons have been brought up verbally very often and we should take this up on a priority to fix them.

Vector drawables used are attached. 
[turnicons.zip](https://github.com/mapbox/mapbox-navigation-android/files/7900746/turnicons.zip)

Unfortunately I don't have the `.svg` files for these drawables.

/cc @mapbox/navigation-android @lawsonkight

**Comment by 1ec5** [comment]
Are you referring to the main maneuver icon? Can you use the assets in https://github.com/mapbox/navigation-ui-resources/tree/1ec5-vector-drawables/img/maneuvers/ for consistency with iOS?

**Comment by abhishek1508** [comment]
> Are you referring to the main maneuver icon?

Yes.

> Can you use the assets in https://github.com/mapbox/navigation-ui-resources/tree/1ec5-vector-drawables/img/maneuvers/ for consistency with iOS?

I can probably use some of them. Some icons like `fork: slight right`, `fork: right`, `merge: slight right`, `uturn`, `depart right` and few more are not available in the link you shared. Since these icons are already public we cannot remove their support or else we would be introducing regression.

**Comment by 1ec5** [comment]
There’s no such thing as a slight right fork or slight right merge, so just replace them with the non-slight versions if you need to maintain backwards compatibility, but I would recommend deprecating them so that developers don’t expect them to occur in practice.

We don’t have an asset for a departure instruction. The iOS navigation SDK has always shown the first instruction instead. But if necessary, I can whip one up by repositioning the 📍 on the arrival icons.

I can export the rest of the maneuvers. Not sure why they were omitted before.

**Comment by tomaszrybakiewicz** [comment]
Hey @1ec5. 
Does iOS use different **depart** icons? 

<img width="300" alt="new_2" src="https://user-images.githubusercontent.com/2678039/151838895-c4c5e33b-aaea-44fb-9de8-75863ceb4d02.png">

Any chance you could export and add them to [navigation-ui-resources folder](https://github.com/mapbox/navigation-ui-resources/tree/1ec5-vector-drawables/img/maneuvers/)?
