### ISSUE TITLE
Migrate generic, process-long shields cache to LruCache

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5418]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/5417/files#r792559126.

Shields data stored in the instances of [`ResourceCache`](https://github.com/mapbox/mapbox-navigation-android/blob/release-v2.2/libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/ShieldsCache.kt) implementations are currently being persisted in memory for the whole lifecycle of the process because of the wrapping [`RoadShieldContentManagerContainer`](https://github.com/mapbox/mapbox-navigation-android/blob/release-v2.2/libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/RoadShieldContentManagerContainer.kt) which is an `object`.

While shields don't have an extensive memory footprint, the risk of accumulating unnecessarily large cache over a process that's not restarted for weeks or months is a risk that we should consider and migrate the `ResourceCache#cache` to be an `LruCache`-based implementation (we can figure out the size limits for each implementation separately).

We might want to tackle this even before a Common Native Cache is available (which should handle this for us out-of-the-box).

cc @Zayankovsky @abhishek1508

**Comment by cafesilencio** [comment]
`CachResultUtils` would have been a good fit for this. It's probably too much refactoring to use it at this moment and it's easy to change the existing implementation to use and LRUCache instead of the map it's currently using.  

I have no idea what the cache size should be for the various types that are utilizing the cache. I'm initially using small values. Any guidance here would be appreciated @abhishek1508 @LukasPaczos .
