### ISSUE TITLE
`MapboxStatusView` use `internal class`

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5420]
Use `internal class` with a `Factory` to create models rather than `data class`

More context https://github.com/mapbox/mapbox-navigation-android/pull/5403#discussion_r793107709

**Comment by tomaszrybakiewicz** [comment]
How about Factory method?

```kotlin
data class Status internal constructor(...) {
   companion object {
      fun create(...): Status { ... }
   }
}
// usage:
val myStatus = Status.create("my message")
```

which usage can be simplified with import alias:

```kotlin
import com.mapbox.navigation.ui.status.model.Status.Companion.create as status

val myStatus = status("my message")
```

**Comment by RingerJK** [comment]
the problem here, users still have access to `copy`, and it's not backward compatible for java users (adding a new field to a class breaks code compilation)
Also a bit more context https://youtrack.jetbrains.com/issue/KT-11914

**Comment by abhishek1508** [comment]
Yep agreed. I would go for just a class and do the following as we have been doing:

```
class Status internal constructor()
```

```
@ExperimentalMapboxNavigationAPI
object StatusFactory {
    @JvmStatic
    fun buildStatus(message: String, duration: Long,.....): Status(message, duration, ....)
}
```

We did this after many discussions as we did not wanted to go forward with Builder pattern. A downside to this approach is that it might be confusing to the users as to why this is `Experimental`. For now, we have tried to convey the message using class based comments, but we can improve upon it. I would suggest to adopt it for now and keep discussing more on a solution we like better. This way we can still solve the problem yet iterate

**Comment by tomaszrybakiewicz** [comment]
Why not keep it simple and just add factory method to `Status` class?

```kotlin
sealed class Status private constructor(...) {
    companion object {
        @ExperimentalMapboxNavigationAPI
        @JvmStatic
        fun create(message: String, ...): Status = Status(message, ...)
    }
}
```

**Comment by Zayankovsky** [comment]
Why do we need factory methods if we can have constructors with default values for parameters and `@JvmOverloads` annotation? We just need to add all new parameters only to the end and all new parameters must have default values, then it won't be a breaking change for both Kotlin and Java users. Is it to give us an option to add parameters without default values?

**Comment by RingerJK** [comment]
There's another problem for java users if they want to create a new object with the very last changed field of the constructor and others take as defaults this way users have to put all "default" values manually to the constructor. `Builder` solves this

**Comment by tomaszrybakiewicz** [comment]
@RingerJK And what is wrong with that? If users choose to write Java instead of Kotlin, let them work for it. We shouldn't degrade our designs, introduce unnecessary factories and builders, nor stand upside down on our heads just to satisfy few Java enthusiasts. If they want easy... they should use Kotlin (it's interop with Java after all).

This Status data class is a simple value object that has been modeled after [iOS Status struct](https://github.com/mapbox/mapbox-navigation-ios/blob/ecd6ebe39894bb02737538beee737b0c845493ab/Sources/MapboxNavigation/StatusView.swift#L26) that's used by their StatusView. I highly doubt we will need to expand it further.

I am strongly suggesting to KISS. Leave Status data class intact and introduce either builder or a factory method next time we need to add additional fields.
