### ISSUE TITLE
MapboxBuildingsApi : queryBuildingToHighlight always empty

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#5433]
**Mapbox Navigation SDK version:** 2.2.1

### Steps to trigger behavior
Hi Mapbox,

We are trying to display highlighted buildings but it looks like the result of the query is always empty.
In the past (on 2.x.x) it was working properly.
Not sure if something changed since that could affect this.
* Buildings are correctly displayed (layer building-extrusion)
* 3D Terrain is added (but doesn't seem to impact)

Is there something I'm missing?

Here is the class handling the highlight : 

 ```
class BuildingHighlight(val mapView: MapView) {

	private val buildingView by lazy { MapboxBuildingView() }

	private val mapboxBuildingsApi by lazy { MapboxBuildingsApi(mapView.getMapboxMap()) }

	private val buildingHighlightOptions by lazy {
		MapboxBuildingHighlightOptions.Builder()
			.fillExtrusionColor(mapView.context.getColorFromAttr(R.attr.cby_colorBrandAccent))
			.fillExtrusionOpacity(0.5)
			.build()
	}

	fun clear() {
		buildingView.clear(getStyle())
	}

	private fun getStyle() = mapView.getMapboxMap().getStyle()!!

	fun highlight(point: Point) {
		mapboxBuildingsApi.queryBuildingToHighlight(point) {
			val buildings = it.value?.buildings ?: return@queryBuildingToHighlight
			buildingView.highlightBuilding(getStyle(), buildings, buildingHighlightOptions)
		}
	}

	fun onProgress(routeProgress: RouteProgress) {
		mapboxBuildingsApi.queryBuildingOnFinalDestination(routeProgress) {
			val buildings = it.value?.buildings ?: return@queryBuildingOnFinalDestination
			buildingView.highlightBuilding(getStyle(), buildings, buildingHighlightOptions)
		}
	}
}
```

**Comment by cafesilencio** [comment]
The issue could be the type of point you're using.  If it's a point on the route that won't necessarily be enough for a building to be identified. The point needs to be a building's location.  The `RouteOptions` you are using aren't in your code snippet so i'll refer you to the documentation for the `queryBuildingOnFinalDestination` method [here](https://github.com/mapbox/mapbox-navigation-android/blob/2333001a90914fca1c95b2f871587d0abfabd98c/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/api/MapboxBuildingsApi.kt#L139).

An easy way to see this is to add a long press listener to the map and in the listener method query for buildings based on the point objects.  If you click on roads vs. buildings you'll see that buildings won't be found when clicking on the road.

```
...
mapView.gestures.addOnMapLongClickListener(this)
...

override fun onMapLongClick(point: Point): Boolean {
    buildingsApi.queryBuildingToHightlight(point) {
        it.fold(
            {},
            { value ->
                  Log.i("tag", "number of buildings found = ${value.buildings.size}")
             }
        )
    }
}
```

In addition I noticed that you're calling `mapboxBuildingsApi.queryBuildingOnFinalDestination` in the route progress observer. I don't recommend doing this since the route progress updates about every 1 second during navigation.  I suggest using an arrival observer.  You can see an [example here](https://github.com/mapbox/mapbox-navigation-android-examples/blob/c50ea353ab49559b7917851bf0a3c37adb4d1553/app/src/main/java/com/mapbox/navigation/examples/basics/ShowBuildingExtrusionsActivity.kt#L240).

**Comment by Christophe668** [comment]
Thanks @cafesilencio for the quick reply! 
Indeed good advice for the `queryBuildingOnFinalDestination`.

Actually, the long press to test the feature is what I do. On press, I call the function
`   fun highlight(point: Point)`

Before it was highlighting my place (for instance). 
Not anymore, therefore my question, I do not see what could interfere here.
When I log the response I have no errors, nor a result, the value is an empty list. 

I did try on different buildings, without success.
Very weird, I did some research but didn't find anything

**Comment by cafesilencio** [comment]
A working example I tested with can be found [here](https://github.com/mapbox/mapbox-navigation-android/blob/5baf5e8254c901e256bafec6f2f8745f2b4f0b72/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt#L71).  It's a starting point.  I'm not sure what else to suggest at this moment. I"m not familiar with how the map internally searches for the building.  The style can definitely be a factor.  If it's a style that is more like a topographical map rather than a city or street map it may not have the necessary layer.  If that's the case you may need to customize the map style you're using, using Mapbox Studio.  You mentioned using the 3d terrain layer.  That's a new layer I haven't worked with very much but that could be enough to knock out the layer(s) used for querying building locations.  

cc @mapbox/maps-android

**Comment by Christophe668** [comment]
Hi again,

So I asked my iOS colleague, they are able to display the building. 
Looking at the internal code of Mapbox, I can spot a difference.

On iOS the code queries feature that starts with `building` whereas on Android the code is looking exactly for `building`.

in `com.mapbox.navigation.ui.maps.building.BuildingProcessor` (Navigation 2.3.0)
I see this: 
```
    private const val BUILDING_LAYER_ID = "building"

    suspend fun queryBuilding(
        action: BuildingAction.QueryBuilding
    ): BuildingResult.QueriedBuildings = suspendCoroutine { continuation ->
        val screenCoordinate = action.mapboxMap.pixelForCoordinate(action.point)
        val queryOptions = RenderedQueryOptions(listOf(BUILDING_LAYER_ID), null)
        action.mapboxMap.queryRenderedFeatures(screenCoordinate, queryOptions) { expected ->
....
```

Although, the buildings set by the components on Mapbox Studio are name "building-extrusion".

Shouldn't the query by looking for layer that start by `building` as in iOS?

cc: @LukasPaczos if you can have a look, that would be great 🙏

**Comment by cafesilencio** [comment]
I added "building-extrusion" to the list of layers queried.  The pull request is here: https://github.com/mapbox/mapbox-navigation-android/pull/5575.
