### ISSUE TITLE
Find a solution to selectively run instrumentation tests 

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5486]
![Screen Shot 2022-02-17 at 2 43 31 PM](https://user-images.githubusercontent.com/3021882/154584951-6e47b9b3-1c75-4f37-ac4c-6ebbb91e678e.png)

We have been waiting 3 hours to merge pull requests for drop-in-ui. These do not impact instrumentation tests.

This ticket is to find a way to speed up the instrumentation tests. Or to force the pull requests that need them, to run them. For example, nav-native upgrades should require instrumentation runs. Also core changes such as the NavigationRoute change https://github.com/mapbox/mapbox-navigation-android/pull/5411

**Comment by kmadsen** [comment]
We've temporarily removed `instrumentation-tests` from required jobs to complete before merging.

**Comment by LukasPaczos** [comment]
This is caused by Firebase maintenance which temporarily limits availability of physical devices which makes the jobs queue up - https://status.firebase.google.com/incidents/1fa4H8MH1ULMPearoyNS.

I don't see what selectively running test would achieve here, we still need the full suite to pass before merging production code. We could explore other ways to speed up the builds but this ticket might not a good place to track it.
