### ISSUE TITLE
NavigationLauncher Walking Reroute Issue

### ISSUE THREAD

**Issue by rheng001** [mapbox/mapbox-navigation-android#549]
I have set my NavigationRoute.builder profile to "walking". I can launch the NavigationLauncher with walking directions just fine but whenever a reroute occurs the new route displayed automatically is for DRIVING. Is this a bug or as intended? I want the reroute to display a new walking route only since I've set the profile to only do walking directions and not driving. Can I get some help?

**Comment by cammace** [comment]
This is happening because when a reroute occurs we are building a new navigation route entirely rather than just modifying the users current origin and bearing using the `toBuilder` method.

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/RouteViewModel.java#L118-L132

**Comment by rheng001** [comment]
@cammace 

Oh that's what was happening. Thank you for clarifying that. I'll just wait until this get resolved. 

Thanks again.

**Comment by danesfeder** [comment]
@rheng001 PR in progress https://github.com/mapbox/mapbox-navigation-android/pull/575

**Comment by konskons5** [comment]
Similar issue occurs when rerouting a route that had waypoints in it. After the reroute event, the waypoint are ignored.
