### ISSUE TITLE
Avoid setting NavigationCamera to Idle state if transition to overview or following is canceled.

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5600]
Current `requestNavigationCameraToFollowing` and `requestNavigationCameraToOverview` public API(s) start their transitions with `TRANSITION_TO_FOLLOWING` and `TRANSITION_TO_OVERVIEW` respectively before finally ending with `FOLLOWING` and `OVERVIEW`. In between these transition states if the transition is canceled, the `NavigationCameraState` goes back to `Idle` state. 

The problem with this approach is that, the apps have to handle this intermediate `Idle` state although it wasn't intentional from users perspective but something that the SDK assumes. Both 1Tap and Drop-In UI are handling this scenario differently along with other customers. The aim of this ticket is remove the code that transitions camera to `Idle` state if transition to following/overview is canceled for any reason.

/cc @LukasPaczos

**Comment by kmadsen** [comment]
Some other notes because I was also wondering if the trip session change is creating the issue.

it is not 100% reproducible, but it feels like it happens more often after this one https://github.com/mapbox/mapbox-navigation-android/pull/5594. 

I ran some tests to verify the state is being updated correctly. The issue will happen when the view model correctly moves into the overview state. So that leads me to believe it's in the CameraComponent or NavigationCamera. 

This log came from this branch https://github.com/mapbox/mapbox-navigation-android/pull/5594
```
15:52:05.979 CameraComponent CameraViewModel state change Overview
15:52:07.130 CameraComponent onDetached
15:52:07.133 CameraComponent onAttached
15:52:07.164 CameraComponent CameraViewModel state change Idle
15:52:08.559 CameraComponent onDetached
15:52:08.561 CameraComponent onAttached
15:52:08.574 CameraComponent CameraViewModel state change Overview
```

The issue may become more obvious when adding a navigation state, which causes CameraComponents to be detached/attached more frequently
