### ISSUE TITLE
NavigationView lifecycle owner in a fragment 

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5796]
Capturing from https://github.com/mapbox/mapbox-maps-android/pull/1330#discussion_r869177995, we should double-check the way we obtain the parent lifecycle owner of the `NavigationView` when it's hosted in a `Fragment`.

We most-likely need to expose a setter and document that in cases of a `Fragment` use-case, the lifecycle owner has to be injected. Or we can also play around with the `ViewTreeLifecycleOwner` but that only works for views already attached to the hierarchy. Fragment integration has been discussed in https://github.com/mapbox/mapbox-navigation-android/issues/5162 but from the perspective of the `ViewModelStoreOwner` and seems that the hosting lifecycle context has fallen through the cracks.

cc @abhishek1508 @tomaszrybakiewicz @kmadsen @cafesilencio @Zayankovsky

**Comment by kmadsen** [comment]
Yeah.. Fragment is not a Context, so unwrapping the Context will give you the Activity - not the hosting Fragment. The NavigationView is attached to the hosting Activity, not the hosting Fragment.

Navigation has not yet seen issues, because there isn't an experience that requires this. For example, we don't have a ViewPager with different `NavigationView`. There's no dual-screen navigation experience. Those experiences are still supported, but the ViewModel will also be shared because it only supports `activityViewModels`
```
 val viewModel by activityViewModels<DropInNavigationViewModel>()
```

The request here seems like, we would want to add support for attaching the view to the Fragment view model.

Considering the solutions here.. What are we actually trying to support here? This kind of issue seems like it is driven by a detail rather than a problem 🤔 . Maybe the solution is to just, support a `NavigationFragment`.

**Comment by kmadsen** [comment]
Also prototyped a little fragment swapper just to help thinking about it. These are the lifecycle events from `ViewLifecycleRegistry`. 

```
// Start FirstPageFragment containing NavigationView.hashCode = 156142097
17:52:12.652 onCreateView 156142097
17:52:12.657 onStart FirstPageFragment
17:52:12.661 onResume FirstPageFragment
17:52:12.687 onViewAttachedToWindow 156142097
17:52:12.688 onCreate 156142097
17:52:12.688 onStart 156142097
17:52:12.688 onResume 156142097

// Swap SecondPageFragment containing NavigationView.hashCode = 140078075
17:52:20.021 onPause FirstPageFragment
17:52:20.023 onStop FirstPageFragment
17:52:20.027 onCreate SecondPageFragment
17:52:20.038 onCreateView 140078075
17:52:20.039 onViewAttachedToWindow 140078075
17:52:20.039 onCreate 140078075
17:52:20.039 onStart 140078075
17:52:20.039 onResume 140078075
17:52:20.045 onStart SecondPageFragment
17:52:20.052 onViewDetachedFromWindow 156142097
17:52:20.053 onPause 156142097
17:52:20.053 onStop 156142097
17:52:20.086 onDestroy FirstPageFragment
17:52:20.089 onResume SecondPageFragment
```

**Comment by LukasPaczos** [comment]
Documenting my idea in https://github.com/mapbox/mapbox-navigation-android/pull/5818.

**Comment by kmadsen** [comment]
Ok makes sense what the issue is. When attaching NavigationView to a Fragment, the coroutines will never be destroyed until the hosting Activity is destroyed.

From the [lifecycle events](https://github.com/mapbox/mapbox-navigation-android/issues/5796#issuecomment-1128287629), you can see that `17:52:20.086 onDestroy FirstPageFragment`. And we should expect to see `onDestroy 156142097`.

This is causing all of the coordinators to remain attached because they are never destroyed.
```
        attachCreated(
    ...
```
