### ISSUE TITLE
Navigation routes cover added layers

### ISSUE THREAD

**Issue by Ranafugaz** [mapbox/mapbox-navigation-android#5964]
Android API: 32
Mapbox Navigation SDK version: 2.5.1

### Steps to trigger behavior
Draw navigation routes on the map with MapboxNavigation.setNavigationRoutes(routes).

### Expected behavior
The routes layers should be added below other added layers, so that they are not covered. 
For example, they could be added below the layer id "mapbox-location-indicator-layer" 

### Actual behavior
The routes layers are drawn on top of all other layers, covering annotations and the user location.
![Screenshot 2022-06-24 at 11 28 38](https://user-images.githubusercontent.com/11565092/175507036-ac27425d-3de8-45f3-9b10-7f74384bfcd6.png)
![Screenshot 2022-06-24 at 11 38 59](https://user-images.githubusercontent.com/11565092/175508936-aa4215c1-d02c-41fc-b22f-4ae6b29544f9.png)

**Comment by cafesilencio** [comment]
It's necessary to indicate the route line layer elevation using the `MapboxRouteLineOptions`.  Since styles are customizable there's no certainty any map will have the "mapbox-location-indicator-layer".  Also that layer is initialized by the map. The timing of that layer's initialization can't be predicted or controlled by the Navigation SDK. That layer is initialized during the initialization of the `LocationComponet`  If no layer location is specified the route line defaults to the top of the layer stack.  For navigation related Mapbox styles "road-label-navigation" is a good location for the route line layers as indicated in the snippet below.  This is documented [here](https://docs.mapbox.com/android/navigation/guides/ui-components/route-line/#position-the-route-line-relative-to-map-layers). Although I see it's a little out of date.  I suggest using "road-label-navigation" as indicated in the code snippet below. This layer elevation can be changed according to the needs of your application.


```
        MapboxRouteLineOptions.Builder(this)
            .withRouteLineBelowLayerId("road-label-navigation")
            .build()
```
