### ISSUE TITLE
Android Drop-In UI : Should not set routes to Nav SDK during route preview

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#5990]
Currently Drop-In sets routes during route preview by calling `MapboxNavigation.setNavigationRoutes`, which makes Nav SDK go into Active Guidance state. This has several implications such as voice instructions being played or route simulation starting prematurely (`ReplayProgressObserver` pushes location updates, as SDK invokes its route progress observers). All information necessary for updating the UI during route preview can be retrieved from the routes themselves (e.g. `DirectionsRoute` has `distance` and `duration`, which can be displayed in the bottom sheet with the trip information).

**Comment by abhishek1508** [comment]
This issue is blocked by https://github.com/mapbox/mapbox-navigation-android/issues/5992

**Comment by cafesilencio** [comment]
I don't know the full context but I've seen some talk about route preview in other places.  Is there some reason for not just calling set routes on the `MapboxRouteLineApi` and rendering the result for route preview?  That would draw the routes on the map. When returning from a route preview screen to active guidance `MapboxRouteLineApi::getNavigationRoutes` can be used to get the routes in the correct order for setting on `MapboxNavigation`.  Will that not work?

**Comment by kmadsen** [comment]
> When returning from a route preview screen to active guidance MapboxRouteLineApi::getNavigationRoutes can be used to get the routes in the correct order for setting on MapboxNavigation. Will that not work?

The approach could be to use the `MapboxRouteLineApi` but unclear to me if that helps . The higher level issue is that, `RouteLineComponent` can only render routes that are set to `MapboxNavigation`. It needs to be able to render `NavigationRoute` that are not in preview.

I think you resolved this with the [`CarRouteLine`](https://github.com/mapbox/mapbox-navigation-android/blob/9f849f7f3051c85cfc6808474e8734ae1b482931/libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt#L38), using a [RoutesProvider](https://github.com/mapbox/mapbox-navigation-android/blob/9f849f7f3051c85cfc6808474e8734ae1b482931/libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/RoutesProvider.kt#L3-L6) and that works great. Are you suggesting a different approach than that?

**Comment by abhishek1508** [comment]
> https://github.com/mapbox/mapbox-navigation-android/issues/5990#issuecomment-1183791237

That's what we will do when we address this issue. We are going to fetch route using points or route options and once the routes are returned from the router, we are gonna set it to `RouteLineApi` so that it can be drawn. Following, when the user clicks on start navigation, only then we will set the route to mapbox navigation. This is exactly what 1TAP and Android-Auto is doing.

However, there is a greater issue here. With the steps above, `RoutesObserver` is not the source of truth anymore. As you are setting the route to route line api when you fetch it from the router, `RoutesObserver` is not yet called because routes have not been set to `mapboxNavigation` yet. Now, when you transition to active guidance and set the routes to `mapboxNavigation`, only then `RoutesObserver` is triggered. This could easily lead to mismatch between the routes in route preview and active guidance state since the source of route set to route line api vs mapboxNavigation is different.

This issue won't be resolved with this ticket as it has nothing to do with Drop-In UI, AA or 1TAP. This is more of a fix on the core side, where we should have logic that would help us to fix this.
