### ISSUE TITLE
Dynamic camera, first pass

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#601]
_Android version of https://github.com/mapbox/mapbox-navigation-ios/issues/773_

The camera should:
* Be more dynamic, communicating maneuver urgency by camera distance/zoom level
* Be timed with voice announcements: what's communicated on screen should match audio cues
* Provide ample context for maneuvers

As a rough first pass, we should implement basic stepped camera movements achieving the following:
- [ ] Triggered by/synchronized with voice announcements
- [ ] On the completion announcement of a maneuver: zoom out to provide context for long steps with long periods of inactivity
- [ ] At the first approach maneuver announcement (`In 2 miles...`): zoom to show the upcoming maneuver on the map, whether by a fixed zoom level based on distance, or a zoom to fit function.
- [ ] At the final turn maneuver announcement: zoom in closely to our current default zoom level 

Once this basic set of triggers/logic is in place, we can experiment with more sophisticated zoom logic, camera tilt, anchor points, etc.

cc @mapbox/navigation-android

**Comment by zugaldia** [comment]
cc: @tobrun who looked into camera animation in the context of https://github.com/mapbox/mapbox-gl-native/issues/9808#issuecomment-324274671.

**Comment by davols** [comment]
Don't want to hijack this at all. Thought about the camera and its zoom levels the other day. But having basic camera movements in relation to maneuvers sound great. My two thoughts were:

* Allow the user to set the zoom level (don't override it when pressing re-center)
* Zoom levels depending on speed 

Both might be fixed with camera movement on voice announcement, but as of now the first one feels quite important since it's really annoying from a UX perspective that it takes over the zoom at re-center.
