### ISSUE TITLE
Metalava includes internal stuff in the current.txt

### ISSUE THREAD

**Issue by dzinad** [mapbox/mapbox-navigation-android#6051]
Example: `CacheHandleWrapper`. It's an internal object, but `current.txt` has the following lines:
```
  public final class CacheHandleWrapperKt {
  }
```
Looks like a Metalava problem. We should look into the docs and maybe up the version if it's already fixed or cut a ticket.

**Comment by Guardiola31337** [comment]
As mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/6044#discussion_r920240933

I believe this is not an issue and how Metalava works.

> That's not an issue, it's how Metalava keeps track of Kotlin files - `Kt` as we're including a `typealias` https://github.com/mapbox/mapbox-navigation-android/blob/4238882c4b93545b6d7da34a290a4e2c0d483f99/libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/CacheHandleWrapper.kt#L6
>
> In any case, as you can see that block is empty, meaning that we're not exposing anything publicly 👍 
>
> Other examples 👀 https://github.com/mapbox/mapbox-navigation-android/blob/827a8774aa367e07961028401064ff8abae29257/libnavigation-core/api/current.txt#L734-L745

**Comment by dzinad** [comment]
But what if we rename the object? `core-check-api` will fail while it shoudn't.

**Comment by Guardiola31337** [comment]
The object shouldn't be a problem (we can quickly test this), I believe what it's tracking is the file name and hence the `Kt`. Although, if we change the name of the file, that'll probably be caught by `check-api`. In any case, that'd catch our eye and we can definitely `update-api` as that wouldn't break SemVer. It's the same as adding new APIs, we need to re-generate Metalava files as it's safe because adding it's fine, as APIs don't break. Ultimately, Metalava is a tool that we use to warn us of potential breaking changes but we ultimately need to check / update the files in some situations after making sure we're good.
