### ISSUE TITLE
Android Drop-In UI: Add support for programmatically changing Info Panel state

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#6099]
As a user, I should be able to hide, collapse and expand info panel on demand. The info panel should be hideable by default so that I can hide the bottom sheet at anytime to make more of the map visible.

**Comment by tomaszrybakiewicz** [comment]
@abhishek1508 Need your opinion on something.

Currently, InfoPanelCordinator observes both `NavigationState` and `NavigationViewOptions.showInfoPanelInFreeDrive` values and determines bottom sheet visibility as following:

![Screen Shot 2022-08-03 at 2 10 44 PM](https://user-images.githubusercontent.com/2678039/182679237-a4660bb5-37aa-43a6-83e7-74d78b0c3bfe.png)
_(State Table)_

In this ticket, I am seeing two feature requests which require a bit of clarification:
1. **Allow Info Panel to be hiddable.**
   We can be easily accomplish this by adding new flag to `NavigationViewOptions` (`isInfoPanelHiddable`) and amending `InfoPanelCoordinator` to observe and copy it's value to `BottomSheetBehavior.isHideable`.
   What's unclear to me is: the restore logic to the collapsed state after the Bottom Sheet is hidden via a swipe gesture.
   According to the above _State Table_, `InfoPanelCoordinator` will automatically re-open Info Panel when NavigationState change. I am not sure if that's what is expected here.

2. **Ability to programmatically show and hide Info Panel** 
    Since the system automatically updates Info Panel visibility. We need a way to override that behaviour when Info Panel visibility is programmatically changed. We could do this by introducing another, nullable, `NavigationViewOptions.infoPanelForcedState` value that will accept one of the `BottomSheetBehaviour` values `STATE_COLLAPSED`, `STATE_EXPANDED`, `STATE_HIDDEN`, `STATE_HALF_EXPANDED`. This value, then can be observed by`InfoPanelCoordinator` and assigned to `BottomSheetBahaviour`. Setting this value to any _non-null_ value will disable default (auto-hiding) behaviour. 
   ![Screen Shot 2022-08-03 at 2 27 34 PM](https://user-images.githubusercontent.com/2678039/182682314-4d23073a-4638-4b3d-ba44-0d8b2d6adbbb.png)
  _(new State Table)_

WDYT?

**Comment by abhishek1508** [comment]
> ![Screen Shot 2022-08-03 at 2 10 44 PM](https://user-images.githubusercontent.com/2678039/182679237-a4660bb5-37aa-43a6-83e7-74d78b0c3bfe.png)
_(State Table)_
>
> In this ticket, I am seeing two feature requests which require a bit of clarification:
> 1. **Allow Info Panel to be hiddable.**
   We can be easily accomplish this by adding new flag to `NavigationViewOptions` (`isInfoPanelHiddable`) and amending `InfoPanelCoordinator` to observe and copy it's value to `BottomSheetBehavior.isHideable`.
   What's unclear to me is: the restore logic to the collapsed state after the Bottom Sheet is hidden via a swipe gesture.
   According to the above _State Table_, `InfoPanelCoordinator` will automatically re-open Info Panel when NavigationState change. I am not sure if that's what is expected here.

The restore logic should be that `InfoPanel` will open automatically as per defined in the table above. The reason being: Let's say we are in free drive and we have marked InfoPanel to hide; so it's hidden. Now we long press on map to select a destination and transition to `DestinationPreview`. If we don't restore the info panel to collapsed state, as a user I would not know how to transition to `RoutePreview` or `ActiveNavigation` states because the info panel is hidden which contains buttons to `Start Route Preview` and `Start Active Guidance`.

> 2. **Ability to programmatically show and hide Info Panel** 
    Since the system automatically updates Info Panel visibility. We need a way to override that behaviour when Info Panel visibility is programmatically changed. We could do this by introducing another, nullable, `NavigationViewOptions.infoPanelForcedState` value that will accept one of the `BottomSheetBehaviour` values `STATE_COLLAPSED`, `STATE_EXPANDED`, `STATE_HIDDEN`, `STATE_HALF_EXPANDED`. This value, then can be observed by`InfoPanelCoordinator` and assigned to `BottomSheetBahaviour`. Setting this value to any _non-null_ value will disable default (auto-hiding) behaviour. 
   ![Screen Shot 2022-08-03 at 2 27 34 PM](https://user-images.githubusercontent.com/2678039/182682314-4d23073a-4638-4b3d-ba44-0d8b2d6adbbb.png)
  _(new State Table)_

Yep agreed to the fact that we need additional flag to `override` default `InfoPanel` behavior.
