### ISSUE TITLE
Error on NavigationLauncher.startNavigation

### ISSUE THREAD

**Issue by JavierDiaz500** [mapbox/mapbox-navigation-android#610]
im following the tutorial of this page: https://www.mapbox.com/help/android-navigation-sdk/

and i have 3 errors on the code

line1: NavigationLauncher.startNavigation(MainActivity.this, origin, destination,
                                awsPoolId, simulateRoute);
on the oncreate method

line2: NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .build()

on the origin variable

line3: navigationMapRoute.addRoute(currentRoute);

the line 2 and 3 are in the getRoute method

**Comment by danesfeder** [comment]
Hey @JavierDiaz500, thanks for bringing this to our attention.  It looks like our help tutorial is a little out of date - please see https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#launch-the-navigation-ui for the recent updates using `NavigationViewOptions`.

For `NavigationRoute` we now also use `Point` instead of `Position`.  You can use `Point.fromLngLat()` to create a new coordinate.  

In the meantime, let us know if you have any other questions and we will work on updating those docs!
