### ISSUE TITLE
Capability to show the destination address in the Maneuver secondary text

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6205]
Hi, I am using DropInUI NavigationView for my application. In mapbox version1.x, I had the ability to modify the maneuver information. I have a requirement to show the destination address in the banner(maneuver) instructions at the top. I have done that the expected behavior in previous version. I have two scenarios.
1.So whenever there is a data available to show in secondary text then I will show that information. Otherwise I will show my address in the secondary text.
2. The second scenario is that I want to show the address always in the secondary text.

**implementation 'com.mapbox.navigation:ui-app:2.8.0-alpha.3'
    implementation 'com.mapbox.navigation:ui-dropin:2.8.0-alpha.3'**

**Comment by abhishek1508** [comment]
This is not possible today with the navigation SDK. The SDK exposes `MapboxManeuverView` which controls the visibility of the `MapboxSecondaryManeuver`. At the moment, the logic is such that `MapboxSecondaryManeuver` is only shown when a secondary instruction is available; otherwise it's hidden. Based on the request above, you would need the `MapboxSecondaryManeuver` to always be visible so you can show the secondary instruction when available or else show the destination address. There is a workaround you can use to achieve this, but I would discourage doing that since. it will involve a lot of changes in your application.

I would like to understand the requirement behind the need to display address in secondary maneuver view. This is not recommended for various reasons:
- Secondary text as the name suggests is for information purpose
- It is assigned a small surface in the UI with smaller fonts. 
- It can be easily overlooked because primary instructions is what is important.

I would recommend to display the destination address in `InfoPanelHeader` along with trip progress information. That way it's easy to associate the trip progress with the destination you are going to and both the pieces of information are in the same place thereby making it easy to visualize.

It would be great if you could revisit the decision on where you would want to display the destination address. Let me know if I can be of more help.

/cc @EricGeiler

**Comment by Sridhar261990** [comment]
As you advised, we have moved the address to info panel.
