### ISSUE TITLE
Make it clear that custom controllers, etc. should invoke all methods from the main thread unless specified otherwise

### ISSUE THREAD

**Issue by dzinad** [mapbox/mapbox-navigation-android#6210]
Example:
If a user sets custom RerouteController, they implement the reroute method which is expected to invoke a callback. However, it is not specified anywhere that it should be invoked from the main thread (while it should).
Options:
1. Expand the docs;
2. Mark the interface with `@MainThread` annotation.

I'd go for two options combined. 
We should also look for other places where situations like this are possible.

**Comment by kmadsen** [comment]
Many implementations are not thread safe. But that does not mean we should force potential background tasks to use the `@MainThread`. 

I think we should consider the `LocationsCollectorImpl` problem as something specific to the location updates. It's the [LocationEngine](https://github.com/mapbox/mapbox-events-android/blob/d73ca293b194376516997b73c5139b28430be671/liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java#L44-L46) that allows developers to decide what `Looper` to update locations from. 

I agree that we should be careful adding [CopyOnWriteArrayList](https://developer.android.com/reference/java/util/concurrent/CopyOnWriteArrayList) because that could be very expensive (locations are 1hz and every write creates a new array). The `LocationsCollectorImpl` should not have a synchronous lock either, because blocking the main thread is always bad.

The mechanism responsible for calling [onNewRawLocation](https://github.com/mapbox/mapbox-navigation-android/blob/da3115462b7e081ea25676e495a6f92adb785c69/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt#L144) is also handling threads. [It seems we to ensure that this](https://github.com/mapbox/mapbox-navigation-android/blob/da3115462b7e081ea25676e495a6f92adb785c69/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt#L263) is not being called by multiple threads.

**Comment by dzinad** [comment]
The problem is a bit different. All the interaction with the collection were from the main-thread except for one that originated in `NavigationRerouteController.RoutesCallback#onNewRoutes`. But the `NavigationRerouteController` was external, provided by the user, not ours. And the user did not know that the callback must be invoked from the main thread. Because we don't specify it. 
I'm not saying that anything not thread-safe should be called from the main thread. But there are things like this one that should (I guess it would be mostly our callbacks invoked by custom controllers).
The only other alternative is to handle these situations by ourselves (switch the thread in our callbacks).
cc @LukasPaczos

**Comment by dzinad** [comment]
Also there's `MapboxNavigationApp`. Capturing from Slack thread, there are some methods that should be annotated with `@MainThread` because `androidx.lifecycle` implementations require main thread (`setup`, `register`, `unregister`, `disable`).

**Comment by dzinad** [comment]
Why do we at all require `MapboxNavigation` interactions to be from the main thread? I mean it's not like it has any interactions with UI or system API that would require the main thread. Is it just a too strong "not thread-safe" mark? Or does it really need the main thread? @mapbox/navigation-android
