### ISSUE TITLE
Android Drop-In UI: Add the ability to modify the maneuver style in dark mode

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6321]
Hello all, 
I am using DropInUi for my application.

Please look at the below image. We have used dark mode and look at the maneuver list and the arrows. Is it possible to customize that? Because I think it should display in white color. Please correct me if I am wrong. I have also gone through [CustomRuntimeStylingActivity](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/app-preview/src/main/java/com/mapbox/navigation/examples/preview/dropinui/CustomRuntimeStylingActivity.kt) But I can't find any code blocks to customize maneuver.
![image-20220908-162223](https://user-images.githubusercontent.com/95765713/189884837-a139ced8-72a7-46ec-a6c7-18916f7ee5f4.png)

**Comment by EricGeiler** [comment]
I will add more to this ticket, I'm seeing issues where I believe the wrong theme/mode images are being shown for exit shields?

Looks to me like the exit shield is showing possibly a daytime image instead of a night image?
![image](https://user-images.githubusercontent.com/61550186/189894892-fa81a96f-67f3-4fae-9281-6d08eb1a2a41.png)
![image](https://user-images.githubusercontent.com/61550186/189895081-677d9674-73c1-4a67-ba1c-040b001e8146.png)
![image](https://user-images.githubusercontent.com/61550186/189895123-9c2b7018-ba5c-4eac-b3be-1eb86f543ece.png)

**Comment by abhishek1508** [comment]
This issue is fixed [here](https://github.com/mapbox/mapbox-navigation-android/pull/6330) and will be available with `v2.8.0-rc.1` scheduled to happen by tomorrow.

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508.
