### ISSUE TITLE
arrive event nothing happen

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-navigation-android#674]
I'm working on mapbox android navigation sdk. only problem is arrive event, i found all the arrive event logic but i don't know what is happening in this case. i also checked the default without any change but nothing happens when user arrive in specific destination. any one know what is the problem ? it's hard to debug it because it needs a laptop with a in hand car with huge traffic always and now it's not possible well.

**Comment by danesfeder** [comment]
Hey @AliKhoshraftar - how are you using the navigation SDK?  Are you using our `navigation-ui` library?  Or the core SDK?

**Comment by danesfeder** [comment]
I believe I know what you're talking about.  This is a bug that occurs after an arrival event and there is no longer a route to be navigated along.  This should be fixed in #667.  To detect an arrival event you can use our public util method https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.java#L58-L61.  This is the same method we used in `ProgressChangeListener` to detect an arrival along a `LegStep`

**Comment by danesfeder** [comment]
Feel free to re-open if the above solution isn't sufficient.
