### ISSUE TITLE
Navigation doesn't start if you're too far off the road

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-android#686]
I live in an apartment complex about 300 meters away from nearest OSM road. When testing the navigation from my house, included navigation UI just doesn't do anything - it doesn't show next waypoint, doesn't show the route, doesn't update my location. 

If I try the same from the road, everything works just fine. 

Expected - navigation should work from anywhere.

**Comment by danesfeder** [comment]
Hey @kozyr, thanks for the feedback.  Testing from inside your apartment may result in issues with your GPS updating correctly / frequently.  300 meters is definitely more than our off-route threshold and should immediately trigger a off-route event with `OffRouteListener`.  

If you're using our core library, it's up to you on the client to then call for a new route: https://www.mapbox.com/android-docs/navigation/overview/off-route/

For the turn-by-turn UI, the UI may be blank because your phone hasn't produced a valid GPS update and you have no progress along the route.

**Comment by kozyr** [comment]
Hi @danesfeder , thing is, my garage is right by my house, and the tiny roads that lead out to a main road there are not in OSM: 
![image](https://user-images.githubusercontent.com/993879/35824357-3a09222e-0a78-11e8-941e-87b5ad901a5e.png)
I'm right near the center of the image where the marker is. So when I start the UI, it's completely blank, and it's a pretty bad user experience. I guess it will also happen in a lot of mall parking lots as well.
 
The directions that Mapbox gives out also start at the nearest road to me, but I guess in this situation, there should be at least a straight line added as a way of getting to the nearest road? Either that, or all these tiny segments should be in OSM, but I doubt that would happen in near term.

**Comment by danesfeder** [comment]
@kozyr Yeah this issue stems from our need to be exactly on the route for navigation to begin.  It isn't a great UX but we are working with our directions team to determine the best solution.  (i.e. - handling parking lots and the scenario you are encountering here)

**Comment by danesfeder** [comment]
Hey @kozyr this shouldn't be an issue with #756.  I believe your issue is you weren't receiving valid location updates from inside your apartment.  If this is the case now, we create a location update from the begging of the route - so navigation will always begin regardless of valid location updates
