### ISSUE TITLE
Usage of mapboxServices vs mapboxSdkServices

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#746]
We are including two different versions of [mapbox-java](https://github.com/mapbox/mapbox-java/) in this project. See [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/gradle/dependencies.gradle#L12-L13) and [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/build.gradle#L46-L48). Considering that we are using the `Maps SDK v5.5.0` we should remove `mapbox-java v3.0.0-beta.3`, that version of is only compatible with the beta versions of the 6.0.0 release or update maps to 6.0.0-beta.x and remove MAS 2.10.0.

**Comment by tobrun** [comment]
cc @danesfeder @zugaldia

**Comment by danesfeder** [comment]
@tobrun removing `mapbox-java v3.0.0-beta.3` would make us revert all the `3.0` code in the Nav SDK?

**Comment by zugaldia** [comment]
I think that ideally we'd work to remove `2.2.10` so that we only use the most recent version of MAS moving forward. Capturing from chat with @danesfeder, looks like this the goal of https://github.com/mapbox/mapbox-navigation-android/pull/697.

cc: @Guardiola31337 who is actively working on that PR and can comment on whther there's anything else needed to resolve the versions conflict.
