### ISSUE TITLE
NavigationView with Google API Client

### ISSUE THREAD

**Issue by jethro-yard8** [mapbox/mapbox-navigation-android#796]
My previous issue with the sdk was that i couldnt retrieve my user location for some unknown reason, now i  switched to using the Google API client to retrieve my location which is working great, however when i tap the map to set a marker my mapboxMap.addOnMapClickListener is not firing. Can i use the Navigation View in conjunction with the Google API client? Furthermore is there an example of an implementation which uses the google api client and navigation routing?

**Comment by danesfeder** [comment]
Hey @jethro-yard8 unfortunately, I can't evaluate if this problem is from our SDK given the details you've provided.  Not sure how the map click listeners correlates to the location services.  If you'd like to raise an issue:
 - Include a minimal demonstration of the bug, including code, logs, and screenshots.
 - Ensure you can reproduce the bug using the latest release.
 - Only post to report a bug or request a feature; direct all other questions to: https://stackoverflow.com/questions/tagged/mapbox
