### ISSUE TITLE
Navigation stops 30 meters before the destination.

### ISSUE THREAD

**Issue by OlafStaf** [mapbox/mapbox-navigation-android#80]
Hi, thanks for MapBox, and also for MapBox Navigation.
I have a strange problem with navigation. Navigation stops 30 meters before the destination, and stops updating the user's location.
My version of map-box-navigation is 0.3.0.

**Comment by cammace** [comment]
Are you using the Mock Location or is this happening in the real world?

**Comment by OlafStaf** [comment]
@cammace I am using Mock Location (Lockito application) with speed 10 km per hour. Is this related to this?

**Comment by mecoFarid** [comment]
I'm using mock location and `OffRouteListener` always triggered even I am on route.

**Comment by cammace** [comment]
Not quite sure why that would be happening since the Mock LocationEngine doesn't go off-route by default. We have an example in our testapp which uses the engine and handles everything as expected. I suggest [checking the code out there](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java) and ensuring you are doing everything correctly. You might also be using an older version of the navigation SDK which could have contained a bug around off-route.

**Comment by mecoFarid** [comment]
I meant Mock location as App (Fake GPS) not MockLocationEngine provided in SDK.
