### ISSUE TITLE
Add ability to simulate portions of route data and replay GPS traces 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#844]
The current implementation of `MockLocationEngine` can be given a `DirectionsRoute` and will begin mocking location updates at a set, static speed. 

We should add the ability to simulate only portions of a route (or slices), as well as the ability to replay GPS traces from a file.  This will increase testing versatility and allow us to simulate location updates through tunnels.

**Comment by Guardiola31337** [comment]
Is this going to be supported in the revamped `ReplayHistoryPlayer` / `ReplayHistoryLocationEngine` @kmadsen?

**Comment by kmadsen** [comment]
The remaining work for replaying a route is inside the [ReplayRouteDriver](https://github.com/mapbox/mapbox-navigation-android/pull/2802/files#diff-a4ab863681b076878569a40fd6ca5c45R12).

Right now it is navigating an entire `DirectionsRoute.geometry()`, but I'm working on making it route by `RouteLeg` because that is where the `LegAnnotation` is - want a better way to create the speed profiles.

So yes the portions we'll be able to simulate independently will be the `RouteLeg`s. The base layer routes geometry strings, so really you could simulate any geometry string independently.

**Comment by kmadsen** [comment]
This is done, use [ReplayRouteMapper](https://github.com/mapbox/mapbox-navigation-android/blob/e92d4b77a4d7f99a767dd6c6c49179d57486f377/libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapper.kt#L51)

You can replay any geometry
fun mapRouteLegGeometry(routeLeg: RouteLeg): List<ReplayEventBase>
fun mapGeometry(geometry: String): List<ReplayEventBase> 

We can also expose the replaying a point list
fun drivePointList(options: ReplayRouteOptions, points: List<Point>): List<ReplayRouteLocation>
