### ISSUE TITLE
Issue with initiating walking and cycling

### ISSUE THREAD

**Issue by excapade** [mapbox/mapbox-navigation-android#846]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior
 1. Initiating walking and cycling

### Expected behavior
- Walking and cycling route should show directions on initiated/start.

### Actual behavior
On starting, the app gets stuck and cycling/walking is never initiated.

**Comment by Guardiola31337** [comment]
Hey @excapade 👋 thanks for your question. This issue tracker is only for bug reports with test cases and feature requests. Please ask usage questions on Stack Overflow. https://stackoverflow.com/questions/tagged/mapbox

Feel free to open a new ticket providing some more information for reproducing the issue (minimal example) or any other specifics around your test setup (used device and Android API, version of the Navigation SDK, etc.). If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, we're unable to reproduce.

**Comment by excapade** [comment]
Hi @Guardiola31337 . I will add more information. thanks.
