### ISSUE TITLE
Navigation UI: Feedback Button

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#859]
`Device: Motorola TC55`

The Audio and Feedback Buttons Do Not Align Up - See Below.

![screenshot_2018-04-12-17-16-19](https://user-images.githubusercontent.com/32104383/38690246-2c2dc6a4-3e6d-11e8-84c8-0b9b07b8c835.png)

**Comment by danesfeder** [comment]
@Danny-James do you see this on your `Samsung Galaxy S8 - Android OS: 7.0` too?

**Comment by Danny-James** [comment]
@danesfeder No it's fine on any other device I have checked, I think it maybe something to do with the pixel density on this particular device?

Maybe the feedback button has to much right margin?

**Comment by Danny-James** [comment]
@danesfeder any chance of having this bumped into Version 13?

**Comment by danesfeder** [comment]
@Danny-James can you confirm screen dimensions of `4.3 in. Native Resolution. 480 x 800`

**Comment by Danny-James** [comment]
@danesfeder [TC55 Specs](https://www.zebra.com/us/en/products/spec-sheets/mobile-computers/handheld/tc55.html)

**Comment by danesfeder** [comment]
@Danny-James this Moto is [a troublemaker](https://github.com/mapbox/mapbox-navigation-android/issues/868) it seems :)  I can't figure out how the margins would be off here.  We don't create UI's specific to this lower API level.  And when I test on a similar res device, it works fine.   I also recreated an emulator that follows the same specs:

![screen shot 2018-04-18 at 1 17 46 pm](https://user-images.githubusercontent.com/8434572/38947767-c4d1b2ce-430b-11e8-9b68-7249ba92a884.png)

Any other ideas I can try on my side here?

**Comment by Danny-James** [comment]
@danesfeder No I don't have any other idea's on this, who is in charge of the UI Design/Implementation? Maybe they have some idea's on the issue here.

**Comment by P-Zenker** [comment]
Hey @Guardiola31337, this issue is still present (com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0):
- Google Nexus 6 (Android 7.1.1 | 2560 x 1440 | 5,96 Zoll (large) | 493 (xxxhdpi))
- MOBISTEL Cynus E4 (Android 5.1 | 800 x 480 | 4 Zoll (normal) | 240 (hdpi)

![2018-05-08 14 23 14](https://user-images.githubusercontent.com/23097192/39760505-c36f26f8-52d5-11e8-82cd-6d675f3fbaa7.jpg)

I want to hide this feedback button anyway but I didn't find any option in NavigationLauncherOptions :/

**Comment by Guardiola31337** [comment]
Hey @P-Zenker thanks for reaching out and report your issue.

Could you add some more information for reproducing the issue (minimal example) or any other specifics around your test setup? Do you get that misalignment running for example the `Navigation Views` activity from the test app using those devices? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.

I created a couple of emulators with the specs you provided and the `Navigation Views` activity from the test app but couldn't 👀 any issue on the buttons position 👇

`Nexus 6`

![nexus6](https://user-images.githubusercontent.com/1668582/39985432-efb93194-575e-11e8-9210-8af4e38a0423.png)

`Cynus E4`

![cynuse4](https://user-images.githubusercontent.com/1668582/39985610-55b1e946-575f-11e8-8716-528de226618a.png)

**Comment by P-Zenker** [comment]
It's just:
```
NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                                .directionsRoute(directionsRoute)
                                .shouldSimulateRoute(true)
                                .enableOffRouteDetection(true)
                                .unitType(NavigationUnitType.TYPE_METRIC)
                                .destination(Point.fromLngLat(CUNavigationUtil.Companion.getZiel().getLng(), CUNavigationUtil.Companion.getZiel().getLat()))
                                .locale(Locale.GERMAN)
                                .build();

NavigationLauncher.startNavigation(CUActivityNavigation.this, options);
```

I don't know which issue it was, but a issue months ago was only visible on physical devices.

**Comment by Guardiola31337** [comment]
> but a issue months ago

What do you mean? Is https://github.com/mapbox/mapbox-navigation-android/issues/859#issuecomment-387413283 still present? What device was used to take the screenshot shown in https://github.com/mapbox/mapbox-navigation-android/issues/859#issuecomment-387413283? Do you get the same misalignment using both devices (Nexus 6 and Cynus E4)?

> only visible on physical devices

> Do you get that misalignment running for example the `Navigation Views` activity from the test app using those devices?

Could you test ☝️ with the mentioned devices? I don't have them physically 😬

**Comment by BradKwon** [comment]
@P-Zenker Hello, I had the exact same issue and resolved it just a while ago.

In my case, it was because of using higher version of Support.ConstraintLayout. I had used its ver. 1.1.0 and found out that the Navigation UI sample app uses ver. 1.0.2. I downgraded it to 1.0.2.2 and buttons are aligned.

Hope that this would help you :)

**Comment by Guardiola31337** [comment]
@BradKwon thanks 🙏
> Thank you, that's the solution!

@P-Zenker great to hear! Thanks for the update.

> But is there a way to hide this feedback button?

We're keeping track of that feature request in https://github.com/mapbox/mapbox-navigation-android/issues/634

Thanks again!

**Comment by BradKwon** [comment]
@Guardiola31337 Thank you for the quick update! 💯
