### ISSUE TITLE
Current Location Cannot be found,shows wrong location near Nigeria. 

### ISSUE THREAD

**Issue by mrunal7761** [mapbox/mapbox-navigation-android#989]
Current location cannot be found as per given examples in github,i tried to implement this piece of code,but not successful.
I used code example given [here.](https://www.mapbox.com/help/android-navigation-sdk/)

		LocationEngineProvider locationEngineProvider = new 
		LocationEngineProvider(NavigationActivity.this);
		locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
		locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
		locationEngine.activate();

		Location lastLocation = locationEngine.getLastLocation();
		if (lastLocation != null) {
			originLocation = lastLocation;
			setCameraPosition(lastLocation);
		} else {
			locationEngine.addLocationEngineListener(this);
		}

Permissions I used are:

		<uses-permission android:name="android.permission.INTERNET"/>
		<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
		<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
		<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
		<uses-permission android:name="android.permission.WAKE_LOCK"/>
		<uses-feature android:name="android.hardware.location.gps"/>

Gradle Details are here:

		compileSdkVersion 27

		minSdkVersion 15
		targetSdkVersion 27
		multiDexEnabled true

		implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.3@aar') {
		transitive=true
		}
		implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.3'
		implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
		implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0') {
		transitive = true
		}

**Comment by Guardiola31337** [comment]
Hey @mrunal7761 👋 Thanks for reaching out and report your issue.

This is being tracked in https://github.com/mapbox/mapbox-events-android/issues/158

In order to display the user’s location on the map, I encourage you to also check the [Location Layer plugin documentation](https://www.mapbox.com/android-docs/plugins/overview/location-layer/).

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!

Closing as duplicated.

cc @electrostat

**Comment by mrunal7761** [comment]
@Guardiola31337 ,can you help me please, i m not getting proper response,so i posted it twice,please help,if you can,because its been days,i cant get current location.. please.
